//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//

/** @file
  ACPI MIPICAM table

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2022 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification
**/

  // Define a Global region of ACPI NVS Region that may be used for any
  // type of implementation.  The starting offset and size will be fixed
  // up by the System BIOS during POST.  Note that the Size must be a word
  // in size to be fixed up correctly.

#ifndef _MIPI_CAM_NVS_AREA_DEF_H_
#define _MIPI_CAM_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  //
  // MipiCam specific
  //
  UINT8    MipiCamControlLogic0;                    ///< Offset 0
  UINT8    MipiCamControlLogic1;                    ///< Offset 1
  UINT8    MipiCamControlLogic2;                    ///< Offset 2
  UINT8    MipiCamControlLogic3;                    ///< Offset 3
  UINT8    MipiCamControlLogic4;                    ///< Offset 4
  UINT8    MipiCamControlLogic5;                    ///< Offset 5
  UINT8    MipiCamLink0Enabled;                     ///< Offset 6
  UINT8    MipiCamLink1Enabled;                     ///< Offset 7
  UINT8    MipiCamLink2Enabled;                     ///< Offset 8
  UINT8    MipiCamLink3Enabled;                     ///< Offset 9
  UINT8    MipiCamLink4Enabled;                     ///< Offset 10
  UINT8    MipiCamLink5Enabled;                     ///< Offset 11
  UINT8    MipiCamLanesClkDiv;                      ///< Offset 12
  // Control Logic 0 options
  UINT8    MipiCamCtrlLogic0_Version;               ///< Offset 13      Version of CLDB structure
  UINT8    MipiCamCtrlLogic0_Type;                  ///< Offset 14      Type
  UINT8    MipiCamCtrlLogic0_CrdVersion;            ///< Offset 15      Version of CRD
  UINT32   MipiCamCtrlLogic0_InputClock;            ///< Offset 16      Input Clock
  UINT8    MipiCamCtrlLogic0_GpioPinsEnabled;       ///< Offset 20      Number of GPIO Pins enabled
  UINT8    MipiCamCtrlLogic0_I2cBus;                ///< Offset 21      I2C Serial Bus Number
  UINT16   MipiCamCtrlLogic0_I2cAddress;            ///< Offset 22      I2C Address
  UINT8    MipiCamCtrlLogic0_GpioGroupPadNumber[6]; ///< Offset 24      GPIO Group Pad Number
  UINT8    MipiCamCtrlLogic0_GpioGroupNumber[6];    ///< Offset 30      GPIO Group Number
  UINT8    MipiCamCtrlLogic0_GpioFunction[6];       ///< Offset 36      GPIO Function
  UINT8    MipiCamCtrlLogic0_GpioActiveValue[6];    ///< Offset 42      GPIO Active Value
  UINT8    MipiCamCtrlLogic0_GpioInitialValue[6];   ///< Offset 48      GPIO Initial Value
  UINT8    MipiCamCtrlLogic0_Pld;                   ///< Offset 54      Camera Position
  UINT8    MipiCamCtrlLogic0_Wled1FlashMaxCurrent;  ///< Offset 55      WLED1 Flash Max Current
  UINT8    MipiCamCtrlLogic0_Wled1TorchMaxCurrent;  ///< Offset 56      WLED1 Torch Max Current
  UINT8    MipiCamCtrlLogic0_Wled2FlashMaxCurrent;  ///< Offset 57      WLED2 Flash Max Current
  UINT8    MipiCamCtrlLogic0_Wled2TorchMaxCurrent;  ///< Offset 58      WLED2 Torch Max Current
  UINT8    MipiCamCtrlLogic0_Wled1Type;             ///< Offset 59      WLED1 Type
  UINT8    MipiCamCtrlLogic0_Wled2Type;             ///< Offset 60      WLED2 Type
  UINT8    MipiCamCtrlLogic0_PchClockSource;        ///< Offset 61      PCH Clock source
  // Control Logic 1 options
  UINT8    MipiCamCtrlLogic1_Version;               ///< Offset 62      Version of CLDB structure
  UINT8    MipiCamCtrlLogic1_Type;                  ///< Offset 63      Type
  UINT8    MipiCamCtrlLogic1_CrdVersion;            ///< Offset 64      Version of CRD
  UINT32   MipiCamCtrlLogic1_InputClock;            ///< Offset 65      Input Clock
  UINT8    MipiCamCtrlLogic1_GpioPinsEnabled;       ///< Offset 69      Number of GPIO Pins enabled
  UINT8    MipiCamCtrlLogic1_I2cBus;                ///< Offset 70      I2C Serial Bus Number
  UINT16   MipiCamCtrlLogic1_I2cAddress;            ///< Offset 71      I2C Address
  UINT8    MipiCamCtrlLogic1_GpioGroupPadNumber[6]; ///< Offset 73      GPIO Group Pad Number
  UINT8    MipiCamCtrlLogic1_GpioGroupNumber[6];    ///< Offset 79      GPIO Group Number
  UINT8    MipiCamCtrlLogic1_GpioFunction[6];       ///< Offset 85      GPIO Function
  UINT8    MipiCamCtrlLogic1_GpioActiveValue[6];    ///< Offset 91      GPIO Active Value
  UINT8    MipiCamCtrlLogic1_GpioInitialValue[6];   ///< Offset 97      GPIO Initial Value
  UINT8    MipiCamCtrlLogic1_Pld;                   ///< Offset 103     Camera Position
  UINT8    MipiCamCtrlLogic1_Wled1FlashMaxCurrent;  ///< Offset 104     WLED1 Flash Max Current
  UINT8    MipiCamCtrlLogic1_Wled1TorchMaxCurrent;  ///< Offset 105     WLED1 Torch Max Current
  UINT8    MipiCamCtrlLogic1_Wled2FlashMaxCurrent;  ///< Offset 106     WLED2 Flash Max Current
  UINT8    MipiCamCtrlLogic1_Wled2TorchMaxCurrent;  ///< Offset 107     WLED2 Torch Max Current
  UINT8    MipiCamCtrlLogic1_Wled1Type;             ///< Offset 108     WLED1 Type
  UINT8    MipiCamCtrlLogic1_Wled2Type;             ///< Offset 109     WLED2 Type
  UINT8    MipiCamCtrlLogic1_PchClockSource;        ///< Offset 110     PCH Clock source
  // Control Logic 2 options
  UINT8    MipiCamCtrlLogic2_Version;               ///< Offset 111     Version of CLDB structure
  UINT8    MipiCamCtrlLogic2_Type;                  ///< Offset 112     Type
  UINT8    MipiCamCtrlLogic2_CrdVersion;            ///< Offset 113     Version of CRD
  UINT32   MipiCamCtrlLogic2_InputClock;            ///< Offset 114     Input Clock
  UINT8    MipiCamCtrlLogic2_GpioPinsEnabled;       ///< Offset 118     Number of GPIO Pins enabled
  UINT8    MipiCamCtrlLogic2_I2cBus;                ///< Offset 119     I2C Serial Bus Number
  UINT16   MipiCamCtrlLogic2_I2cAddress;            ///< Offset 120     I2C Address
  UINT8    MipiCamCtrlLogic2_GpioGroupPadNumber[6]; ///< Offset 122     GPIO Group Pad Number
  UINT8    MipiCamCtrlLogic2_GpioGroupNumber[6];    ///< Offset 128     GPIO Group Number
  UINT8    MipiCamCtrlLogic2_GpioFunction[6];       ///< Offset 134     GPIO Function
  UINT8    MipiCamCtrlLogic2_GpioActiveValue[6];    ///< Offset 140     GPIO Active Value
  UINT8    MipiCamCtrlLogic2_GpioInitialValue[6];   ///< Offset 146     GPIO Initial Value
  UINT8    MipiCamCtrlLogic2_Pld;                   ///< Offset 152     Camera Position
  UINT8    MipiCamCtrlLogic2_Wled1FlashMaxCurrent;  ///< Offset 153     WLED1 Flash Max Current
  UINT8    MipiCamCtrlLogic2_Wled1TorchMaxCurrent;  ///< Offset 154     WLED1 Torch Max Current
  UINT8    MipiCamCtrlLogic2_Wled2FlashMaxCurrent;  ///< Offset 155     WLED2 Flash Max Current
  UINT8    MipiCamCtrlLogic2_Wled2TorchMaxCurrent;  ///< Offset 156     WLED2 Torch Max Current
  UINT8    MipiCamCtrlLogic2_Wled1Type;             ///< Offset 157     WLED1 Type
  UINT8    MipiCamCtrlLogic2_Wled2Type;             ///< Offset 158     WLED2 Type
  UINT8    MipiCamCtrlLogic2_PchClockSource;        ///< Offset 159     PCH Clock source
  // Control Logic 3 options
  UINT8    MipiCamCtrlLogic3_Version;               ///< Offset 160     Version of CLDB structure
  UINT8    MipiCamCtrlLogic3_Type;                  ///< Offset 161     Type
  UINT8    MipiCamCtrlLogic3_CrdVersion;            ///< Offset 162     Version of CRD
  UINT32   MipiCamCtrlLogic3_InputClock;            ///< Offset 163     Input Clock
  UINT8    MipiCamCtrlLogic3_GpioPinsEnabled;       ///< Offset 167     Number of GPIO Pins enabled
  UINT8    MipiCamCtrlLogic3_I2cBus;                ///< Offset 168     I2C Serial Bus Number
  UINT16   MipiCamCtrlLogic3_I2cAddress;            ///< Offset 169     I2C Address
  UINT8    MipiCamCtrlLogic3_GpioGroupPadNumber[6]; ///< Offset 171     GPIO Group Pad Number
  UINT8    MipiCamCtrlLogic3_GpioGroupNumber[6];    ///< Offset 177     GPIO Group Number
  UINT8    MipiCamCtrlLogic3_GpioFunction[6];       ///< Offset 183     GPIO Function
  UINT8    MipiCamCtrlLogic3_GpioActiveValue[6];    ///< Offset 189     GPIO Active Value
  UINT8    MipiCamCtrlLogic3_GpioInitialValue[6];   ///< Offset 195     GPIO Initial Value
  UINT8    MipiCamCtrlLogic3_Pld;                   ///< Offset 201     Camera Position
  UINT8    MipiCamCtrlLogic3_Wled1FlashMaxCurrent;  ///< Offset 202     WLED1 Flash Max Current
  UINT8    MipiCamCtrlLogic3_Wled1TorchMaxCurrent;  ///< Offset 203     WLED1 Torch Max Current
  UINT8    MipiCamCtrlLogic3_Wled2FlashMaxCurrent;  ///< Offset 204     WLED2 Flash Max Current
  UINT8    MipiCamCtrlLogic3_Wled2TorchMaxCurrent;  ///< Offset 205     WLED2 Torch Max Current
  UINT8    MipiCamCtrlLogic3_Wled1Type;             ///< Offset 206     WLED1 Type
  UINT8    MipiCamCtrlLogic3_Wled2Type;             ///< Offset 207     WLED2 Type
  UINT8    MipiCamCtrlLogic3_PchClockSource;        ///< Offset 208     PCH Clock source
  // Control Logic 4 options
  UINT8    MipiCamCtrlLogic4_Version;               ///< Offset 209     Version of CLDB structure
  UINT8    MipiCamCtrlLogic4_Type;                  ///< Offset 210     Type
  UINT8    MipiCamCtrlLogic4_CrdVersion;            ///< Offset 211     Version of CRD
  UINT32   MipiCamCtrlLogic4_InputClock;            ///< Offset 212     Input Clock
  UINT8    MipiCamCtrlLogic4_GpioPinsEnabled;       ///< Offset 216     Number of GPIO Pins enabled
  UINT8    MipiCamCtrlLogic4_I2cBus;                ///< Offset 217     I2C Serial Bus Number
  UINT16   MipiCamCtrlLogic4_I2cAddress;            ///< Offset 218     I2C Address
  UINT8    MipiCamCtrlLogic4_GpioGroupPadNumber[6]; ///< Offset 220     GPIO Group Pad Number
  UINT8    MipiCamCtrlLogic4_GpioGroupNumber[6];    ///< Offset 226     GPIO Group Number
  UINT8    MipiCamCtrlLogic4_GpioFunction[6];       ///< Offset 232     GPIO Function
  UINT8    MipiCamCtrlLogic4_GpioActiveValue[6];    ///< Offset 238     GPIO Active Value
  UINT8    MipiCamCtrlLogic4_GpioInitialValue[6];   ///< Offset 244     GPIO Initial Value
  UINT8    MipiCamCtrlLogic4_Pld;                   ///< Offset 250     Camera Position
  UINT8    MipiCamCtrlLogic4_Wled1FlashMaxCurrent;  ///< Offset 251     WLED1 Flash Max Current
  UINT8    MipiCamCtrlLogic4_Wled1TorchMaxCurrent;  ///< Offset 252     WLED1 Torch Max Current
  UINT8    MipiCamCtrlLogic4_Wled2FlashMaxCurrent;  ///< Offset 253     WLED2 Flash Max Current
  UINT8    MipiCamCtrlLogic4_Wled2TorchMaxCurrent;  ///< Offset 254     WLED2 Torch Max Current
  UINT8    MipiCamCtrlLogic4_Wled1Type;             ///< Offset 255     WLED1 Type
  UINT8    MipiCamCtrlLogic4_Wled2Type;             ///< Offset 256     WLED2 Type
  UINT8    MipiCamCtrlLogic4_PchClockSource;        ///< Offset 257     PCH Clock source
  // Control Logic 5 options
  UINT8    MipiCamCtrlLogic5_Version;               ///< Offset 258     Version of CLDB structure
  UINT8    MipiCamCtrlLogic5_Type;                  ///< Offset 259     Type
  UINT8    MipiCamCtrlLogic5_CrdVersion;            ///< Offset 260     Version of CRD
  UINT32   MipiCamCtrlLogic5_InputClock;            ///< Offset 261     Input Clock
  UINT8    MipiCamCtrlLogic5_GpioPinsEnabled;       ///< Offset 265     Number of GPIO Pins enabled
  UINT8    MipiCamCtrlLogic5_I2cBus;                ///< Offset 266     I2C Serial Bus Number
  UINT16   MipiCamCtrlLogic5_I2cAddress;            ///< Offset 267     I2C Address
  UINT8    MipiCamCtrlLogic5_GpioGroupPadNumber[6]; ///< Offset 269     GPIO Group Pad Number
  UINT8    MipiCamCtrlLogic5_GpioGroupNumber[6];    ///< Offset 275     GPIO Group Number
  UINT8    MipiCamCtrlLogic5_GpioFunction[6];       ///< Offset 281     GPIO Function
  UINT8    MipiCamCtrlLogic5_GpioActiveValue[6];    ///< Offset 287     GPIO Active Value
  UINT8    MipiCamCtrlLogic5_GpioInitialValue[6];   ///< Offset 293     GPIO Initial Value
  UINT8    MipiCamCtrlLogic5_Pld;                   ///< Offset 299     Camera Position
  UINT8    MipiCamCtrlLogic5_Wled1FlashMaxCurrent;  ///< Offset 300     WLED1 Flash Max Current
  UINT8    MipiCamCtrlLogic5_Wled1TorchMaxCurrent;  ///< Offset 301     WLED1 Torch Max Current
  UINT8    MipiCamCtrlLogic5_Wled2FlashMaxCurrent;  ///< Offset 302     WLED2 Flash Max Current
  UINT8    MipiCamCtrlLogic5_Wled2TorchMaxCurrent;  ///< Offset 303     WLED2 Torch Max Current
  UINT8    MipiCamCtrlLogic5_Wled1Type;             ///< Offset 304     WLED1 Type
  UINT8    MipiCamCtrlLogic5_Wled2Type;             ///< Offset 305     WLED2 Type
  UINT8    MipiCamCtrlLogic5_PchClockSource;        ///< Offset 306     PCH Clock source
  // Mipi Cam Link0 options
  UINT8    MipiCamLink0SensorModel;                 ///< Offset 307     Sensor Model
  UINT8    MipiCamLink0UserHid[9];                  ///< Offset 308     User defined HID ASCII character 0
                                                    ///< Offset 316     User defined HID ASCII character 8
  UINT8    MipiCamLink0Pld;                         ///< Offset 317     Camera Position
  UINT8    MipiCamLink0ModuleName[16];              ///< Offset 318     Camera Module Name ASCII character 0
                                                    ///< Offset 333     Camera Module Name ASCII character 15
  UINT8    MipiCamLink0I2cDevicesEnabled;           ///< Offset 334     Number of I2C devices
  UINT8    MipiCamLink0I2cBus;                      ///< Offset 335     I2C Serial Bus number
  UINT16   MipiCamLink0I2cAddrDev[12];              ///< Offset 336     Address of I2C Device0 on Link0
                                                    ///< Offset 338     Address of I2C Device1 on Link0
                                                    ///< Offset 340     Address of I2C Device2 on Link0
                                                    ///< Offset 342     Address of I2C Device3 on Link0
                                                    ///< Offset 344     Address of I2C Device4 on Link0
                                                    ///< Offset 346     Address of I2C Device5 on Link0
                                                    ///< Offset 348     Address of I2C Device6 on Link0
                                                    ///< Offset 350     Address of I2C Device7 on Link0
                                                    ///< Offset 352     Address of I2C Device8 on Link0
                                                    ///< Offset 354     Address of I2C Device9 on Link0
                                                    ///< Offset 356     Address of I2C Device10 on Link0
                                                    ///< Offset 358     Address of I2C Device11 on Link0
  UINT8    MipiCamLink0I2cDeviceType[12];           ///< Offset 360     Type of I2C Device0 on Link0
                                                    ///< Offset 361     Type of I2C Device1 on Link0
                                                    ///< Offset 362     Type of I2C Device2 on Link0
                                                    ///< Offset 363     Type of I2C Device3 on Link0
                                                    ///< Offset 364     Type of I2C Device4 on Link0
                                                    ///< Offset 365     Type of I2C Device5 on Link0
                                                    ///< Offset 366     Type of I2C Device6 on Link0
                                                    ///< Offset 367     Type of I2C Device7 on Link0
                                                    ///< Offset 368     Type of I2C Device8 on Link0
                                                    ///< Offset 369     Type of I2C Device9 on Link0
                                                    ///< Offset 370     Type of I2C Device10 on Link0
                                                    ///< Offset 371     Type of I2C Device11 on Link0
  UINT8    MipiCamLink0DD_Version;                  ///< Offset 372     Version of SSDB structure
  UINT8    MipiCamLink0DD_CrdVersion;               ///< Offset 373     Version of CRD
  UINT8    MipiCamLink0DD_LinkUsed;                 ///< Offset 374     CSI2 Link used
  UINT8    MipiCamLink0DD_LaneUsed;                 ///< Offset 375     MIPI-CSI2 Data Lane
  UINT8    MipiCamLink0DD_EepromType;               ///< Offset 376     EEPROM Type
  UINT8    MipiCamLink0DD_VcmType;                  ///< Offset 377     VCM Type
  UINT8    MipiCamLink0DD_FlashSupport;             ///< Offset 378     Flash Support
  UINT8    MipiCamLink0DD_PrivacyLed;               ///< Offset 379     Privacy LED
  UINT8    MipiCamLink0DD_Degree;                   ///< Offset 380     Degree
  UINT32   MipiCamLink0DD_Mclk;                     ///< Offset 381     MCLK
  UINT8    MipiCamLink0DD_ControlLogic;             ///< Offset 385     Control Logic
  UINT8    MipiCamLink0DD_PmicPosition;             ///< Offset 386     PMIC Position
  UINT8    MipiCamLink0DD_VoltageRail;              ///< Offset 387     Voltage Rail
  UINT8    MipiCamLink0DD_PhyConfiguration;         ///< Offset 388     Phy Configuratioin
  UINT8    MipiCamLink0DD_LaneConfiguration;        ///< Offset 389     Lane Configuratioin
  UINT8    MipiCamLink0_FlashDriverSelection;       ///< Offset 390     Flash Driver Selection
  UINT8    MipiCamLink0DD_FlashID;                  ///< Offset 391     Flash ID for Link0
  // Mipi Cam Link1 options
  UINT8    MipiCamLink1SensorModel;                 ///< Offset 392     Sensor Model
  UINT8    MipiCamLink1UserHid[9];                  ///< Offset 393     User defined HID ASCII character 0
                                                    ///< Offset 401     User defined HID ASCII character 8
  UINT8    MipiCamLink1Pld;                         ///< Offset 402     Camera Position
  UINT8    MipiCamLink1ModuleName[16];              ///< Offset 403     Camera Module Name ASCII character 0
                                                    ///< Offset 418     Camera Module Name ASCII character 15
  UINT8    MipiCamLink1I2cDevicesEnabled;           ///< Offset 419     Number of I2C devices
  UINT8    MipiCamLink1I2cBus;                      ///< Offset 420     I2C Serial Bus number
  UINT16   MipiCamLink1I2cAddrDev[12];              ///< Offset 421     Address of I2C Device0 on Link1
                                                    ///< Offset 423     Address of I2C Device1 on Link1
                                                    ///< Offset 425     Address of I2C Device2 on Link1
                                                    ///< Offset 427     Address of I2C Device3 on Link1
                                                    ///< Offset 429     Address of I2C Device4 on Link1
                                                    ///< Offset 431     Address of I2C Device5 on Link1
                                                    ///< Offset 433     Address of I2C Device6 on Link1
                                                    ///< Offset 435     Address of I2C Device7 on Link1
                                                    ///< Offset 437     Address of I2C Device8 on Link1
                                                    ///< Offset 439     Address of I2C Device9 on Link1
                                                    ///< Offset 441     Address of I2C Device10 on Link1
                                                    ///< Offset 443     Address of I2C Device11 on Link1
  UINT8    MipiCamLink1I2cDeviceType[12];           ///< Offset 445     Type of I2C Device0 on Link1
                                                    ///< Offset 446     Type of I2C Device1 on Link1
                                                    ///< Offset 447     Type of I2C Device2 on Link1
                                                    ///< Offset 448     Type of I2C Device3 on Link1
                                                    ///< Offset 449     Type of I2C Device4 on Link1
                                                    ///< Offset 450     Type of I2C Device5 on Link1
                                                    ///< Offset 451     Type of I2C Device6 on Link1
                                                    ///< Offset 452     Type of I2C Device7 on Link1
                                                    ///< Offset 453     Type of I2C Device8 on Link1
                                                    ///< Offset 454     Type of I2C Device9 on Link1
                                                    ///< Offset 455     Type of I2C Device10 on Link1
                                                    ///< Offset 456     Type of I2C Device11 on Link1
  UINT8    MipiCamLink1DD_Version;                  ///< Offset 457     Version of SSDB structure
  UINT8    MipiCamLink1DD_CrdVersion;               ///< Offset 458     Version of CRD
  UINT8    MipiCamLink1DD_LinkUsed;                 ///< Offset 459     CSI2 Link used
  UINT8    MipiCamLink1DD_LaneUsed;                 ///< Offset 460     MIPI-CSI2 Data Lane
  UINT8    MipiCamLink1DD_EepromType;               ///< Offset 461     EEPROM Type
  UINT8    MipiCamLink1DD_VcmType;                  ///< Offset 462     VCM Type
  UINT8    MipiCamLink1DD_FlashSupport;             ///< Offset 463     Flash Support
  UINT8    MipiCamLink1DD_PrivacyLed;               ///< Offset 464     Privacy LED
  UINT8    MipiCamLink1DD_Degree;                   ///< Offset 465     Degree
  UINT32   MipiCamLink1DD_Mclk;                     ///< Offset 466     MCLK
  UINT8    MipiCamLink1DD_ControlLogic;             ///< Offset 470     Control Logic
  UINT8    MipiCamLink1DD_PmicPosition;             ///< Offset 471     PMIC Position
  UINT8    MipiCamLink1DD_VoltageRail;              ///< Offset 472     Voltage Rail
  UINT8    MipiCamLink1DD_PhyConfiguration;         ///< Offset 473     Phy Configuratioin
  UINT8    MipiCamLink1DD_LaneConfiguration;        ///< Offset 474     Lane Configuratioin
  UINT8    MipiCamLink1_FlashDriverSelection;       ///< Offset 475     Flash Driver Selection
  UINT8    MipiCamLink1DD_FlashID;                  ///< Offset 476     Flash ID for Link1
  // Mipi Cam Link2 options
  UINT8    MipiCamLink2SensorModel;                 ///< Offset 477     Sensor Model
  UINT8    MipiCamLink2UserHid[9];                  ///< Offset 478     User defined HID ASCII character 0
                                                    ///< Offset 486     User defined HID ASCII character 8
  UINT8    MipiCamLink2Pld;                         ///< Offset 487     Camera Position
  UINT8    MipiCamLink2ModuleName[16];              ///< Offset 488     Camera Module Name ASCII character 0
                                                    ///< Offset 503     Camera Module Name ASCII character 15
  UINT8    MipiCamLink2I2cDevicesEnabled;           ///< Offset 504     Number of I2C devices
  UINT8    MipiCamLink2I2cBus;                      ///< Offset 505     I2C Serial Bus number
  UINT16   MipiCamLink2I2cAddrDev[12];              ///< Offset 506     Address of I2C Device0 on Link2
                                                    ///< Offset 508     Address of I2C Device1 on Link2
                                                    ///< Offset 510     Address of I2C Device2 on Link2
                                                    ///< Offset 512     Address of I2C Device3 on Link2
                                                    ///< Offset 514     Address of I2C Device4 on Link2
                                                    ///< Offset 516     Address of I2C Device5 on Link2
                                                    ///< Offset 518     Address of I2C Device6 on Link2
                                                    ///< Offset 520     Address of I2C Device7 on Link2
                                                    ///< Offset 522     Address of I2C Device8 on Link2
                                                    ///< Offset 524     Address of I2C Device9 on Link2
                                                    ///< Offset 526     Address of I2C Device10 on Link2
                                                    ///< Offset 528     Address of I2C Device11 on Link2
  UINT8    MipiCamLink2I2cDeviceType[12];           ///< Offset 530     Type of I2C Device0 on Link2
                                                    ///< Offset 531     Type of I2C Device1 on Link2
                                                    ///< Offset 532     Type of I2C Device2 on Link2
                                                    ///< Offset 533     Type of I2C Device3 on Link2
                                                    ///< Offset 534     Type of I2C Device4 on Link2
                                                    ///< Offset 535     Type of I2C Device5 on Link2
                                                    ///< Offset 536     Type of I2C Device6 on Link2
                                                    ///< Offset 537     Type of I2C Device7 on Link2
                                                    ///< Offset 538     Type of I2C Device8 on Link2
                                                    ///< Offset 539     Type of I2C Device9 on Link2
                                                    ///< Offset 540     Type of I2C Device10 on Link2
                                                    ///< Offset 541     Type of I2C Device11 on Link2
  UINT8    MipiCamLink2DD_Version;                  ///< Offset 542     Version of SSDB structure
  UINT8    MipiCamLink2DD_CrdVersion;               ///< Offset 543     Version of CRD
  UINT8    MipiCamLink2DD_LinkUsed;                 ///< Offset 544     CSI2 Link used
  UINT8    MipiCamLink2DD_LaneUsed;                 ///< Offset 545     MIPI-CSI2 Data Lane
  UINT8    MipiCamLink2DD_EepromType;               ///< Offset 546     EEPROM Type
  UINT8    MipiCamLink2DD_VcmType;                  ///< Offset 547     VCM Type
  UINT8    MipiCamLink2DD_FlashSupport;             ///< Offset 548     Flash Support
  UINT8    MipiCamLink2DD_PrivacyLed;               ///< Offset 549     Privacy LED
  UINT8    MipiCamLink2DD_Degree;                   ///< Offset 550     Degree
  UINT32   MipiCamLink2DD_Mclk;                     ///< Offset 551     MCLK
  UINT8    MipiCamLink2DD_ControlLogic;             ///< Offset 555     Control Logic
  UINT8    MipiCamLink2DD_PmicPosition;             ///< Offset 556     PMIC Position
  UINT8    MipiCamLink2DD_VoltageRail;              ///< Offset 557     Voltage Rail
  UINT8    MipiCamLink2DD_PhyConfiguration;         ///< Offset 558     Phy Configuratioin
  UINT8    MipiCamLink2DD_LaneConfiguration;        ///< Offset 559     Lane Configuratioin
  UINT8    MipiCamLink2_FlashDriverSelection;       ///< Offset 560     Flash Driver Selection
  UINT8    MipiCamLink2DD_FlashID;                  ///< Offset 561     Flash ID for Link2
  // Mipi Cam Link3 options
  UINT8    MipiCamLink3SensorModel;                 ///< Offset 562     Sensor Model
  UINT8    MipiCamLink3UserHid[9];                  ///< Offset 563     User defined HID ASCII character 0
                                                    ///< Offset 571     User defined HID ASCII character 8
  UINT8    MipiCamLink3Pld;                         ///< Offset 572     Camera Position
  UINT8    MipiCamLink3ModuleName[16];              ///< Offset 573     Camera Module Name ASCII character 0
                                                    ///< Offset 588     Camera Module Name ASCII character 15
  UINT8    MipiCamLink3I2cDevicesEnabled;           ///< Offset 589     Number of I2C devices
  UINT8    MipiCamLink3I2cBus;                      ///< Offset 590     I2C Serial Bus number
  UINT16   MipiCamLink3I2cAddrDev[12];              ///< Offset 591     Address of I2C Device0 on Link3
                                                    ///< Offset 593     Address of I2C Device1 on Link3
                                                    ///< Offset 595     Address of I2C Device2 on Link3
                                                    ///< Offset 597     Address of I2C Device3 on Link3
                                                    ///< Offset 599     Address of I2C Device4 on Link3
                                                    ///< Offset 601     Address of I2C Device5 on Link3
                                                    ///< Offset 603     Address of I2C Device6 on Link3
                                                    ///< Offset 605     Address of I2C Device7 on Link3
                                                    ///< Offset 607     Address of I2C Device8 on Link3
                                                    ///< Offset 609     Address of I2C Device9 on Link3
                                                    ///< Offset 611     Address of I2C Device10 on Link3
                                                    ///< Offset 613     Address of I2C Device11 on Link3
  UINT8    MipiCamLink3I2cDeviceType[12];           ///< Offset 615     Type of I2C Device0 on Link3
                                                    ///< Offset 616     Type of I2C Device1 on Link3
                                                    ///< Offset 617     Type of I2C Device2 on Link3
                                                    ///< Offset 618     Type of I2C Device3 on Link3
                                                    ///< Offset 619     Type of I2C Device4 on Link3
                                                    ///< Offset 620     Type of I2C Device5 on Link3
                                                    ///< Offset 621     Type of I2C Device6 on Link3
                                                    ///< Offset 622     Type of I2C Device7 on Link3
                                                    ///< Offset 623     Type of I2C Device8 on Link3
                                                    ///< Offset 624     Type of I2C Device9 on Link3
                                                    ///< Offset 625     Type of I2C Device10 on Link3
                                                    ///< Offset 626     Type of I2C Device11 on Link3
  UINT8    MipiCamLink3DD_Version;                  ///< Offset 627     Version of SSDB structure
  UINT8    MipiCamLink3DD_CrdVersion;               ///< Offset 628     Version of CRD
  UINT8    MipiCamLink3DD_LinkUsed;                 ///< Offset 629     CSI2 Link used
  UINT8    MipiCamLink3DD_LaneUsed;                 ///< Offset 630     MIPI-CSI2 Data Lane
  UINT8    MipiCamLink3DD_EepromType;               ///< Offset 631     EEPROM Type
  UINT8    MipiCamLink3DD_VcmType;                  ///< Offset 632     VCM Type
  UINT8    MipiCamLink3DD_FlashSupport;             ///< Offset 633     Flash Support
  UINT8    MipiCamLink3DD_PrivacyLed;               ///< Offset 634     Privacy LED
  UINT8    MipiCamLink3DD_Degree;                   ///< Offset 635     Degree
  UINT32   MipiCamLink3DD_Mclk;                     ///< Offset 636     MCLK
  UINT8    MipiCamLink3DD_ControlLogic;             ///< Offset 640     Control Logic
  UINT8    MipiCamLink3DD_PmicPosition;             ///< Offset 641     PMIC Position
  UINT8    MipiCamLink3DD_VoltageRail;              ///< Offset 642     Voltage Rail
  UINT8    MipiCamLink3DD_PhyConfiguration;         ///< Offset 643     Phy Configuratioin
  UINT8    MipiCamLink3DD_LaneConfiguration;        ///< Offset 644     Lane Configuratioin
  UINT8    MipiCamLink3_FlashDriverSelection;       ///< Offset 645     Flash Driver Selection
  UINT8    MipiCamLink3DD_FlashID;                  ///< Offset 646     Flash ID for Link3
  // Mipi Cam Link4 options
  UINT8    MipiCamLink4SensorModel;                 ///< Offset 647     Sensor Model
  UINT8    MipiCamLink4UserHid[9];                  ///< Offset 648     User defined HID ASCII character 0
                                                    ///< Offset 656     User defined HID ASCII character 8
  UINT8    MipiCamLink4Pld;                         ///< Offset 657     Camera Position
  UINT8    MipiCamLink4ModuleName[16];              ///< Offset 658     Camera Module Name ASCII character 0
                                                    ///< Offset 673     Camera Module Name ASCII character 15
  UINT8    MipiCamLink4I2cDevicesEnabled;           ///< Offset 674     Number of I2C devices
  UINT8    MipiCamLink4I2cBus;                      ///< Offset 675     I2C Serial Bus number
  UINT16   MipiCamLink4I2cAddrDev[12];              ///< Offset 676     Address of I2C Device0 on Link4
                                                    ///< Offset 678     Address of I2C Device1 on Link4
                                                    ///< Offset 680     Address of I2C Device2 on Link4
                                                    ///< Offset 682     Address of I2C Device3 on Link4
                                                    ///< Offset 684     Address of I2C Device4 on Link4
                                                    ///< Offset 686     Address of I2C Device5 on Link4
                                                    ///< Offset 688     Address of I2C Device6 on Link4
                                                    ///< Offset 690     Address of I2C Device7 on Link4
                                                    ///< Offset 692     Address of I2C Device8 on Link4
                                                    ///< Offset 694     Address of I2C Device9 on Link4
                                                    ///< Offset 696     Address of I2C Device10 on Link4
                                                    ///< Offset 698     Address of I2C Device11 on Link4
  UINT8    MipiCamLink4I2cDeviceType[12];           ///< Offset 700     Type of I2C Device0 on Link4
                                                    ///< Offset 701     Type of I2C Device1 on Link4
                                                    ///< Offset 702     Type of I2C Device2 on Link4
                                                    ///< Offset 703     Type of I2C Device3 on Link4
                                                    ///< Offset 704     Type of I2C Device4 on Link4
                                                    ///< Offset 705     Type of I2C Device5 on Link4
                                                    ///< Offset 706     Type of I2C Device6 on Link4
                                                    ///< Offset 707     Type of I2C Device7 on Link4
                                                    ///< Offset 708     Type of I2C Device8 on Link4
                                                    ///< Offset 709     Type of I2C Device9 on Link4
                                                    ///< Offset 710     Type of I2C Device10 on Link4
                                                    ///< Offset 711     Type of I2C Device11 on Link4
  UINT8    MipiCamLink4DD_Version;                  ///< Offset 712     Version of SSDB structure
  UINT8    MipiCamLink4DD_CrdVersion;               ///< Offset 713     Version of CRD
  UINT8    MipiCamLink4DD_LinkUsed;                 ///< Offset 714     CSI2 Link used
  UINT8    MipiCamLink4DD_LaneUsed;                 ///< Offset 715     MIPI-CSI2 Data Lane
  UINT8    MipiCamLink4DD_EepromType;               ///< Offset 716     EEPROM Type
  UINT8    MipiCamLink4DD_VcmType;                  ///< Offset 717     VCM Type
  UINT8    MipiCamLink4DD_FlashSupport;             ///< Offset 718     Flash Support
  UINT8    MipiCamLink4DD_PrivacyLed;               ///< Offset 719     Privacy LED
  UINT8    MipiCamLink4DD_Degree;                   ///< Offset 720     Degree
  UINT32   MipiCamLink4DD_Mclk;                     ///< Offset 721     MCLK
  UINT8    MipiCamLink4DD_ControlLogic;             ///< Offset 725     Control Logic
  UINT8    MipiCamLink4DD_PmicPosition;             ///< Offset 726     PMIC Position
  UINT8    MipiCamLink4DD_VoltageRail;              ///< Offset 727     Voltage Rail
  UINT8    MipiCamLink4DD_PhyConfiguration;         ///< Offset 728     Phy Configuratioin
  UINT8    MipiCamLink4DD_LaneConfiguration;        ///< Offset 729     Lane Configuratioin
  UINT8    MipiCamLink4_FlashDriverSelection;       ///< Offset 730     Flash Driver Selection
  UINT8    MipiCamLink4DD_FlashID;                  ///< Offset 731     Flash ID for Link4
  // Mipi Cam Link5 options
  UINT8    MipiCamLink5SensorModel;                 ///< Offset 732     Sensor Model
  UINT8    MipiCamLink5UserHid[9];                  ///< Offset 733     User defined HID ASCII character 0
                                                    ///< Offset 741     User defined HID ASCII character 8
  UINT8    MipiCamLink5Pld;                         ///< Offset 742     Camera Position
  UINT8    MipiCamLink5ModuleName[16];              ///< Offset 743     Camera Module Name ASCII character 0
                                                    ///< Offset 758     Camera Module Name ASCII character 15
  UINT8    MipiCamLink5I2cDevicesEnabled;           ///< Offset 759     Number of I2C devices
  UINT8    MipiCamLink5I2cBus;                      ///< Offset 760     I2C Serial Bus number
  UINT16   MipiCamLink5I2cAddrDev[12];              ///< Offset 761     Address of I2C Device0 on Link5
                                                    ///< Offset 763     Address of I2C Device1 on Link5
                                                    ///< Offset 765     Address of I2C Device2 on Link5
                                                    ///< Offset 767     Address of I2C Device3 on Link5
                                                    ///< Offset 769     Address of I2C Device4 on Link5
                                                    ///< Offset 771     Address of I2C Device5 on Link5
                                                    ///< Offset 773     Address of I2C Device6 on Link5
                                                    ///< Offset 775     Address of I2C Device7 on Link5
                                                    ///< Offset 777     Address of I2C Device8 on Link5
                                                    ///< Offset 779     Address of I2C Device9 on Link5
                                                    ///< Offset 781     Address of I2C Device10 on Link5
                                                    ///< Offset 783     Address of I2C Device11 on Link5
  UINT8    MipiCamLink5I2cDeviceType[12];           ///< Offset 785     Type of I2C Device0 on Link5
                                                    ///< Offset 786     Type of I2C Device1 on Link5
                                                    ///< Offset 787     Type of I2C Device2 on Link5
                                                    ///< Offset 788     Type of I2C Device3 on Link5
                                                    ///< Offset 789     Type of I2C Device4 on Link5
                                                    ///< Offset 790     Type of I2C Device5 on Link5
                                                    ///< Offset 791     Type of I2C Device6 on Link5
                                                    ///< Offset 792     Type of I2C Device7 on Link5
                                                    ///< Offset 793     Type of I2C Device8 on Link5
                                                    ///< Offset 794     Type of I2C Device9 on Link5
                                                    ///< Offset 795     Type of I2C Device10 on Link5
                                                    ///< Offset 796     Type of I2C Device11 on Link5
  UINT8    MipiCamLink5DD_Version;                  ///< Offset 797     Version of SSDB structure
  UINT8    MipiCamLink5DD_CrdVersion;               ///< Offset 798     Version of CRD
  UINT8    MipiCamLink5DD_LinkUsed;                 ///< Offset 799     CSI2 Link used
  UINT8    MipiCamLink5DD_LaneUsed;                 ///< Offset 800     MIPI-CSI2 Data Lane
  UINT8    MipiCamLink5DD_EepromType;               ///< Offset 801     EEPROM Type
  UINT8    MipiCamLink5DD_VcmType;                  ///< Offset 802     VCM Type
  UINT8    MipiCamLink5DD_FlashSupport;             ///< Offset 803     Flash Support
  UINT8    MipiCamLink5DD_PrivacyLed;               ///< Offset 804     Privacy LED
  UINT8    MipiCamLink5DD_Degree;                   ///< Offset 805     Degree
  UINT32   MipiCamLink5DD_Mclk;                     ///< Offset 806     MCLK
  UINT8    MipiCamLink5DD_ControlLogic;             ///< Offset 810     Control Logic
  UINT8    MipiCamLink5DD_PmicPosition;             ///< Offset 811     PMIC Position
  UINT8    MipiCamLink5DD_VoltageRail;              ///< Offset 812     Voltage Rail
  UINT8    MipiCamLink5DD_PhyConfiguration;         ///< Offset 813     Phy Configuratioin
  UINT8    MipiCamLink5DD_LaneConfiguration;        ///< Offset 814     Lane Configuratioin
  UINT8    MipiCamLink5_FlashDriverSelection;       ///< Offset 815     Flash Driver Selection
  UINT8    MipiCamLink5DD_FlashID;                  ///< Offset 816     Flash ID for Link5
  UINT8    MipiCamFlash0Model;                      ///< Offset 817     Flash Driver Model
  UINT8    MipiCamFlash0UserHid[9];                 ///< Offset 818     User defined HID ASCII character 0
                                                    ///< Offset 826     User defined HID ASCII character 8
  UINT8    MipiCamFlash0Mode;                       ///< Offset 827     Flash Mode Selection
  UINT8    MipiCamFlash0ModuleName[16];             ///< Offset 828     Flash Module Name ASCII character 0
                                                    ///< Offset 843     Flash Module Name ASCII character 15
  UINT8    MipiCamFlash0I2cBus;                     ///< Offset 844     I2C Bus Number
  UINT16   MipiCamFlash0I2cAddrDev;                 ///< Offset 845     I2C Target Device Address
  UINT8    MipiCamFlash0GpioGroupPadNumber;         ///< Offset 847     GPIO Group Pad Number
  UINT16   MipiCamFlash0GpioGroupNumber;            ///< Offset 848     GPIO Group Number
  UINT8    MipiCamFlash0GpioActiveValue;            ///< Offset 850     GPIO Active Value
  UINT8    MipiCamFlash0GpioInitialValue;           ///< Offset 851     GPIO Initial Value
  UINT8    MipiCamFlash0OperatingMode;              ///< Offset 852     Flash Driver Operating Mode
  UINT8    MipiCamFlash1Model;                      ///< Offset 853     Flash Driver Model
  UINT8    MipiCamFlash1UserHid[9];                 ///< Offset 854     User defined HID ASCII character 0
                                                    ///< Offset 862     User defined HID ASCII character 8
  UINT8    MipiCamFlash1Mode;                       ///< Offset 863     Flash Mode Selection
  UINT8    MipiCamFlash1ModuleName[16];             ///< Offset 864     Flash Module Name ASCII character 0
                                                    ///< Offset 879     Flash Module Name ASCII character 15
  UINT8    MipiCamFlash1I2cBus;                     ///< Offset 880     I2C Bus Number
  UINT16   MipiCamFlash1I2cAddrDev;                 ///< Offset 881     I2C Target Device Address
  UINT8    MipiCamFlash1GpioGroupPadNumber;         ///< Offset 883     GPIO Group Pad Number
  UINT16   MipiCamFlash1GpioGroupNumber;            ///< Offset 884     GPIO Group Number
  UINT8    MipiCamFlash1GpioActiveValue;            ///< Offset 886     GPIO Active Value
  UINT8    MipiCamFlash1GpioInitialValue;           ///< Offset 887     GPIO Initial Value
  UINT8    MipiCamFlash1OperatingMode;              ///< Offset 888     Flash Driver Operating Mode
  UINT8    MipiCamFlash2Model;                      ///< Offset 889     Flash Driver Model
  UINT8    MipiCamFlash2UserHid[9];                 ///< Offset 890     User defined HID ASCII character 0
                                                    ///< Offset 898     User defined HID ASCII character 8
  UINT8    MipiCamFlash2Mode;                       ///< Offset 899     Flash Mode Selection
  UINT8    MipiCamFlash2ModuleName[16];             ///< Offset 900     Flash Module Name ASCII character 0
                                                    ///< Offset 915     Flash Module Name ASCII character 15
  UINT8    MipiCamFlash2I2cBus;                     ///< Offset 916     I2C Bus Number
  UINT16   MipiCamFlash2I2cAddrDev;                 ///< Offset 917     I2C Target Device Address
  UINT8    MipiCamFlash2GpioGroupPadNumber;         ///< Offset 919     GPIO Group Pad Number
  UINT16   MipiCamFlash2GpioGroupNumber;            ///< Offset 920     GPIO Group Number
  UINT8    MipiCamFlash2GpioActiveValue;            ///< Offset 922     GPIO Active Value
  UINT8    MipiCamFlash2GpioInitialValue;           ///< Offset 923     GPIO Initial Value
  UINT8    MipiCamFlash2OperatingMode;              ///< Offset 924     Flash Driver Operating Mode
  UINT8    MipiCamFlash3Model;                      ///< Offset 925     Flash Driver Model
  UINT8    MipiCamFlash3UserHid[9];                 ///< Offset 926     User defined HID ASCII character 0
                                                    ///< Offset 934     User defined HID ASCII character 8
  UINT8    MipiCamFlash3Mode;                       ///< Offset 935     Flash Mode Selection
  UINT8    MipiCamFlash3ModuleName[16];             ///< Offset 936     Flash Module Name ASCII character 0
                                                    ///< Offset 951     Flash Module Name ASCII character 15
  UINT8    MipiCamFlash3I2cBus;                     ///< Offset 952     I2C Bus Number
  UINT16   MipiCamFlash3I2cAddrDev;                 ///< Offset 953     I2C Target Device Address
  UINT8    MipiCamFlash3GpioGroupPadNumber;         ///< Offset 955     GPIO Group Pad Number
  UINT16   MipiCamFlash3GpioGroupNumber;            ///< Offset 956     GPIO Group Number
  UINT8    MipiCamFlash3GpioActiveValue;            ///< Offset 958     GPIO Active Value
  UINT8    MipiCamFlash3GpioInitialValue;           ///< Offset 959     GPIO Initial Value
  UINT8    MipiCamFlash3OperatingMode;              ///< Offset 960     Flash Driver Operating Mode
  UINT8    MipiCamFlash4Model;                      ///< Offset 961     Flash Driver Model
  UINT8    MipiCamFlash4UserHid[9];                 ///< Offset 962     User defined HID ASCII character 0
                                                    ///< Offset 970     User defined HID ASCII character 8
  UINT8    MipiCamFlash4Mode;                       ///< Offset 971     Flash Mode Selection
  UINT8    MipiCamFlash4ModuleName[16];             ///< Offset 972     Flash Module Name ASCII character 0
                                                    ///< Offset 987     Flash Module Name ASCII character 15
  UINT8    MipiCamFlash4I2cBus;                     ///< Offset 988     I2C Bus Number
  UINT16   MipiCamFlash4I2cAddrDev;                 ///< Offset 989     I2C Target Device Address
  UINT8    MipiCamFlash4GpioGroupPadNumber;         ///< Offset 991     GPIO Group Pad Number
  UINT16   MipiCamFlash4GpioGroupNumber;            ///< Offset 992     GPIO Group Number
  UINT8    MipiCamFlash4GpioActiveValue;            ///< Offset 994     GPIO Active Value
  UINT8    MipiCamFlash4GpioInitialValue;           ///< Offset 995     GPIO Initial Value
  UINT8    MipiCamFlash4OperatingMode;              ///< Offset 996     Flash Driver Operating Mode
  UINT8    MipiCamFlash5Model;                      ///< Offset 997     Flash Driver Model
  UINT8    MipiCamFlash5UserHid[9];                 ///< Offset 998     User defined HID ASCII character 0
                                                    ///< Offset 1006    User defined HID ASCII character 8
  UINT8    MipiCamFlash5Mode;                       ///< Offset 1007    Flash Mode Selection
  UINT8    MipiCamFlash5ModuleName[16];             ///< Offset 1008    Flash Module Name ASCII character 0
                                                    ///< Offset 1023    Flash Module Name ASCII character 15
  UINT8    MipiCamFlash5I2cBus;                     ///< Offset 1024    I2C Bus Number
  UINT16   MipiCamFlash5I2cAddrDev;                 ///< Offset 1025    I2C Target Device Address
  UINT8    MipiCamFlash5GpioGroupPadNumber;         ///< Offset 1027    GPIO Group Pad Number
  UINT16   MipiCamFlash5GpioGroupNumber;            ///< Offset 1028    GPIO Group Number
  UINT8    MipiCamFlash5GpioActiveValue;            ///< Offset 1030    GPIO Active Value
  UINT8    MipiCamFlash5GpioInitialValue;           ///< Offset 1031    GPIO Initial Value
  UINT8    MipiCamFlash5OperatingMode;              ///< Offset 1032    Flash Driver Operating Mode
  UINT16   MipiCamCtrlLogic0_GpioComNumber[6];      ///< Offset 1033    GPIO com number
  UINT16   MipiCamCtrlLogic1_GpioComNumber[6];      ///< Offset 1045    GPIO com number
  UINT16   MipiCamCtrlLogic2_GpioComNumber[6];      ///< Offset 1057    GPIO com number
  UINT16   MipiCamCtrlLogic3_GpioComNumber[6];      ///< Offset 1069    GPIO com number
  UINT16   MipiCamCtrlLogic4_GpioComNumber[6];      ///< Offset 1081    GPIO com number
  UINT16   MipiCamCtrlLogic5_GpioComNumber[6];      ///< Offset 1093    GPIO com number
  UINT16   MipiCamFlash0GpioComNumber;              ///< Offset 1105    GPIO Com Number
  UINT16   MipiCamFlash1GpioComNumber;              ///< Offset 1107    GPIO Com Number
  UINT16   MipiCamFlash2GpioComNumber;              ///< Offset 1109    GPIO Com Number
  UINT16   MipiCamFlash3GpioComNumber;              ///< Offset 1111    GPIO Com Number
  UINT16   MipiCamFlash4GpioComNumber;              ///< Offset 1113    GPIO Com Number
  UINT16   MipiCamFlash5GpioComNumber;              ///< Offset 1115    GPIO Com Number
  UINT8    MipiCamFlash0GpioSupport;                ///< Offset 1117    Flash 0 GPIO Support
  UINT8    MipiCamFlash1GpioSupport;                ///< Offset 1118    Flash 1 GPIO Support
  UINT8    MipiCamFlash2GpioSupport;                ///< Offset 1119    Flash 2 GPIO Support
  UINT8    MipiCamFlash3GpioSupport;                ///< Offset 1120    Flash 3 GPIO Support
  UINT8    MipiCamFlash4GpioSupport;                ///< Offset 1121    Flash 4 GPIO Support
  UINT8    MipiCamFlash5GpioSupport;                ///< Offset 1122    Flash 5 GPIO Support
  UINT8    MipiCamPlatformId;                       ///< Offset 1123    Platform ID
  UINT8    MipiCamEmulationConfig;                  ///< Offset 1124    Emulation Config Status
  UINT8    MipiCamChipsetId;                        ///< Offset 1125    ChipsetId
  //Audio Custom HID Link0
  UINT8    AudioLink0UserHid[9];                    ///< Offset 1126    User defined HID ASCII character 0
                                                    ///< Offset 1134    User defined HID ASCII character 8
  //Audio Custom HID Link1
  UINT8    AudioLink1UserHid[9];                    ///< Offset 1135    User defined HID ASCII character 0
                                                    ///< Offset 1143    User defined HID ASCII character 8
  // HD Audio
  UINT8    I2SE;                                    ///< Offset 1144    HD Audio I2S Enable
  UINT8    PcdMipiCamSensor;                        ///< Offset 1145    Mipi Camera Sensor
} MIPICAM_NVS_AREA;

#pragma pack(pop)
#endif
