/** @file
  This file includes all code needed to load the Green MRC payload.

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2023 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

 @par Specification
**/
//
// Include files
//
#include "MrcUcPayloadData.h"
#include "CMrcTypes.h"

//
// This data is automatically harvested from the Green MRC binary.
// Each section is a section from the ELF generated by XCC.
// The offset is the position of the section in the file.
// The address is the destination address in Xtensa SRAM.
// The size is the size of the section in bytes.
//

MRC_PAYLOAD_SECTION gUcPayloadSections[MRC_FAST_PAYLOAD_END] = {
#ifndef MDEPKG_NDEBUG
  {0x0, 0x1ffa0000, 0x00000004},
  {0x118, 0x1ffc0000, 0x00000100},
  {0x218, 0x1ffc0310, 0x00000064},
  {0x27c, 0x1ffc0600, 0x0000016c},
  {0x3e8, 0x1ffc077c, 0x0000000c},
  {0x3f4, 0x1ffc079c, 0x00000010},
  {0x404, 0x1ffc07bc, 0x0000000c},
  {0x410, 0x1ffc07dc, 0x00000008},
  {0x418, 0x1ffc07f8, 0x0001a4d4},
  {0x1a8ec, 0x1ffdaccc, 0x00000110},
  {0x1a9fc, 0x1ffe0000, 0x0000565c},
  {0x20058, 0x20002000, 0x00000100},
  {0x20158, 0x20002100, 0x00019c40},
  {0x39d98, 0x2001bd40, 0x00045cf4},
  {0x7fa8c, 0x20061a34, 0x0000000c},
  {0x7fa98, 0x20061a40, 0x00000298},
  {0x7fd38, 0x20061ce0, 0x00001b0c},
#else // Release
  {0x0, 0x1ffa0000, 0x00000004},
  {0x118, 0x1ffc0000, 0x00000100},
  {0x218, 0x1ffc0310, 0x00000064},
  {0x27c, 0x1ffc0600, 0x0000016c},
  {0x3e8, 0x1ffc077c, 0x0000000c},
  {0x3f4, 0x1ffc079c, 0x00000010},
  {0x404, 0x1ffc07bc, 0x0000000c},
  {0x410, 0x1ffc07dc, 0x00000008},
  {0x418, 0x1ffc07f8, 0x00016368},
  {0x16780, 0x1ffd6b60, 0x00000110},
  {0x16890, 0x1ffe0000, 0x00004f2c},
  {0x1b7bc, 0x20002000, 0x00000100},
  {0x1b8bc, 0x20002100, 0x00008cc4},
  {0x24580, 0x2000adc4, 0x0003a40c},
  {0x5e98c, 0x200451d0, 0x0000000c},
  {0x5e99c, 0x200451e0, 0x00000298},
  {0x5ec3c, 0x20045480, 0x0000060c},
#endif
};

UINT32 gUcMrcDataAddress = 0x20066680;
UINT32 gUcCommBufferAddress = 0x1ffb7eec;
UINT32 gUcExtInputsAddress = 0x20081b80;
