#ifndef __MrcRegisterStructPtl1Dxxx_h__
#define __MrcRegisterStructPtl1Dxxx_h__
/** @file
  This file was automatically generated. Modify at your own risk.
  Note that no error checking is done in these functions so ensure that the correct values are passed.

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2023 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/

#pragma pack(push, 1)

typedef MC0_IBECC_ACTIVATE_STRUCT MC1_IBECC_ACTIVATE_STRUCT;

typedef MC0_IBECC_STATUS_STRUCT MC1_IBECC_STATUS_STRUCT;

typedef MC0_IBECC_IOSF_SB_EP_CTRL_STRUCT MC1_IBECC_IOSF_SB_EP_CTRL_STRUCT;

typedef MC0_IBECC_PROTECT_ADDR_RANGE_0_STRUCT MC1_IBECC_PROTECT_ADDR_RANGE_0_STRUCT;

typedef MC0_IBECC_PROTECT_ADDR_RANGE_0_STRUCT MC1_IBECC_PROTECT_ADDR_RANGE_1_STRUCT;

typedef MC0_IBECC_PROTECT_ADDR_RANGE_0_STRUCT MC1_IBECC_PROTECT_ADDR_RANGE_2_STRUCT;

typedef MC0_IBECC_PROTECT_ADDR_RANGE_0_STRUCT MC1_IBECC_PROTECT_ADDR_RANGE_3_STRUCT;

typedef MC0_IBECC_PROTECT_ADDR_RANGE_0_STRUCT MC1_IBECC_PROTECT_ADDR_RANGE_4_STRUCT;

typedef MC0_IBECC_PROTECT_ADDR_RANGE_0_STRUCT MC1_IBECC_PROTECT_ADDR_RANGE_5_STRUCT;

typedef MC0_IBECC_PROTECT_ADDR_RANGE_0_STRUCT MC1_IBECC_PROTECT_ADDR_RANGE_6_STRUCT;

typedef MC0_IBECC_PROTECT_ADDR_RANGE_0_STRUCT MC1_IBECC_PROTECT_ADDR_RANGE_7_STRUCT;

typedef MC0_IBECC_DEFAULT_PG_CP_STRUCT MC1_IBECC_DEFAULT_PG_CP_STRUCT;

typedef MC0_IBECC_DEFAULT_PG_RAC_STRUCT MC1_IBECC_DEFAULT_PG_RAC_STRUCT;

typedef MC0_IBECC_DEFAULT_PG_WAC_STRUCT MC1_IBECC_DEFAULT_PG_WAC_STRUCT;

typedef MC0_IBECC_DEFAULT_PG_CP_STRUCT MC1_IBECC_DEBUG_PG_CP_STRUCT;

typedef MC0_IBECC_DEFAULT_PG_RAC_STRUCT MC1_IBECC_DEBUG_PG_RAC_STRUCT;

typedef MC0_IBECC_DEBUG_PG_WAC_STRUCT MC1_IBECC_DEBUG_PG_WAC_STRUCT;

typedef MC0_IBECC_DEFAULT_PG_CP_STRUCT MC1_IBECC_OS_PG_CP_STRUCT;

typedef MC0_IBECC_DEFAULT_PG_RAC_STRUCT MC1_IBECC_OS_PG_RAC_STRUCT;

typedef MC0_IBECC_OS_PG_WAC_STRUCT MC1_IBECC_OS_PG_WAC_STRUCT;

typedef MC0_IBECC_CLK_GATE_EN_0_STRUCT MC1_IBECC_CLK_GATE_EN_0_STRUCT;

typedef MC0_IBECC_P0_REQUEST_CREDIT_CONFIG_VC0_STRUCT MC1_IBECC_P0_REQUEST_CREDIT_CONFIG_VC0_STRUCT;

typedef MC0_IBECC_P0_REQUEST_CREDIT_CONFIG_VC1_STRUCT MC1_IBECC_P0_REQUEST_CREDIT_CONFIG_VC1_STRUCT;

typedef MC0_IBECC_P0_REQUEST_SHARED_CREDIT_CONFIG_STRUCT MC1_IBECC_P0_REQUEST_SHARED_CREDIT_CONFIG_STRUCT;

typedef MC0_IBECC_CFI_BLOCK_STRUCT MC1_IBECC_CFI_BLOCK_STRUCT;

typedef MC0_IBECC_MBIST_POST_CTRL_WDB_STRUCT MC1_IBECC_MBIST_POST_CTRL_WDB_STRUCT;

typedef MC0_IBECC_MBIST_POST_CTRL_WDB_STRUCT MC1_IBECC_MBIST_POST_CTRL_RDB_STRUCT;

typedef MC0_IBECC_PARITY_CONTROL_STRUCT MC1_IBECC_PARITY_CONTROL_STRUCT;

typedef MC0_IBECC_P1_RESPONSE_CREDIT_CONFIG_VC0_STRUCT MC1_IBECC_P1_RESPONSE_CREDIT_CONFIG_VC0_STRUCT;

typedef MC0_IBECC_P1_RESPONSE_CREDIT_CONFIG_VC0_STRUCT MC1_IBECC_P1_RESPONSE_CREDIT_CONFIG_VC1_STRUCT;

typedef MC0_IBECC_CFI_PORT_CONTROL_STRUCT MC1_IBECC_CFI_PORT_CONTROL_STRUCT;

typedef MC0_IBECC_QCLK_GLB_DRV_CLKGATE_CONTROL_STRUCT MC1_IBECC_QCLK_GLB_DRV_CLKGATE_CONTROL_STRUCT;

typedef MC0_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT MC1_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT;

typedef MC0_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT MC1_IBECC_ECC_VC1_RD_REQCOUNT_STRUCT;

typedef MC0_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT MC1_IBECC_ECC_VC0_WR_REQCOUNT_STRUCT;

typedef MC0_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT MC1_IBECC_ECC_VC1_WR_REQCOUNT_STRUCT;

typedef MC0_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT MC1_IBECC_NOECC_VC0_RD_REQCOUNT_STRUCT;

typedef MC0_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT MC1_IBECC_NOECC_VC1_RD_REQCOUNT_STRUCT;

typedef MC0_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT MC1_IBECC_NOECC_VC0_WR_REQCOUNT_STRUCT;

typedef MC0_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT MC1_IBECC_NOECC_VC1_WR_REQCOUNT_STRUCT;

typedef MC0_IBECC_REQUEST_ARB_CONFIG_STRUCT MC1_IBECC_REQUEST_ARB_CONFIG_STRUCT;

typedef MC0_IBECC_REQUEST_ARB_CONFIG_STRUCT MC1_IBECC_RESPONSE_ARB_CONFIG_STRUCT;

typedef MC0_IBECC_ECC_ERROR_LOG_STRUCT MC1_IBECC_ECC_ERROR_LOG_STRUCT;

typedef MC0_IBECC_PARITY_ERR_LOG_STRUCT MC1_IBECC_PARITY_ERR_LOG_STRUCT;

typedef MC0_IBECC_ECC_INJ_ADDR_MASK_STRUCT MC1_IBECC_ECC_INJ_ADDR_MASK_STRUCT;

typedef MC0_IBECC_ECC_INJ_ADDR_MASK_STRUCT MC1_IBECC_ECC_INJ_ADDR_BASE_STRUCT;

typedef MC0_IBECC_PARITY_ERR_INJ_STRUCT MC1_IBECC_PARITY_ERR_INJ_STRUCT;

typedef MC0_IBECC_CONTROL_STRUCT MC1_IBECC_CONTROL_STRUCT;

typedef MC0_IBECC_ECC_INJ_CONTROL_STRUCT MC1_IBECC_ECC_INJ_CONTROL_STRUCT;

typedef MC0_IBECC_MBIST_POST_CTRL_WDB_STRUCT MC1_IBECC_MBIST_POST_CTRL_RSB_STRUCT;

typedef MC0_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT MC1_IBECC_ECC_VC0_SYND_RD_REQCOUNT_STRUCT;

typedef MC0_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT MC1_IBECC_ECC_VC1_SYND_RD_REQCOUNT_STRUCT;

typedef MC0_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT MC1_IBECC_ECC_VC0_SYND_WR_REQCOUNT_STRUCT;

typedef MC0_IBECC_ECC_VC0_RD_REQCOUNT_STRUCT MC1_IBECC_ECC_VC1_SYND_WR_REQCOUNT_STRUCT;

typedef MC0_IBECC_RD_TRKR_VC_MAX_ENTRY_THRESHOLD_STRUCT MC1_IBECC_RD_TRKR_VC_MAX_ENTRY_THRESHOLD_STRUCT;

typedef MC0_IBECC_BLOCK_BIDS_STRUCT MC1_IBECC_BLOCK_BIDS_STRUCT;

typedef MC0_IBECC_ECC_STORAGE_ADDR_RANGE_0_STRUCT MC1_IBECC_ECC_STORAGE_ADDR_RANGE_0_STRUCT;

typedef MC0_IBECC_ECC_STORAGE_ADDR_RANGE_0_STRUCT MC1_IBECC_ECC_STORAGE_ADDR_RANGE_1_STRUCT;

typedef MC0_IBECC_ECC_STORAGE_ADDR_RANGE_0_STRUCT MC1_IBECC_ECC_STORAGE_ADDR_RANGE_2_STRUCT;

typedef MC0_IBECC_ECC_STORAGE_ADDR_RANGE_0_STRUCT MC1_IBECC_ECC_STORAGE_ADDR_RANGE_3_STRUCT;

typedef MC0_IBECC_ECC_STORAGE_ADDR_RANGE_0_STRUCT MC1_IBECC_ECC_STORAGE_ADDR_RANGE_4_STRUCT;

typedef MC0_IBECC_ECC_STORAGE_ADDR_RANGE_0_STRUCT MC1_IBECC_ECC_STORAGE_ADDR_RANGE_5_STRUCT;

typedef MC0_IBECC_ECC_STORAGE_ADDR_RANGE_0_STRUCT MC1_IBECC_ECC_STORAGE_ADDR_RANGE_6_STRUCT;

typedef MC0_IBECC_ECC_STORAGE_ADDR_RANGE_0_STRUCT MC1_IBECC_ECC_STORAGE_ADDR_RANGE_7_STRUCT;

typedef MC0_IBECC_MDST_TRIM_FUSE_STRUCT MC1_IBECC_MDST_TRIM_FUSE_STRUCT;

typedef MC0_IBECC_ECC_ERR_COUNT_STRUCT MC1_IBECC_ECC_ERR_COUNT_STRUCT;

typedef MC0_IBECC_DEFAULT_PG_CP_STRUCT MC1_IBECC_RESTRICTED_PG_CP_STRUCT;

typedef MC0_IBECC_DEFAULT_PG_RAC_STRUCT MC1_IBECC_RESTRICTED_PG_RAC_STRUCT;

typedef MC0_IBECC_DEFAULT_PG_CP_STRUCT MC1_IBECC_RESTRICTED_PG_WAC_STRUCT;

typedef MC0_IBECC_MEMORY_INIT_CONTROL_STRUCT MC1_IBECC_MEMORY_INIT_CONTROL_STRUCT;

typedef MC0_IBECC_P1_DATA_TX_CNT_STRUCT MC1_IBECC_P1_DATA_TX_CNT_STRUCT;

typedef MC0_IBECC_P1_DATA_RX_CNT_STRUCT MC1_IBECC_P1_DATA_RX_CNT_STRUCT;

typedef MC0_IBECC_P1_DATA_TX_CNT_STRUCT MC1_IBECC_P0_DATA_TX_CNT_STRUCT;

typedef MC0_IBECC_P1_DATA_RX_CNT_STRUCT MC1_IBECC_P0_DATA_RX_CNT_STRUCT;

typedef MC0_IBECC_ADDR_HASH_STRUCT MC1_IBECC_ADDR_HASH_STRUCT;

typedef MC0_IBECC_IP_VERSION_0_0_0_IBECCHBAR_STRUCT MC1_IBECC_IP_VERSION_0_0_0_IBECCHBAR_STRUCT;

typedef MC0_IBECC_CFI_HOST_STRUCT MC1_IBECC_CFI_HOST_STRUCT;

typedef MC0_MAD_INTER_CHANNEL_STRUCT MC1_MAD_INTER_CHANNEL_STRUCT;

typedef MC0_MAD_INTRA_CHANNEL_0_STRUCT MC1_MAD_INTRA_CHANNEL_0_STRUCT;

typedef MC0_MAD_INTRA_CHANNEL_0_STRUCT MC1_MAD_INTRA_CHANNEL_1_STRUCT;

typedef MC0_MAD_DRAM_HASH_0_STRUCT MC1_MAD_DRAM_HASH_0_STRUCT;

typedef MC0_MAD_DRAM_HASH_0_STRUCT MC1_MAD_DRAM_HASH_1_STRUCT;

typedef MC0_MCDECS_MISC_STRUCT MC1_MCDECS_MISC_STRUCT;

typedef MC0_MCDECS_CBIT_STRUCT MC1_MCDECS_CBIT_STRUCT;

typedef MC0_MAD_CHANNEL_HASH_STRUCT MC1_MAD_CHANNEL_HASH_STRUCT;

typedef MC0_MAD_SUB_CHANNEL_HASH_STRUCT MC1_MAD_SUB_CHANNEL_HASH_STRUCT;

typedef MC0_PWM_PROGRAMMABLE_REQCOUNT_CONFIG_STRUCT MC1_PWM_PROGRAMMABLE_REQCOUNT_CONFIG_STRUCT;

typedef MC0_MC_INIT_STATE_G_STRUCT MC1_MC_INIT_STATE_G_STRUCT;

typedef MC0_MC_IP_VERSION_STRUCT MC1_MC_IP_VERSION_STRUCT;

typedef MC0_MC_RTL_VERSION_STRUCT MC1_MC_RTL_VERSION_STRUCT;

typedef MC0_PM_OPP_SREF_IDLE_TIMER_STRUCT MC1_PM_OPP_SREF_IDLE_TIMER_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_TOTAL_REQCOUNT_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_PROGRAMMABLE_REQCOUNT_0_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_PROGRAMMABLE_REQCOUNT_1_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_RDCAS_COUNT_STRUCT;

typedef MC0_PM_OPP_SREF_ENABLE_STRUCT MC1_PM_OPP_SREF_ENABLE_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_READ_OCCUPANCY_COUNT_STRUCT;

typedef MC0_STALL_DRAIN_STRUCT MC1_STALL_DRAIN_STRUCT;

typedef MC0_IPC_MC_ARB_STRUCT MC1_IPC_MC_ARB_STRUCT;

typedef MC0_IPC_MC_ARB_STRUCT MC1_IPC_MC_DEC_ARB_STRUCT;

typedef MC0_QUEUE_CREDIT_C_STRUCT MC1_QUEUE_CREDIT_C_STRUCT;

typedef MC0_ECC_INJ_ADDR_COMPARE_STRUCT MC1_ECC_INJ_ADDR_COMPARE_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_WRCAS_COUNT_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_COMMAND_COUNT_STRUCT;

typedef MC0_TOLUD_STRUCT MC1_TOLUD_STRUCT;

typedef MC0_PWM_TOTAL_REQCOUNT_STRUCT MC1_PWM_ACT_COUNT_STRUCT;

typedef MC0_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT MC1_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT;

typedef MC0_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT MC1_GDXC_DDR_SYS_ADD_FILTER_MASK_1_STRUCT;

typedef MC0_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT MC1_GDXC_DDR_SYS_ADD_FILTER_MATCH_0_STRUCT;

typedef MC0_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT MC1_GDXC_DDR_SYS_ADD_FILTER_MATCH_1_STRUCT;

typedef MC0_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT MC1_GDXC_DDR_SYS_ADD_TRIGGER_MASK_STRUCT;

typedef MC0_GDXC_DDR_SYS_ADD_FILTER_MASK_0_STRUCT MC1_GDXC_DDR_SYS_ADD_TRIGGER_MATCH_STRUCT;

typedef MC0_SC_QOS_STRUCT MC1_SC_QOS_STRUCT;

typedef MC0_MCMAINS_GLOBAL_DRIVER_GATE_CFG_STRUCT MC1_MCMAINS_GLOBAL_DRIVER_GATE_CFG_STRUCT;

typedef MC0_PM_CONTROL_STRUCT MC1_PM_CONTROL_STRUCT;

typedef MC0_CLOCK_SPINE_GATE_CFG_STRUCT MC1_CLOCK_SPINE_GATE_CFG_STRUCT;

typedef MC0_PWM_COUNTERS_DURATION_STRUCT MC1_PWM_COUNTERS_DURATION_STRUCT;

typedef MC0_MCDECS_SECOND_CBIT_STRUCT MC1_MCDECS_SECOND_CBIT_STRUCT;

typedef MC0_ECC_INJ_ADDR_MASK_STRUCT MC1_ECC_INJ_ADDR_MASK_STRUCT;

typedef MC0_SC_QOS2_STRUCT MC1_SC_QOS2_STRUCT;

typedef MC0_SC_QOS3_STRUCT MC1_SC_QOS3_STRUCT;

typedef MC0_NORMALMODE_CFG_STRUCT MC1_NORMALMODE_CFG_STRUCT;

typedef MC0_MC_CPGC_CONTROL_STRUCT MC1_MC_CPGC_CONTROL_STRUCT;

typedef MC0_MC_CPGC_CONTROL_UARCH_STRUCT MC1_MC_CPGC_CONTROL_UARCH_STRUCT;

typedef MC0_PARITYERRLOG_STRUCT MC1_PARITYERRLOG_STRUCT;

typedef MC0_PARITY_ERR_INJ_STRUCT MC1_PARITY_ERR_INJ_STRUCT;

typedef MC0_PARITY_CONTROL_STRUCT MC1_PARITY_CONTROL_STRUCT;

typedef MC0_MAD_MC_HASH_STRUCT MC1_MAD_MC_HASH_STRUCT;

typedef MC0_PMON_UNIT_CONTROL_STRUCT MC1_PMON_UNIT_CONTROL_STRUCT;

typedef MC0_PMON_UNIT_STATUS_STRUCT MC1_PMON_UNIT_STATUS_STRUCT;

typedef MC0_PMON_COUNTER_CONTROL_0_STRUCT MC1_PMON_COUNTER_CONTROL_0_STRUCT;

typedef MC0_PMON_COUNTER_CONTROL_0_STRUCT MC1_PMON_COUNTER_CONTROL_1_STRUCT;

typedef MC0_PMON_COUNTER_CONTROL_0_STRUCT MC1_PMON_COUNTER_CONTROL_2_STRUCT;

typedef MC0_PMON_COUNTER_CONTROL_0_STRUCT MC1_PMON_COUNTER_CONTROL_3_STRUCT;

typedef MC0_PMON_COUNTER_CONTROL_0_STRUCT MC1_PMON_COUNTER_CONTROL_4_STRUCT;

typedef MC0_PMON_COUNTER_DATA_0_STRUCT MC1_PMON_COUNTER_DATA_0_STRUCT;

typedef MC0_PMON_COUNTER_DATA_0_STRUCT MC1_PMON_COUNTER_DATA_1_STRUCT;

typedef MC0_PMON_COUNTER_DATA_0_STRUCT MC1_PMON_COUNTER_DATA_2_STRUCT;

typedef MC0_PMON_COUNTER_DATA_0_STRUCT MC1_PMON_COUNTER_DATA_3_STRUCT;

typedef MC0_PMON_COUNTER_DATA_0_STRUCT MC1_PMON_COUNTER_DATA_4_STRUCT;

typedef MC0_OS_TELEMETRY_CONTROL_STRUCT MC1_OS_TELEMETRY_CONTROL_STRUCT;

typedef MC0_PM_OPP_SR_POLICY_0_STRUCT MC1_PM_OPP_SR_POLICY_0_STRUCT;

typedef MC0_PM_OPP_SR_POLICY_0_STRUCT MC1_PM_OPP_SR_POLICY_1_STRUCT;

typedef MC0_MC_CFI_FABRIC_CONTROL_STRUCT MC1_MC_CFI_FABRIC_CONTROL_STRUCT;

typedef MC0_MC_CFI_CONTROL_STRUCT MC1_MC_CFI_CONTROL_STRUCT;

typedef MC0_PM_REQ_FORCE_DFX_STRUCT MC1_PM_REQ_FORCE_DFX_STRUCT;

typedef MC0_DDRPL_CFG2_DTF_STRUCT MC1_DDRPL_CFG2_DTF_STRUCT;

typedef MC0_SC_QOS_UARCH_STRUCT MC1_SC_QOS_UARCH_STRUCT;

typedef MC0_DDRPL_CFG_DTF_STRUCT MC1_DDRPL_CFG_DTF_STRUCT;

typedef MC0_DDRPL_DEBUG_DTF_STRUCT MC1_DDRPL_DEBUG_DTF_STRUCT;

typedef MC0_DDRPL_VISA_LANES_STRUCT MC1_DDRPL_VISA_LANES_STRUCT;

typedef MC0_DDRPL_VISA_CFG_DTF_STRUCT MC1_DDRPL_VISA_CFG_DTF_STRUCT;

typedef MC0_DDRPL_DRAMADDRESS_FILTER_STRUCT MC1_DDRPL_DRAMADDRESS_FILTER_STRUCT;

typedef MC0_DDRPL_DRAMADDRESS_FILTER2_STRUCT MC1_DDRPL_DRAMADDRESS_FILTER2_STRUCT;

#pragma pack(pop)
#endif
