#ifndef __MrcRegisterPtl1xxx_h__
#define __MrcRegisterPtl1xxx_h__

/**
@file
  This file was automatically generated. Modify at your own risk.
  Note that no error checking is done in these functions so ensure that the correct values are passed.

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2023 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/

#pragma pack(push, 1)


#define DATA5CH0_CR_DDRCRDATACONTROL1_REG                              (0x00001000)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL1_REG

#define DATA5CH0_CR_DDRCRDATACONTROL5_REG                              (0x00001004)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL5_REG

#define DATA5CH0_CR_DDRCRRXEQTAP01_REG                                 (0x00001008)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP01_REG

#define DATA5CH0_CR_DDRCRRXEQTAP_REG                                   (0x0000100C)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP_REG

#define DATA5CH0_CR_DDRCRCMDBUSTRAIN_REG                               (0x00001010)
//Duplicate of DATA0CH0_CR_DDRCRCMDBUSTRAIN_REG

#define DATA5CH0_CR_DDRCRDATATCOCONTROL0_REG                           (0x00001014)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL0_REG

#define DATA5CH0_CR_DDRCRDATATCOCONTROL1_REG                           (0x00001018)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL1_REG

#define DATA5CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG                    (0x0000101C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA5CH0_CR_DDRCRRDRETRAINCONTROLSTATUS_REG                    (0x00001020)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA5CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG                   (0x00001024)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG

#define DATA5CH0_CR_DDRCRWRRETRAINDELTARANK_REG                        (0x00001028)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINDELTARANK_REG

#define DATA5CH0_CR_DDRCRRDRETRAINDELTARANK_REG                        (0x0000102C)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAINDELTARANK_REG

#define DATA5CH0_CR_DATATRAINFEEDBACK_REG                              (0x00001030)
//Duplicate of DATA0CH0_CR_DATATRAINFEEDBACK_REG

#define DATA5CH0_CR_DCCFSMSTATUS_REG                                   (0x00001034)
//Duplicate of DATA0CH0_CR_DCCFSMSTATUS_REG

#define DATA5CH0_CR_DCCLANESTATUS0_REG                                 (0x00001038)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS0_REG

#define DATA5CH0_CR_DCCLANESTATUS1_REG                                 (0x0000103C)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS1_REG

#define DATA5CH0_CR_DCCLANESTATUS2_REG                                 (0x00001040)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS2_REG

#define DATA5CH0_CR_DCCLANESTATUS3_REG                                 (0x00001044)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS3_REG

#define DATA5CH0_CR_DDRCRMARGINMODECONTROL0_REG                        (0x00001048)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODECONTROL0_REG

#define DATA5CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG                       (0x0000104C)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA5CH0_CR_DDRCRMARGINMODEDEBUGLSB0_REG                       (0x00001050)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA5CH0_CR_DDRCRDLLSTATUS_REG                                 (0x00001054)
//Duplicate of DATA0CH0_CR_DDRCRDLLSTATUS_REG

#define DATA5CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG                     (0x00001058)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG

#define DATA5CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG                (0x0000105C)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG

#define DATA5CH0_CR_DDRCRCOMPDQSDELAY_REG                              (0x00001060)
//Duplicate of DATA0CH0_CR_DDRCRCOMPDQSDELAY_REG

#define DATA5CH0_CR_DDRCRADC_REG                                       (0x00001064)
//Duplicate of DATA0CH0_CR_DDRCRADC_REG

#define DATA5CH0_CR_REFPIFSMCONTROL_REG                                (0x00001068)
//Duplicate of DATA0CH0_CR_REFPIFSMCONTROL_REG

#define DATA5CH0_CR_DDRDATADQRANK0LANE8_REG                            (0x0000106C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH0_CR_DDRDATADQRANK1LANE8_REG                            (0x00001070)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH0_CR_DDRCRDATAVREFPERBIT012_REG                         (0x00001074)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT012_REG

#define DATA5CH0_CR_DDRCRDATAVREFPERBIT345_REG                         (0x00001078)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT345_REG

#define DATA5CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG                       (0x0000107C)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG

#define DATA5CH1_CR_DDRDATADQRANK0LANE0_REG                            (0x00001080)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK0LANE1_REG                            (0x00001084)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK0LANE2_REG                            (0x00001088)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK0LANE3_REG                            (0x0000108C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK0LANE4_REG                            (0x00001090)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK0LANE5_REG                            (0x00001094)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK0LANE6_REG                            (0x00001098)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK0LANE7_REG                            (0x0000109C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK1LANE0_REG                            (0x000010A0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK1LANE1_REG                            (0x000010A4)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK1LANE2_REG                            (0x000010A8)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK1LANE3_REG                            (0x000010AC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK1LANE4_REG                            (0x000010B0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK1LANE5_REG                            (0x000010B4)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK1LANE6_REG                            (0x000010B8)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK1LANE7_REG                            (0x000010BC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQSRANK0_REG                                (0x000010C0)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATA5CH1_CR_DDRDATADQSRANK1_REG                                (0x000010C4)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATA5CH1_CR_TXCONTROL0RANK0_REG                                (0x000010C8)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATA5CH1_CR_TXCONTROL0RANK1_REG                                (0x000010CC)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATA5CH1_CR_DDRCRDATAOFFSETTRAIN_REG                           (0x000010D0)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETTRAIN_REG

#define DATA5CH1_CR_DDRCRDATACONTROL2_REG                              (0x000010D4)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL2_REG

#define DATA5CH1_CR_DCCFSMCONTROL_REG                                  (0x000010D8)
//Duplicate of DATA0CH0_CR_DCCFSMCONTROL_REG

#define DATA5CH1_CR_DCCCALCCONTROL_REG                                 (0x000010DC)
//Duplicate of DATA0CH0_CR_DCCCALCCONTROL_REG

#define DATA5CH1_CR_DCCLANETARGET_REG                                  (0x000010E0)
//Duplicate of DATA0CH0_CR_DCCLANETARGET_REG

#define DATA5CH1_CR_DDRCRRANKMUXDELAY_REG                              (0x000010E4)
//Duplicate of DATA0CH0_CR_DDRCRRANKMUXDELAY_REG

#define DATA5CH1_CR_DDRCRDLLCONTROL0_REG                               (0x000010E8)
//Duplicate of DATA0CH0_CR_DDRCRDLLCONTROL0_REG

#define DATA5CH1_CR_DCCPILUT0_REG                                      (0x000010EC)
//Duplicate of DATA0CH0_CR_DCCPILUT0_REG

#define DATA5CH1_CR_REFPICONTROL_REG                                   (0x000010F0)
//Duplicate of DATA0CH0_CR_REFPICONTROL_REG

#define DATA5CH1_CR_SPARE_REG                                          (0x000010F4)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DATA5CH1_CR_DDRCRXTALKBIASCONTROL1_REG                         (0x000010F8)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL1_REG

#define DATA5CH1_CR_DDRCRDQSWCKDLLCONTROL0_REG                         (0x000010FC)
//Duplicate of DATA0CH0_CR_DDRCRDQSWCKDLLCONTROL0_REG

#define DATA5CH1_CR_TERDCCCONTROL0_REG                                 (0x00001100)
//Duplicate of DATA0CH0_CR_TERDCCCONTROL0_REG

#define DATA5CH1_CR_DDRCRXTALKBIASCONTROL2_REG                         (0x00001104)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL2_REG

#define DATA5CH1_CR_DDRCRXTALKBIASCONTROL3_REG                         (0x00001108)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL3_REG

#define DATA5CH1_CR_DDRCRXTALKBIASCONTROL4_REG                         (0x0000110C)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL4_REG

#define DATA5CH1_CR_DDRCRXTALKBIASCONTROL5_REG                         (0x00001110)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL5_REG

#define DATA5CH1_CR_DDRDATADQDCCRANK0LANE0TO4_REG                      (0x00001114)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE0TO4_REG

#define DATA5CH1_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG         (0x00001118)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG

#define DATA5CH1_CR_DDRDATADQDCCRANK1LANE2TO6_REG                      (0x0000111C)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE2TO6_REG

#define DATA5CH1_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG               (0x00001120)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG

#define DATA5CH1_CR_SPARE1_REG                                         (0x00001124)
//Duplicate of DATA0CH0_CR_SPARE1_REG

#define DATA5CH1_CR_VCCCLKCOMPRXOFFSET_REG                             (0x00001134)
//Duplicate of DATA0CH0_CR_VCCCLKCOMPRXOFFSET_REG

#define DATA5CH1_CR_DDRCRWRRETRAININITRANK1_REG                        (0x0000114C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATA5CH1_CR_DDRCRWRRETRAININITRANK0_REG                        (0x00001150)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATA5CH1_CR_DDRCRRDRETRAININITRANK1_REG                        (0x0000115C)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATA5CH1_CR_DDRCRRDRETRAININITRANK0_REG                        (0x00001160)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATA5CH1_CR_DDRCRRXCTLE_REG                                    (0x00001164)
//Duplicate of DATA0CH0_CR_DDRCRRXCTLE_REG

#define DATA5CH1_CR_RXCONTROL0RANK0_REG                                (0x00001168)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATA5CH1_CR_RXCONTROL0RANK1_REG                                (0x0000116C)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATA5CH1_CR_DDRDQREPLICACTLE_REG                               (0x00001170)
//Duplicate of DATA0CH0_CR_DDRDQREPLICACTLE_REG

#define DATA5CH1_CR_DDRCRDATAOFFSETCOMP_REG                            (0x00001178)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETCOMP_REG

#define DATA5CH1_CR_DDRCRDATACONTROL0_REG                              (0x0000117C)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL0_REG

#define DATA5CH1_CR_DDRCRDATACONTROL1_REG                              (0x00001180)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL1_REG

#define DATA5CH1_CR_DDRCRDATACONTROL5_REG                              (0x00001184)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL5_REG

#define DATA5CH1_CR_DDRCRRXEQTAP01_REG                                 (0x00001188)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP01_REG

#define DATA5CH1_CR_DDRCRRXEQTAP_REG                                   (0x0000118C)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP_REG

#define DATA5CH1_CR_DDRCRCMDBUSTRAIN_REG                               (0x00001190)
//Duplicate of DATA0CH0_CR_DDRCRCMDBUSTRAIN_REG

#define DATA5CH1_CR_DDRCRDATATCOCONTROL0_REG                           (0x00001194)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL0_REG

#define DATA5CH1_CR_DDRCRDATATCOCONTROL1_REG                           (0x00001198)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL1_REG

#define DATA5CH1_CR_DDRCRWRRETRAINCONTROLSTATUS_REG                    (0x0000119C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA5CH1_CR_DDRCRRDRETRAINCONTROLSTATUS_REG                    (0x000011A0)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA5CH1_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG                   (0x000011A4)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG

#define DATA5CH1_CR_DDRCRWRRETRAINDELTARANK_REG                        (0x000011A8)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINDELTARANK_REG

#define DATA5CH1_CR_DDRCRRDRETRAINDELTARANK_REG                        (0x000011AC)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAINDELTARANK_REG

#define DATA5CH1_CR_DATATRAINFEEDBACK_REG                              (0x000011B0)
//Duplicate of DATA0CH0_CR_DATATRAINFEEDBACK_REG

#define DATA5CH1_CR_DCCFSMSTATUS_REG                                   (0x000011B4)
//Duplicate of DATA0CH0_CR_DCCFSMSTATUS_REG

#define DATA5CH1_CR_DCCLANESTATUS0_REG                                 (0x000011B8)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS0_REG

#define DATA5CH1_CR_DCCLANESTATUS1_REG                                 (0x000011BC)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS1_REG

#define DATA5CH1_CR_DCCLANESTATUS2_REG                                 (0x000011C0)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS2_REG

#define DATA5CH1_CR_DCCLANESTATUS3_REG                                 (0x000011C4)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS3_REG

#define DATA5CH1_CR_DDRCRMARGINMODECONTROL0_REG                        (0x000011C8)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODECONTROL0_REG

#define DATA5CH1_CR_DDRCRMARGINMODEDEBUGMSB0_REG                       (0x000011CC)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA5CH1_CR_DDRCRMARGINMODEDEBUGLSB0_REG                       (0x000011D0)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA5CH1_CR_DDRCRDLLSTATUS_REG                                 (0x000011D4)
//Duplicate of DATA0CH0_CR_DDRCRDLLSTATUS_REG

#define DATA5CH1_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG                     (0x000011D8)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG

#define DATA5CH1_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG                (0x000011DC)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG

#define DATA5CH1_CR_DDRCRCOMPDQSDELAY_REG                              (0x000011E0)
//Duplicate of DATA0CH0_CR_DDRCRCOMPDQSDELAY_REG

#define DATA5CH1_CR_DDRCRADC_REG                                       (0x000011E4)
//Duplicate of DATA0CH0_CR_DDRCRADC_REG

#define DATA5CH1_CR_REFPIFSMCONTROL_REG                                (0x000011E8)
//Duplicate of DATA0CH0_CR_REFPIFSMCONTROL_REG

#define DATA5CH1_CR_DDRDATADQRANK0LANE8_REG                            (0x000011EC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRDATADQRANK1LANE8_REG                            (0x000011F0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA5CH1_CR_DDRCRDATAVREFPERBIT012_REG                         (0x000011F4)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT012_REG

#define DATA5CH1_CR_DDRCRDATAVREFPERBIT345_REG                         (0x000011F8)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT345_REG

#define DATA5CH1_CR_DDRCRDATAVREFPERBIT67DBI_REG                       (0x000011FC)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG

#define DATA6CH0_CR_DDRDATADQRANK0LANE0_REG                            (0x00001200)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK0LANE1_REG                            (0x00001204)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK0LANE2_REG                            (0x00001208)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK0LANE3_REG                            (0x0000120C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK0LANE4_REG                            (0x00001210)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK0LANE5_REG                            (0x00001214)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK0LANE6_REG                            (0x00001218)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK0LANE7_REG                            (0x0000121C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK1LANE0_REG                            (0x00001220)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK1LANE1_REG                            (0x00001224)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK1LANE2_REG                            (0x00001228)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK1LANE3_REG                            (0x0000122C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK1LANE4_REG                            (0x00001230)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK1LANE5_REG                            (0x00001234)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK1LANE6_REG                            (0x00001238)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK1LANE7_REG                            (0x0000123C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQSRANK0_REG                                (0x00001240)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATA6CH0_CR_DDRDATADQSRANK1_REG                                (0x00001244)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATA6CH0_CR_TXCONTROL0RANK0_REG                                (0x00001248)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATA6CH0_CR_TXCONTROL0RANK1_REG                                (0x0000124C)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATA6CH0_CR_DDRCRDATAOFFSETTRAIN_REG                           (0x00001250)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETTRAIN_REG

#define DATA6CH0_CR_DDRCRDATACONTROL2_REG                              (0x00001254)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL2_REG

#define DATA6CH0_CR_DCCFSMCONTROL_REG                                  (0x00001258)
//Duplicate of DATA0CH0_CR_DCCFSMCONTROL_REG

#define DATA6CH0_CR_DCCCALCCONTROL_REG                                 (0x0000125C)
//Duplicate of DATA0CH0_CR_DCCCALCCONTROL_REG

#define DATA6CH0_CR_DCCLANETARGET_REG                                  (0x00001260)
//Duplicate of DATA0CH0_CR_DCCLANETARGET_REG

#define DATA6CH0_CR_DDRCRRANKMUXDELAY_REG                              (0x00001264)
//Duplicate of DATA0CH0_CR_DDRCRRANKMUXDELAY_REG

#define DATA6CH0_CR_DDRCRDLLCONTROL0_REG                               (0x00001268)
//Duplicate of DATA0CH0_CR_DDRCRDLLCONTROL0_REG

#define DATA6CH0_CR_DCCPILUT0_REG                                      (0x0000126C)
//Duplicate of DATA0CH0_CR_DCCPILUT0_REG

#define DATA6CH0_CR_REFPICONTROL_REG                                   (0x00001270)
//Duplicate of DATA0CH0_CR_REFPICONTROL_REG

#define DATA6CH0_CR_SPARE_REG                                          (0x00001274)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DATA6CH0_CR_DDRCRXTALKBIASCONTROL1_REG                         (0x00001278)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL1_REG

#define DATA6CH0_CR_DDRCRDQSWCKDLLCONTROL0_REG                         (0x0000127C)
//Duplicate of DATA0CH0_CR_DDRCRDQSWCKDLLCONTROL0_REG

#define DATA6CH0_CR_TERDCCCONTROL0_REG                                 (0x00001280)
//Duplicate of DATA0CH0_CR_TERDCCCONTROL0_REG

#define DATA6CH0_CR_DDRCRXTALKBIASCONTROL2_REG                         (0x00001284)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL2_REG

#define DATA6CH0_CR_DDRCRXTALKBIASCONTROL3_REG                         (0x00001288)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL3_REG

#define DATA6CH0_CR_DDRCRXTALKBIASCONTROL4_REG                         (0x0000128C)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL4_REG

#define DATA6CH0_CR_DDRCRXTALKBIASCONTROL5_REG                         (0x00001290)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL5_REG

#define DATA6CH0_CR_DDRDATADQDCCRANK0LANE0TO4_REG                      (0x00001294)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE0TO4_REG

#define DATA6CH0_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG         (0x00001298)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG

#define DATA6CH0_CR_DDRDATADQDCCRANK1LANE2TO6_REG                      (0x0000129C)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE2TO6_REG

#define DATA6CH0_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG               (0x000012A0)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG

#define DATA6CH0_CR_SPARE1_REG                                         (0x000012A4)
//Duplicate of DATA0CH0_CR_SPARE1_REG

#define DATA6CH0_CR_VCCCLKCOMPRXOFFSET_REG                             (0x000012B4)
//Duplicate of DATA0CH0_CR_VCCCLKCOMPRXOFFSET_REG

#define DATA6CH0_CR_DDRCRWRRETRAININITRANK1_REG                        (0x000012CC)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATA6CH0_CR_DDRCRWRRETRAININITRANK0_REG                        (0x000012D0)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATA6CH0_CR_DDRCRRDRETRAININITRANK1_REG                        (0x000012DC)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATA6CH0_CR_DDRCRRDRETRAININITRANK0_REG                        (0x000012E0)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATA6CH0_CR_DDRCRRXCTLE_REG                                    (0x000012E4)
//Duplicate of DATA0CH0_CR_DDRCRRXCTLE_REG

#define DATA6CH0_CR_RXCONTROL0RANK0_REG                                (0x000012E8)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATA6CH0_CR_RXCONTROL0RANK1_REG                                (0x000012EC)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATA6CH0_CR_DDRDQREPLICACTLE_REG                               (0x000012F0)
//Duplicate of DATA0CH0_CR_DDRDQREPLICACTLE_REG

#define DATA6CH0_CR_DDRCRDATAOFFSETCOMP_REG                            (0x000012F8)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETCOMP_REG

#define DATA6CH0_CR_DDRCRDATACONTROL0_REG                              (0x000012FC)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL0_REG

#define DATA6CH0_CR_DDRCRDATACONTROL1_REG                              (0x00001300)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL1_REG

#define DATA6CH0_CR_DDRCRDATACONTROL5_REG                              (0x00001304)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL5_REG

#define DATA6CH0_CR_DDRCRRXEQTAP01_REG                                 (0x00001308)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP01_REG

#define DATA6CH0_CR_DDRCRRXEQTAP_REG                                   (0x0000130C)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP_REG

#define DATA6CH0_CR_DDRCRCMDBUSTRAIN_REG                               (0x00001310)
//Duplicate of DATA0CH0_CR_DDRCRCMDBUSTRAIN_REG

#define DATA6CH0_CR_DDRCRDATATCOCONTROL0_REG                           (0x00001314)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL0_REG

#define DATA6CH0_CR_DDRCRDATATCOCONTROL1_REG                           (0x00001318)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL1_REG

#define DATA6CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG                    (0x0000131C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA6CH0_CR_DDRCRRDRETRAINCONTROLSTATUS_REG                    (0x00001320)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA6CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG                   (0x00001324)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG

#define DATA6CH0_CR_DDRCRWRRETRAINDELTARANK_REG                        (0x00001328)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINDELTARANK_REG

#define DATA6CH0_CR_DDRCRRDRETRAINDELTARANK_REG                        (0x0000132C)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAINDELTARANK_REG

#define DATA6CH0_CR_DATATRAINFEEDBACK_REG                              (0x00001330)
//Duplicate of DATA0CH0_CR_DATATRAINFEEDBACK_REG

#define DATA6CH0_CR_DCCFSMSTATUS_REG                                   (0x00001334)
//Duplicate of DATA0CH0_CR_DCCFSMSTATUS_REG

#define DATA6CH0_CR_DCCLANESTATUS0_REG                                 (0x00001338)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS0_REG

#define DATA6CH0_CR_DCCLANESTATUS1_REG                                 (0x0000133C)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS1_REG

#define DATA6CH0_CR_DCCLANESTATUS2_REG                                 (0x00001340)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS2_REG

#define DATA6CH0_CR_DCCLANESTATUS3_REG                                 (0x00001344)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS3_REG

#define DATA6CH0_CR_DDRCRMARGINMODECONTROL0_REG                        (0x00001348)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODECONTROL0_REG

#define DATA6CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG                       (0x0000134C)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA6CH0_CR_DDRCRMARGINMODEDEBUGLSB0_REG                       (0x00001350)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA6CH0_CR_DDRCRDLLSTATUS_REG                                 (0x00001354)
//Duplicate of DATA0CH0_CR_DDRCRDLLSTATUS_REG

#define DATA6CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG                     (0x00001358)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG

#define DATA6CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG                (0x0000135C)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG

#define DATA6CH0_CR_DDRCRCOMPDQSDELAY_REG                              (0x00001360)
//Duplicate of DATA0CH0_CR_DDRCRCOMPDQSDELAY_REG

#define DATA6CH0_CR_DDRCRADC_REG                                       (0x00001364)
//Duplicate of DATA0CH0_CR_DDRCRADC_REG

#define DATA6CH0_CR_REFPIFSMCONTROL_REG                                (0x00001368)
//Duplicate of DATA0CH0_CR_REFPIFSMCONTROL_REG

#define DATA6CH0_CR_DDRDATADQRANK0LANE8_REG                            (0x0000136C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRDATADQRANK1LANE8_REG                            (0x00001370)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH0_CR_DDRCRDATAVREFPERBIT012_REG                         (0x00001374)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT012_REG

#define DATA6CH0_CR_DDRCRDATAVREFPERBIT345_REG                         (0x00001378)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT345_REG

#define DATA6CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG                       (0x0000137C)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG

#define DATA6CH1_CR_DDRDATADQRANK0LANE0_REG                            (0x00001380)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK0LANE1_REG                            (0x00001384)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK0LANE2_REG                            (0x00001388)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK0LANE3_REG                            (0x0000138C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK0LANE4_REG                            (0x00001390)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK0LANE5_REG                            (0x00001394)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK0LANE6_REG                            (0x00001398)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK0LANE7_REG                            (0x0000139C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK1LANE0_REG                            (0x000013A0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK1LANE1_REG                            (0x000013A4)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK1LANE2_REG                            (0x000013A8)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK1LANE3_REG                            (0x000013AC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK1LANE4_REG                            (0x000013B0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK1LANE5_REG                            (0x000013B4)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK1LANE6_REG                            (0x000013B8)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK1LANE7_REG                            (0x000013BC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQSRANK0_REG                                (0x000013C0)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATA6CH1_CR_DDRDATADQSRANK1_REG                                (0x000013C4)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATA6CH1_CR_TXCONTROL0RANK0_REG                                (0x000013C8)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATA6CH1_CR_TXCONTROL0RANK1_REG                                (0x000013CC)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATA6CH1_CR_DDRCRDATAOFFSETTRAIN_REG                           (0x000013D0)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETTRAIN_REG

#define DATA6CH1_CR_DDRCRDATACONTROL2_REG                              (0x000013D4)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL2_REG

#define DATA6CH1_CR_DCCFSMCONTROL_REG                                  (0x000013D8)
//Duplicate of DATA0CH0_CR_DCCFSMCONTROL_REG

#define DATA6CH1_CR_DCCCALCCONTROL_REG                                 (0x000013DC)
//Duplicate of DATA0CH0_CR_DCCCALCCONTROL_REG

#define DATA6CH1_CR_DCCLANETARGET_REG                                  (0x000013E0)
//Duplicate of DATA0CH0_CR_DCCLANETARGET_REG

#define DATA6CH1_CR_DDRCRRANKMUXDELAY_REG                              (0x000013E4)
//Duplicate of DATA0CH0_CR_DDRCRRANKMUXDELAY_REG

#define DATA6CH1_CR_DDRCRDLLCONTROL0_REG                               (0x000013E8)
//Duplicate of DATA0CH0_CR_DDRCRDLLCONTROL0_REG

#define DATA6CH1_CR_DCCPILUT0_REG                                      (0x000013EC)
//Duplicate of DATA0CH0_CR_DCCPILUT0_REG

#define DATA6CH1_CR_REFPICONTROL_REG                                   (0x000013F0)
//Duplicate of DATA0CH0_CR_REFPICONTROL_REG

#define DATA6CH1_CR_SPARE_REG                                          (0x000013F4)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DATA6CH1_CR_DDRCRXTALKBIASCONTROL1_REG                         (0x000013F8)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL1_REG

#define DATA6CH1_CR_DDRCRDQSWCKDLLCONTROL0_REG                         (0x000013FC)
//Duplicate of DATA0CH0_CR_DDRCRDQSWCKDLLCONTROL0_REG

#define DATA6CH1_CR_TERDCCCONTROL0_REG                                 (0x00001400)
//Duplicate of DATA0CH0_CR_TERDCCCONTROL0_REG

#define DATA6CH1_CR_DDRCRXTALKBIASCONTROL2_REG                         (0x00001404)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL2_REG

#define DATA6CH1_CR_DDRCRXTALKBIASCONTROL3_REG                         (0x00001408)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL3_REG

#define DATA6CH1_CR_DDRCRXTALKBIASCONTROL4_REG                         (0x0000140C)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL4_REG

#define DATA6CH1_CR_DDRCRXTALKBIASCONTROL5_REG                         (0x00001410)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL5_REG

#define DATA6CH1_CR_DDRDATADQDCCRANK0LANE0TO4_REG                      (0x00001414)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE0TO4_REG

#define DATA6CH1_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG         (0x00001418)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG

#define DATA6CH1_CR_DDRDATADQDCCRANK1LANE2TO6_REG                      (0x0000141C)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE2TO6_REG

#define DATA6CH1_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG               (0x00001420)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG

#define DATA6CH1_CR_SPARE1_REG                                         (0x00001424)
//Duplicate of DATA0CH0_CR_SPARE1_REG

#define DATA6CH1_CR_VCCCLKCOMPRXOFFSET_REG                             (0x00001434)
//Duplicate of DATA0CH0_CR_VCCCLKCOMPRXOFFSET_REG

#define DATA6CH1_CR_DDRCRWRRETRAININITRANK1_REG                        (0x0000144C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATA6CH1_CR_DDRCRWRRETRAININITRANK0_REG                        (0x00001450)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATA6CH1_CR_DDRCRRDRETRAININITRANK1_REG                        (0x0000145C)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATA6CH1_CR_DDRCRRDRETRAININITRANK0_REG                        (0x00001460)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATA6CH1_CR_DDRCRRXCTLE_REG                                    (0x00001464)
//Duplicate of DATA0CH0_CR_DDRCRRXCTLE_REG

#define DATA6CH1_CR_RXCONTROL0RANK0_REG                                (0x00001468)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATA6CH1_CR_RXCONTROL0RANK1_REG                                (0x0000146C)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATA6CH1_CR_DDRDQREPLICACTLE_REG                               (0x00001470)
//Duplicate of DATA0CH0_CR_DDRDQREPLICACTLE_REG

#define DATA6CH1_CR_DDRCRDATAOFFSETCOMP_REG                            (0x00001478)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETCOMP_REG

#define DATA6CH1_CR_DDRCRDATACONTROL0_REG                              (0x0000147C)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL0_REG

#define DATA6CH1_CR_DDRCRDATACONTROL1_REG                              (0x00001480)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL1_REG

#define DATA6CH1_CR_DDRCRDATACONTROL5_REG                              (0x00001484)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL5_REG

#define DATA6CH1_CR_DDRCRRXEQTAP01_REG                                 (0x00001488)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP01_REG

#define DATA6CH1_CR_DDRCRRXEQTAP_REG                                   (0x0000148C)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP_REG

#define DATA6CH1_CR_DDRCRCMDBUSTRAIN_REG                               (0x00001490)
//Duplicate of DATA0CH0_CR_DDRCRCMDBUSTRAIN_REG

#define DATA6CH1_CR_DDRCRDATATCOCONTROL0_REG                           (0x00001494)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL0_REG

#define DATA6CH1_CR_DDRCRDATATCOCONTROL1_REG                           (0x00001498)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL1_REG

#define DATA6CH1_CR_DDRCRWRRETRAINCONTROLSTATUS_REG                    (0x0000149C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA6CH1_CR_DDRCRRDRETRAINCONTROLSTATUS_REG                    (0x000014A0)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA6CH1_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG                   (0x000014A4)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG

#define DATA6CH1_CR_DDRCRWRRETRAINDELTARANK_REG                        (0x000014A8)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINDELTARANK_REG

#define DATA6CH1_CR_DDRCRRDRETRAINDELTARANK_REG                        (0x000014AC)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAINDELTARANK_REG

#define DATA6CH1_CR_DATATRAINFEEDBACK_REG                              (0x000014B0)
//Duplicate of DATA0CH0_CR_DATATRAINFEEDBACK_REG

#define DATA6CH1_CR_DCCFSMSTATUS_REG                                   (0x000014B4)
//Duplicate of DATA0CH0_CR_DCCFSMSTATUS_REG

#define DATA6CH1_CR_DCCLANESTATUS0_REG                                 (0x000014B8)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS0_REG

#define DATA6CH1_CR_DCCLANESTATUS1_REG                                 (0x000014BC)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS1_REG

#define DATA6CH1_CR_DCCLANESTATUS2_REG                                 (0x000014C0)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS2_REG

#define DATA6CH1_CR_DCCLANESTATUS3_REG                                 (0x000014C4)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS3_REG

#define DATA6CH1_CR_DDRCRMARGINMODECONTROL0_REG                        (0x000014C8)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODECONTROL0_REG

#define DATA6CH1_CR_DDRCRMARGINMODEDEBUGMSB0_REG                       (0x000014CC)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA6CH1_CR_DDRCRMARGINMODEDEBUGLSB0_REG                       (0x000014D0)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA6CH1_CR_DDRCRDLLSTATUS_REG                                 (0x000014D4)
//Duplicate of DATA0CH0_CR_DDRCRDLLSTATUS_REG

#define DATA6CH1_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG                     (0x000014D8)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG

#define DATA6CH1_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG                (0x000014DC)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG

#define DATA6CH1_CR_DDRCRCOMPDQSDELAY_REG                              (0x000014E0)
//Duplicate of DATA0CH0_CR_DDRCRCOMPDQSDELAY_REG

#define DATA6CH1_CR_DDRCRADC_REG                                       (0x000014E4)
//Duplicate of DATA0CH0_CR_DDRCRADC_REG

#define DATA6CH1_CR_REFPIFSMCONTROL_REG                                (0x000014E8)
//Duplicate of DATA0CH0_CR_REFPIFSMCONTROL_REG

#define DATA6CH1_CR_DDRDATADQRANK0LANE8_REG                            (0x000014EC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRDATADQRANK1LANE8_REG                            (0x000014F0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA6CH1_CR_DDRCRDATAVREFPERBIT012_REG                         (0x000014F4)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT012_REG

#define DATA6CH1_CR_DDRCRDATAVREFPERBIT345_REG                         (0x000014F8)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT345_REG

#define DATA6CH1_CR_DDRCRDATAVREFPERBIT67DBI_REG                       (0x000014FC)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG

#define DATA7CH0_CR_DDRDATADQRANK0LANE0_REG                            (0x00001500)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK0LANE1_REG                            (0x00001504)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK0LANE2_REG                            (0x00001508)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK0LANE3_REG                            (0x0000150C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK0LANE4_REG                            (0x00001510)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK0LANE5_REG                            (0x00001514)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK0LANE6_REG                            (0x00001518)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK0LANE7_REG                            (0x0000151C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK1LANE0_REG                            (0x00001520)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK1LANE1_REG                            (0x00001524)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK1LANE2_REG                            (0x00001528)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK1LANE3_REG                            (0x0000152C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK1LANE4_REG                            (0x00001530)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK1LANE5_REG                            (0x00001534)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK1LANE6_REG                            (0x00001538)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK1LANE7_REG                            (0x0000153C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQSRANK0_REG                                (0x00001540)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATA7CH0_CR_DDRDATADQSRANK1_REG                                (0x00001544)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATA7CH0_CR_TXCONTROL0RANK0_REG                                (0x00001548)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATA7CH0_CR_TXCONTROL0RANK1_REG                                (0x0000154C)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATA7CH0_CR_DDRCRDATAOFFSETTRAIN_REG                           (0x00001550)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETTRAIN_REG

#define DATA7CH0_CR_DDRCRDATACONTROL2_REG                              (0x00001554)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL2_REG

#define DATA7CH0_CR_DCCFSMCONTROL_REG                                  (0x00001558)
//Duplicate of DATA0CH0_CR_DCCFSMCONTROL_REG

#define DATA7CH0_CR_DCCCALCCONTROL_REG                                 (0x0000155C)
//Duplicate of DATA0CH0_CR_DCCCALCCONTROL_REG

#define DATA7CH0_CR_DCCLANETARGET_REG                                  (0x00001560)
//Duplicate of DATA0CH0_CR_DCCLANETARGET_REG

#define DATA7CH0_CR_DDRCRRANKMUXDELAY_REG                              (0x00001564)
//Duplicate of DATA0CH0_CR_DDRCRRANKMUXDELAY_REG

#define DATA7CH0_CR_DDRCRDLLCONTROL0_REG                               (0x00001568)
//Duplicate of DATA0CH0_CR_DDRCRDLLCONTROL0_REG

#define DATA7CH0_CR_DCCPILUT0_REG                                      (0x0000156C)
//Duplicate of DATA0CH0_CR_DCCPILUT0_REG

#define DATA7CH0_CR_REFPICONTROL_REG                                   (0x00001570)
//Duplicate of DATA0CH0_CR_REFPICONTROL_REG

#define DATA7CH0_CR_SPARE_REG                                          (0x00001574)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DATA7CH0_CR_DDRCRXTALKBIASCONTROL1_REG                         (0x00001578)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL1_REG

#define DATA7CH0_CR_DDRCRDQSWCKDLLCONTROL0_REG                         (0x0000157C)
//Duplicate of DATA0CH0_CR_DDRCRDQSWCKDLLCONTROL0_REG

#define DATA7CH0_CR_TERDCCCONTROL0_REG                                 (0x00001580)
//Duplicate of DATA0CH0_CR_TERDCCCONTROL0_REG

#define DATA7CH0_CR_DDRCRXTALKBIASCONTROL2_REG                         (0x00001584)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL2_REG

#define DATA7CH0_CR_DDRCRXTALKBIASCONTROL3_REG                         (0x00001588)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL3_REG

#define DATA7CH0_CR_DDRCRXTALKBIASCONTROL4_REG                         (0x0000158C)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL4_REG

#define DATA7CH0_CR_DDRCRXTALKBIASCONTROL5_REG                         (0x00001590)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL5_REG

#define DATA7CH0_CR_DDRDATADQDCCRANK0LANE0TO4_REG                      (0x00001594)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE0TO4_REG

#define DATA7CH0_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG         (0x00001598)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG

#define DATA7CH0_CR_DDRDATADQDCCRANK1LANE2TO6_REG                      (0x0000159C)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE2TO6_REG

#define DATA7CH0_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG               (0x000015A0)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG

#define DATA7CH0_CR_SPARE1_REG                                         (0x000015A4)
//Duplicate of DATA0CH0_CR_SPARE1_REG

#define DATA7CH0_CR_VCCCLKCOMPRXOFFSET_REG                             (0x000015B4)
//Duplicate of DATA0CH0_CR_VCCCLKCOMPRXOFFSET_REG

#define DATA7CH0_CR_DDRCRWRRETRAININITRANK1_REG                        (0x000015CC)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATA7CH0_CR_DDRCRWRRETRAININITRANK0_REG                        (0x000015D0)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATA7CH0_CR_DDRCRRDRETRAININITRANK1_REG                        (0x000015DC)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATA7CH0_CR_DDRCRRDRETRAININITRANK0_REG                        (0x000015E0)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATA7CH0_CR_DDRCRRXCTLE_REG                                    (0x000015E4)
//Duplicate of DATA0CH0_CR_DDRCRRXCTLE_REG

#define DATA7CH0_CR_RXCONTROL0RANK0_REG                                (0x000015E8)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATA7CH0_CR_RXCONTROL0RANK1_REG                                (0x000015EC)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATA7CH0_CR_DDRDQREPLICACTLE_REG                               (0x000015F0)
//Duplicate of DATA0CH0_CR_DDRDQREPLICACTLE_REG

#define DATA7CH0_CR_DDRCRDATAOFFSETCOMP_REG                            (0x000015F8)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETCOMP_REG

#define DATA7CH0_CR_DDRCRDATACONTROL0_REG                              (0x000015FC)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL0_REG

#define DATA7CH0_CR_DDRCRDATACONTROL1_REG                              (0x00001600)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL1_REG

#define DATA7CH0_CR_DDRCRDATACONTROL5_REG                              (0x00001604)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL5_REG

#define DATA7CH0_CR_DDRCRRXEQTAP01_REG                                 (0x00001608)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP01_REG

#define DATA7CH0_CR_DDRCRRXEQTAP_REG                                   (0x0000160C)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP_REG

#define DATA7CH0_CR_DDRCRCMDBUSTRAIN_REG                               (0x00001610)
//Duplicate of DATA0CH0_CR_DDRCRCMDBUSTRAIN_REG

#define DATA7CH0_CR_DDRCRDATATCOCONTROL0_REG                           (0x00001614)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL0_REG

#define DATA7CH0_CR_DDRCRDATATCOCONTROL1_REG                           (0x00001618)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL1_REG

#define DATA7CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG                    (0x0000161C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA7CH0_CR_DDRCRRDRETRAINCONTROLSTATUS_REG                    (0x00001620)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA7CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG                   (0x00001624)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG

#define DATA7CH0_CR_DDRCRWRRETRAINDELTARANK_REG                        (0x00001628)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINDELTARANK_REG

#define DATA7CH0_CR_DDRCRRDRETRAINDELTARANK_REG                        (0x0000162C)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAINDELTARANK_REG

#define DATA7CH0_CR_DATATRAINFEEDBACK_REG                              (0x00001630)
//Duplicate of DATA0CH0_CR_DATATRAINFEEDBACK_REG

#define DATA7CH0_CR_DCCFSMSTATUS_REG                                   (0x00001634)
//Duplicate of DATA0CH0_CR_DCCFSMSTATUS_REG

#define DATA7CH0_CR_DCCLANESTATUS0_REG                                 (0x00001638)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS0_REG

#define DATA7CH0_CR_DCCLANESTATUS1_REG                                 (0x0000163C)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS1_REG

#define DATA7CH0_CR_DCCLANESTATUS2_REG                                 (0x00001640)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS2_REG

#define DATA7CH0_CR_DCCLANESTATUS3_REG                                 (0x00001644)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS3_REG

#define DATA7CH0_CR_DDRCRMARGINMODECONTROL0_REG                        (0x00001648)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODECONTROL0_REG

#define DATA7CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG                       (0x0000164C)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA7CH0_CR_DDRCRMARGINMODEDEBUGLSB0_REG                       (0x00001650)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA7CH0_CR_DDRCRDLLSTATUS_REG                                 (0x00001654)
//Duplicate of DATA0CH0_CR_DDRCRDLLSTATUS_REG

#define DATA7CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG                     (0x00001658)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG

#define DATA7CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG                (0x0000165C)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG

#define DATA7CH0_CR_DDRCRCOMPDQSDELAY_REG                              (0x00001660)
//Duplicate of DATA0CH0_CR_DDRCRCOMPDQSDELAY_REG

#define DATA7CH0_CR_DDRCRADC_REG                                       (0x00001664)
//Duplicate of DATA0CH0_CR_DDRCRADC_REG

#define DATA7CH0_CR_REFPIFSMCONTROL_REG                                (0x00001668)
//Duplicate of DATA0CH0_CR_REFPIFSMCONTROL_REG

#define DATA7CH0_CR_DDRDATADQRANK0LANE8_REG                            (0x0000166C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRDATADQRANK1LANE8_REG                            (0x00001670)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH0_CR_DDRCRDATAVREFPERBIT012_REG                         (0x00001674)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT012_REG

#define DATA7CH0_CR_DDRCRDATAVREFPERBIT345_REG                         (0x00001678)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT345_REG

#define DATA7CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG                       (0x0000167C)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG

#define DATA7CH1_CR_DDRDATADQRANK0LANE0_REG                            (0x00001680)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK0LANE1_REG                            (0x00001684)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK0LANE2_REG                            (0x00001688)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK0LANE3_REG                            (0x0000168C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK0LANE4_REG                            (0x00001690)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK0LANE5_REG                            (0x00001694)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK0LANE6_REG                            (0x00001698)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK0LANE7_REG                            (0x0000169C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK1LANE0_REG                            (0x000016A0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK1LANE1_REG                            (0x000016A4)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK1LANE2_REG                            (0x000016A8)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK1LANE3_REG                            (0x000016AC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK1LANE4_REG                            (0x000016B0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK1LANE5_REG                            (0x000016B4)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK1LANE6_REG                            (0x000016B8)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK1LANE7_REG                            (0x000016BC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQSRANK0_REG                                (0x000016C0)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATA7CH1_CR_DDRDATADQSRANK1_REG                                (0x000016C4)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATA7CH1_CR_TXCONTROL0RANK0_REG                                (0x000016C8)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATA7CH1_CR_TXCONTROL0RANK1_REG                                (0x000016CC)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATA7CH1_CR_DDRCRDATAOFFSETTRAIN_REG                           (0x000016D0)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETTRAIN_REG

#define DATA7CH1_CR_DDRCRDATACONTROL2_REG                              (0x000016D4)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL2_REG

#define DATA7CH1_CR_DCCFSMCONTROL_REG                                  (0x000016D8)
//Duplicate of DATA0CH0_CR_DCCFSMCONTROL_REG

#define DATA7CH1_CR_DCCCALCCONTROL_REG                                 (0x000016DC)
//Duplicate of DATA0CH0_CR_DCCCALCCONTROL_REG

#define DATA7CH1_CR_DCCLANETARGET_REG                                  (0x000016E0)
//Duplicate of DATA0CH0_CR_DCCLANETARGET_REG

#define DATA7CH1_CR_DDRCRRANKMUXDELAY_REG                              (0x000016E4)
//Duplicate of DATA0CH0_CR_DDRCRRANKMUXDELAY_REG

#define DATA7CH1_CR_DDRCRDLLCONTROL0_REG                               (0x000016E8)
//Duplicate of DATA0CH0_CR_DDRCRDLLCONTROL0_REG

#define DATA7CH1_CR_DCCPILUT0_REG                                      (0x000016EC)
//Duplicate of DATA0CH0_CR_DCCPILUT0_REG

#define DATA7CH1_CR_REFPICONTROL_REG                                   (0x000016F0)
//Duplicate of DATA0CH0_CR_REFPICONTROL_REG

#define DATA7CH1_CR_SPARE_REG                                          (0x000016F4)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DATA7CH1_CR_DDRCRXTALKBIASCONTROL1_REG                         (0x000016F8)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL1_REG

#define DATA7CH1_CR_DDRCRDQSWCKDLLCONTROL0_REG                         (0x000016FC)
//Duplicate of DATA0CH0_CR_DDRCRDQSWCKDLLCONTROL0_REG

#define DATA7CH1_CR_TERDCCCONTROL0_REG                                 (0x00001700)
//Duplicate of DATA0CH0_CR_TERDCCCONTROL0_REG

#define DATA7CH1_CR_DDRCRXTALKBIASCONTROL2_REG                         (0x00001704)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL2_REG

#define DATA7CH1_CR_DDRCRXTALKBIASCONTROL3_REG                         (0x00001708)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL3_REG

#define DATA7CH1_CR_DDRCRXTALKBIASCONTROL4_REG                         (0x0000170C)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL4_REG

#define DATA7CH1_CR_DDRCRXTALKBIASCONTROL5_REG                         (0x00001710)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL5_REG

#define DATA7CH1_CR_DDRDATADQDCCRANK0LANE0TO4_REG                      (0x00001714)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE0TO4_REG

#define DATA7CH1_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG         (0x00001718)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG

#define DATA7CH1_CR_DDRDATADQDCCRANK1LANE2TO6_REG                      (0x0000171C)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE2TO6_REG

#define DATA7CH1_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG               (0x00001720)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG

#define DATA7CH1_CR_SPARE1_REG                                         (0x00001724)
//Duplicate of DATA0CH0_CR_SPARE1_REG

#define DATA7CH1_CR_VCCCLKCOMPRXOFFSET_REG                             (0x00001734)
//Duplicate of DATA0CH0_CR_VCCCLKCOMPRXOFFSET_REG

#define DATA7CH1_CR_DDRCRWRRETRAININITRANK1_REG                        (0x0000174C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATA7CH1_CR_DDRCRWRRETRAININITRANK0_REG                        (0x00001750)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATA7CH1_CR_DDRCRRDRETRAININITRANK1_REG                        (0x0000175C)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATA7CH1_CR_DDRCRRDRETRAININITRANK0_REG                        (0x00001760)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATA7CH1_CR_DDRCRRXCTLE_REG                                    (0x00001764)
//Duplicate of DATA0CH0_CR_DDRCRRXCTLE_REG

#define DATA7CH1_CR_RXCONTROL0RANK0_REG                                (0x00001768)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATA7CH1_CR_RXCONTROL0RANK1_REG                                (0x0000176C)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATA7CH1_CR_DDRDQREPLICACTLE_REG                               (0x00001770)
//Duplicate of DATA0CH0_CR_DDRDQREPLICACTLE_REG

#define DATA7CH1_CR_DDRCRDATAOFFSETCOMP_REG                            (0x00001778)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETCOMP_REG

#define DATA7CH1_CR_DDRCRDATACONTROL0_REG                              (0x0000177C)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL0_REG

#define DATA7CH1_CR_DDRCRDATACONTROL1_REG                              (0x00001780)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL1_REG

#define DATA7CH1_CR_DDRCRDATACONTROL5_REG                              (0x00001784)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL5_REG

#define DATA7CH1_CR_DDRCRRXEQTAP01_REG                                 (0x00001788)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP01_REG

#define DATA7CH1_CR_DDRCRRXEQTAP_REG                                   (0x0000178C)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP_REG

#define DATA7CH1_CR_DDRCRCMDBUSTRAIN_REG                               (0x00001790)
//Duplicate of DATA0CH0_CR_DDRCRCMDBUSTRAIN_REG

#define DATA7CH1_CR_DDRCRDATATCOCONTROL0_REG                           (0x00001794)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL0_REG

#define DATA7CH1_CR_DDRCRDATATCOCONTROL1_REG                           (0x00001798)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL1_REG

#define DATA7CH1_CR_DDRCRWRRETRAINCONTROLSTATUS_REG                    (0x0000179C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA7CH1_CR_DDRCRRDRETRAINCONTROLSTATUS_REG                    (0x000017A0)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA7CH1_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG                   (0x000017A4)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG

#define DATA7CH1_CR_DDRCRWRRETRAINDELTARANK_REG                        (0x000017A8)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINDELTARANK_REG

#define DATA7CH1_CR_DDRCRRDRETRAINDELTARANK_REG                        (0x000017AC)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAINDELTARANK_REG

#define DATA7CH1_CR_DATATRAINFEEDBACK_REG                              (0x000017B0)
//Duplicate of DATA0CH0_CR_DATATRAINFEEDBACK_REG

#define DATA7CH1_CR_DCCFSMSTATUS_REG                                   (0x000017B4)
//Duplicate of DATA0CH0_CR_DCCFSMSTATUS_REG

#define DATA7CH1_CR_DCCLANESTATUS0_REG                                 (0x000017B8)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS0_REG

#define DATA7CH1_CR_DCCLANESTATUS1_REG                                 (0x000017BC)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS1_REG

#define DATA7CH1_CR_DCCLANESTATUS2_REG                                 (0x000017C0)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS2_REG

#define DATA7CH1_CR_DCCLANESTATUS3_REG                                 (0x000017C4)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS3_REG

#define DATA7CH1_CR_DDRCRMARGINMODECONTROL0_REG                        (0x000017C8)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODECONTROL0_REG

#define DATA7CH1_CR_DDRCRMARGINMODEDEBUGMSB0_REG                       (0x000017CC)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA7CH1_CR_DDRCRMARGINMODEDEBUGLSB0_REG                       (0x000017D0)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA7CH1_CR_DDRCRDLLSTATUS_REG                                 (0x000017D4)
//Duplicate of DATA0CH0_CR_DDRCRDLLSTATUS_REG

#define DATA7CH1_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG                     (0x000017D8)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG

#define DATA7CH1_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG                (0x000017DC)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG

#define DATA7CH1_CR_DDRCRCOMPDQSDELAY_REG                              (0x000017E0)
//Duplicate of DATA0CH0_CR_DDRCRCOMPDQSDELAY_REG

#define DATA7CH1_CR_DDRCRADC_REG                                       (0x000017E4)
//Duplicate of DATA0CH0_CR_DDRCRADC_REG

#define DATA7CH1_CR_REFPIFSMCONTROL_REG                                (0x000017E8)
//Duplicate of DATA0CH0_CR_REFPIFSMCONTROL_REG

#define DATA7CH1_CR_DDRDATADQRANK0LANE8_REG                            (0x000017EC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRDATADQRANK1LANE8_REG                            (0x000017F0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA7CH1_CR_DDRCRDATAVREFPERBIT012_REG                         (0x000017F4)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT012_REG

#define DATA7CH1_CR_DDRCRDATAVREFPERBIT345_REG                         (0x000017F8)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT345_REG

#define DATA7CH1_CR_DDRCRDATAVREFPERBIT67DBI_REG                       (0x000017FC)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG

#define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_REG                           (0x00001E00)
#define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_DEF                           (0x20000000)
#define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_VOLATILE_BITFIELDS_MSK        (0xC7A00000)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target0_OFF                 ( 0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target0_WID                 ( 9)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target0_MSK                 (0x000001FF)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target0_MIN                 (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target0_MAX                 (511) // 0x000001FF
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target0_DEF                 (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target0_HSH                 (0x09001E00)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target1_OFF                 ( 9)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target1_WID                 ( 9)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target1_MSK                 (0x0003FE00)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target1_MIN                 (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target1_MAX                 (511) // 0x000001FF
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target1_DEF                 (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Target1_HSH                 (0x09121E00)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Spare_OFF                   (18)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Spare_WID                   ( 2)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Spare_MSK                   (0x000C0000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Spare_MIN                   (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Spare_MAX                   (3) // 0x00000003
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Spare_DEF                   (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Spare_HSH                   (0x02241E00)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnSensor_OFF                (20)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnSensor_WID                ( 1)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnSensor_MSK                (0x00100000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnSensor_MIN                (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnSensor_MAX                (1) // 0x00000001
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnSensor_DEF                (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnSensor_HSH                (0x01281E00)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_RstCount_OFF                (21)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_RstCount_WID                ( 1)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_RstCount_MSK                (0x00200000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_RstCount_MIN                (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_RstCount_MAX                (1) // 0x00000001
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_RstCount_DEF                (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_RstCount_HSH                (0x01AA1E00)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_SelCount_OFF                (22)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_SelCount_WID                ( 1)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_SelCount_MSK                (0x00400000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_SelCount_MIN                (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_SelCount_MAX                (1) // 0x00000001
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_SelCount_DEF                (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_SelCount_HSH                (0x012C1E00)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_CountMSB_OFF                (23)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_CountMSB_WID                ( 4)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_CountMSB_MSK                (0x07800000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_CountMSB_MIN                (-8)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_CountMSB_MAX                (7) // 0x00000007
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_CountMSB_DEF                (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_CountMSB_HSH                (0x84AE1E00)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_UsePSAL_OFF                 (27)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_UsePSAL_WID                 ( 1)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_UsePSAL_MSK                 (0x08000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_UsePSAL_MIN                 (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_UsePSAL_MAX                 (1) // 0x00000001
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_UsePSAL_DEF                 (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_UsePSAL_HSH                 (0x01361E00)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Chop_OFF                    (28)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Chop_WID                    ( 1)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Chop_MSK                    (0x10000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Chop_MIN                    (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Chop_MAX                    (1) // 0x00000001
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Chop_DEF                    (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_Chop_HSH                    (0x01381E00)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnDiv_OFF                   (29)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnDiv_WID                   ( 1)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnDiv_MSK                   (0x20000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnDiv_MIN                   (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnDiv_MAX                   (1) // 0x00000001
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnDiv_DEF                   (0x00000001)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_EnDiv_HSH                   (0x013A1E00)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaUndervoltage_OFF        (30)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaUndervoltage_WID        ( 1)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaUndervoltage_MSK        (0x40000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaUndervoltage_MIN        (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaUndervoltage_MAX        (1) // 0x00000001
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaUndervoltage_DEF        (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaUndervoltage_HSH        (0x01BC1E00)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaOvervoltage_OFF         (31)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaOvervoltage_WID         ( 1)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaOvervoltage_MSK         (0x80000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaOvervoltage_MIN         (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaOvervoltage_MAX         (1) // 0x00000001
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaOvervoltage_DEF         (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_FusaOvervoltage_HSH         (0x01BE1E00)

#define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_REG                      (0x00001E04)
#define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_DEF                      (0x00000000)
#define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_VOLATILE_BITFIELDS_MSK   (0x00FFFFFF)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count0_OFF             ( 0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count0_WID             (12)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count0_MSK             (0x00000FFF)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count0_MIN             (-2048)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count0_MAX             (2047) // 0x000007FF
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count0_DEF             (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count0_HSH             (0x8C801E04)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count1_OFF             (12)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count1_WID             (12)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count1_MSK             (0x00FFF000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count1_MIN             (-2048)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count1_MAX             (2047) // 0x000007FF
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count1_DEF             (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Count1_HSH             (0x8C981E04)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_CntStart_OFF           (24)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_CntStart_WID           ( 2)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_CntStart_MSK           (0x03000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_CntStart_MIN           (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_CntStart_MAX           (3) // 0x00000003
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_CntStart_DEF           (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_CntStart_HSH           (0x02301E04)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Duration_OFF           (26)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Duration_WID           ( 3)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Duration_MSK           (0x1C000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Duration_MIN           (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Duration_MAX           (7) // 0x00000007
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Duration_DEF           (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_Duration_HSH           (0x03341E04)

  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_SelLVR_OFF             (29)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_SelLVR_WID             ( 3)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_SelLVR_MSK             (0xE0000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_SelLVR_MIN             (0)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_SelLVR_MAX             (7) // 0x00000007
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_SelLVR_DEF             (0x00000000)
  #define DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_SelLVR_HSH             (0x033A1E04)

#define DDRPGTERMCR0_CR_SPARE_REG                                      (0x00001E08)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DDRPGTERMCR0_CR_TLINETERMINATION_REG                           (0x00001E28)
#define DDRPGTERMCR0_CR_TLINETERMINATION_DEF                           (0x00000000)
#define DDRPGTERMCR0_CR_TLINETERMINATION_VOLATILE_BITFIELDS_MSK        (0x000000F3)

  #define DDRPGTERMCR0_CR_TLINETERMINATION_TlBonusOut_OFF              ( 0)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_TlBonusOut_WID              ( 2)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_TlBonusOut_MSK              (0x00000003)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_TlBonusOut_MIN              (0)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_TlBonusOut_MAX              (3) // 0x00000003
  #define DDRPGTERMCR0_CR_TLINETERMINATION_TlBonusOut_DEF              (0x00000000)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_TlBonusOut_HSH              (0x02801E28)

  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusIn_OFF               ( 2)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusIn_WID               ( 2)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusIn_MSK               (0x0000000C)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusIn_MIN               (0)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusIn_MAX               (3) // 0x00000003
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusIn_DEF               (0x00000000)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusIn_HSH               (0x02041E28)

  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut0_OFF             ( 4)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut0_WID             ( 2)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut0_MSK             (0x00000030)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut0_MIN             (0)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut0_MAX             (3) // 0x00000003
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut0_DEF             (0x00000000)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut0_HSH             (0x02881E28)

  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut1_OFF             ( 6)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut1_WID             ( 2)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut1_MSK             (0x000000C0)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut1_MIN             (0)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut1_MAX             (3) // 0x00000003
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut1_DEF             (0x00000000)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VSBonusOut1_HSH             (0x028C1E28)

  #define DDRPGTERMCR0_CR_TLINETERMINATION_VS_sel_vdd2_ladder_OFF      ( 8)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VS_sel_vdd2_ladder_WID      ( 1)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VS_sel_vdd2_ladder_MSK      (0x00000100)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VS_sel_vdd2_ladder_MIN      (0)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VS_sel_vdd2_ladder_MAX      (1) // 0x00000001
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VS_sel_vdd2_ladder_DEF      (0x00000000)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_VS_sel_vdd2_ladder_HSH      (0x01101E28)

  #define DDRPGTERMCR0_CR_TLINETERMINATION_Spare_OFF                   ( 9)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_Spare_WID                   (23)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_Spare_MSK                   (0xFFFFFE00)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_Spare_MIN                   (0)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_Spare_MAX                   (8388607) // 0x007FFFFF
  #define DDRPGTERMCR0_CR_TLINETERMINATION_Spare_DEF                   (0x00000000)
  #define DDRPGTERMCR0_CR_TLINETERMINATION_Spare_HSH                   (0x17121E28)

#define DDRPGCR0_CR_LVRVOLTAGESENSOR_REG                               (0x00001E80)
//Duplicate of DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_REG

#define DDRPGCR0_CR_LVRVOLTAGESENSORCOUNT_REG                          (0x00001E84)
//Duplicate of DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_REG

#define DDRPGCR0_CR_SPARE_REG                                          (0x00001E88)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DDRPGCR0_CR_TLINETERMINATION_REG                               (0x00001EA8)
//Duplicate of DDRPGTERMCR0_CR_TLINETERMINATION_REG

#define DDRPGCR1_CR_LVRVOLTAGESENSOR_REG                               (0x00001F00)
//Duplicate of DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_REG

#define DDRPGCR1_CR_LVRVOLTAGESENSORCOUNT_REG                          (0x00001F04)
//Duplicate of DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_REG

#define DDRPGCR1_CR_SPARE_REG                                          (0x00001F08)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DDRPGCR1_CR_TLINETERMINATION_REG                               (0x00001F28)
//Duplicate of DDRPGTERMCR0_CR_TLINETERMINATION_REG

#define DDRPGCR2_CR_LVRVOLTAGESENSOR_REG                               (0x00001F80)
//Duplicate of DDRPGTERMCR0_CR_LVRVOLTAGESENSOR_REG

#define DDRPGCR2_CR_LVRVOLTAGESENSORCOUNT_REG                          (0x00001F84)
//Duplicate of DDRPGTERMCR0_CR_LVRVOLTAGESENSORCOUNT_REG

#define DDRPGCR2_CR_SPARE_REG                                          (0x00001F88)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DDRPGCR2_CR_TLINETERMINATION_REG                               (0x00001FA8)
//Duplicate of DDRPGTERMCR0_CR_TLINETERMINATION_REG



#pragma pack(pop)
#endif /* __MrcRegisterPtl1xxx_h__ */







