#ifndef __MrcRegisterPtl8xxx_h__
#define __MrcRegisterPtl8xxx_h__

/**
@file
  This file was automatically generated. Modify at your own risk.
  Note that no error checking is done in these functions so ensure that the correct values are passed.

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2023 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/

#pragma pack(push, 1)


#define DATADDR5CH0IL_CR_DDRDATADQRANK0LANE0_REG                       (0x00008600)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK0LANE1_REG                       (0x00008604)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK0LANE2_REG                       (0x00008608)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK0LANE3_REG                       (0x0000860C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK0LANE4_REG                       (0x00008610)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK0LANE5_REG                       (0x00008614)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK0LANE6_REG                       (0x00008618)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK0LANE7_REG                       (0x0000861C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK1LANE0_REG                       (0x00008620)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK1LANE1_REG                       (0x00008624)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK1LANE2_REG                       (0x00008628)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK1LANE3_REG                       (0x0000862C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK1LANE4_REG                       (0x00008630)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK1LANE5_REG                       (0x00008634)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK1LANE6_REG                       (0x00008638)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK1LANE7_REG                       (0x0000863C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQSRANK0_REG                           (0x00008640)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATADDR5CH0IL_CR_DDRDATADQSRANK1_REG                           (0x00008644)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATADDR5CH0IL_CR_TXCONTROL0RANK0_REG                           (0x00008648)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATADDR5CH0IL_CR_TXCONTROL0RANK1_REG                           (0x0000864C)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATADDR5CH0IL_CR_DDRCRDATAOFFSETTRAIN_REG                      (0x00008650)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETTRAIN_REG

#define DATADDR5CH0IL_CR_DDRCRDATACONTROL2_REG                         (0x00008654)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL2_REG

#define DATADDR5CH0IL_CR_DCCFSMCONTROL_REG                             (0x00008658)
//Duplicate of DATA0CH0_CR_DCCFSMCONTROL_REG

#define DATADDR5CH0IL_CR_DCCCALCCONTROL_REG                            (0x0000865C)
//Duplicate of DATA0CH0_CR_DCCCALCCONTROL_REG

#define DATADDR5CH0IL_CR_DCCLANETARGET_REG                             (0x00008660)
//Duplicate of DATA0CH0_CR_DCCLANETARGET_REG

#define DATADDR5CH0IL_CR_DDRCRRANKMUXDELAY_REG                         (0x00008664)
//Duplicate of DATA0CH0_CR_DDRCRRANKMUXDELAY_REG

#define DATADDR5CH0IL_CR_DDRCRDLLCONTROL0_REG                          (0x00008668)
//Duplicate of DATA0CH0_CR_DDRCRDLLCONTROL0_REG

#define DATADDR5CH0IL_CR_DCCPILUT0_REG                                 (0x0000866C)
//Duplicate of DATA0CH0_CR_DCCPILUT0_REG

#define DATADDR5CH0IL_CR_REFPICONTROL_REG                              (0x00008670)
//Duplicate of DATA0CH0_CR_REFPICONTROL_REG

#define DATADDR5CH0IL_CR_SPARE_REG                                     (0x00008674)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DATADDR5CH0IL_CR_DDRCRXTALKBIASCONTROL1_REG                    (0x00008678)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL1_REG

#define DATADDR5CH0IL_CR_DDRCRDQSWCKDLLCONTROL0_REG                    (0x0000867C)
//Duplicate of DATA0CH0_CR_DDRCRDQSWCKDLLCONTROL0_REG

#define DATADDR5CH0IL_CR_TERDCCCONTROL0_REG                            (0x00008680)
//Duplicate of DATA0CH0_CR_TERDCCCONTROL0_REG

#define DATADDR5CH0IL_CR_DDRCRXTALKBIASCONTROL2_REG                    (0x00008684)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL2_REG

#define DATADDR5CH0IL_CR_DDRCRXTALKBIASCONTROL3_REG                    (0x00008688)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL3_REG

#define DATADDR5CH0IL_CR_DDRCRXTALKBIASCONTROL4_REG                    (0x0000868C)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL4_REG

#define DATADDR5CH0IL_CR_DDRCRXTALKBIASCONTROL5_REG                    (0x00008690)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL5_REG

#define DATADDR5CH0IL_CR_DDRDATADQDCCRANK0LANE0TO4_REG                 (0x00008694)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE0TO4_REG

#define DATADDR5CH0IL_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG    (0x00008698)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG

#define DATADDR5CH0IL_CR_DDRDATADQDCCRANK1LANE2TO6_REG                 (0x0000869C)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE2TO6_REG

#define DATADDR5CH0IL_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG          (0x000086A0)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG

#define DATADDR5CH0IL_CR_SPARE1_REG                                    (0x000086A4)
//Duplicate of DATA0CH0_CR_SPARE1_REG

#define DATADDR5CH0IL_CR_VCCCLKCOMPRXOFFSET_REG                        (0x000086B4)
//Duplicate of DATA0CH0_CR_VCCCLKCOMPRXOFFSET_REG

#define DATADDR5CH0IL_CR_DDRCRWRRETRAININITRANK1_REG                   (0x000086CC)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATADDR5CH0IL_CR_DDRCRWRRETRAININITRANK0_REG                   (0x000086D0)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATADDR5CH0IL_CR_DDRCRRDRETRAININITRANK1_REG                   (0x000086DC)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATADDR5CH0IL_CR_DDRCRRDRETRAININITRANK0_REG                   (0x000086E0)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATADDR5CH0IL_CR_DDRCRRXCTLE_REG                               (0x000086E4)
//Duplicate of DATA0CH0_CR_DDRCRRXCTLE_REG

#define DATADDR5CH0IL_CR_RXCONTROL0RANK0_REG                           (0x000086E8)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATADDR5CH0IL_CR_RXCONTROL0RANK1_REG                           (0x000086EC)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATADDR5CH0IL_CR_DDRDQREPLICACTLE_REG                          (0x000086F0)
//Duplicate of DATA0CH0_CR_DDRDQREPLICACTLE_REG

#define DATADDR5CH0IL_CR_DDRCRDATAOFFSETCOMP_REG                       (0x000086F8)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETCOMP_REG

#define DATADDR5CH0IL_CR_DDRCRDATACONTROL0_REG                         (0x000086FC)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL0_REG

#define DATADDR5CH0IL_CR_DDRCRDATACONTROL1_REG                         (0x00008700)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL1_REG

#define DATADDR5CH0IL_CR_DDRCRDATACONTROL5_REG                         (0x00008704)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL5_REG

#define DATADDR5CH0IL_CR_DDRCRRXEQTAP01_REG                            (0x00008708)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP01_REG

#define DATADDR5CH0IL_CR_DDRCRRXEQTAP_REG                              (0x0000870C)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP_REG

#define DATADDR5CH0IL_CR_DDRCRCMDBUSTRAIN_REG                          (0x00008710)
//Duplicate of DATA0CH0_CR_DDRCRCMDBUSTRAIN_REG

#define DATADDR5CH0IL_CR_DDRCRDATATCOCONTROL0_REG                      (0x00008714)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL0_REG

#define DATADDR5CH0IL_CR_DDRCRDATATCOCONTROL1_REG                      (0x00008718)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL1_REG

#define DATADDR5CH0IL_CR_DDRCRWRRETRAINCONTROLSTATUS_REG               (0x0000871C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATADDR5CH0IL_CR_DDRCRRDRETRAINCONTROLSTATUS_REG               (0x00008720)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATADDR5CH0IL_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG              (0x00008724)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG

#define DATADDR5CH0IL_CR_DDRCRWRRETRAINDELTARANK_REG                   (0x00008728)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINDELTARANK_REG

#define DATADDR5CH0IL_CR_DDRCRRDRETRAINDELTARANK_REG                   (0x0000872C)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAINDELTARANK_REG

#define DATADDR5CH0IL_CR_DATATRAINFEEDBACK_REG                         (0x00008730)
//Duplicate of DATA0CH0_CR_DATATRAINFEEDBACK_REG

#define DATADDR5CH0IL_CR_DCCFSMSTATUS_REG                              (0x00008734)
//Duplicate of DATA0CH0_CR_DCCFSMSTATUS_REG

#define DATADDR5CH0IL_CR_DCCLANESTATUS0_REG                            (0x00008738)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS0_REG

#define DATADDR5CH0IL_CR_DCCLANESTATUS1_REG                            (0x0000873C)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS1_REG

#define DATADDR5CH0IL_CR_DCCLANESTATUS2_REG                            (0x00008740)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS2_REG

#define DATADDR5CH0IL_CR_DCCLANESTATUS3_REG                            (0x00008744)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS3_REG

#define DATADDR5CH0IL_CR_DDRCRMARGINMODECONTROL0_REG                   (0x00008748)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODECONTROL0_REG

#define DATADDR5CH0IL_CR_DDRCRMARGINMODEDEBUGMSB0_REG                  (0x0000874C)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATADDR5CH0IL_CR_DDRCRMARGINMODEDEBUGLSB0_REG                  (0x00008750)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATADDR5CH0IL_CR_DDRCRDLLSTATUS_REG                            (0x00008754)
//Duplicate of DATA0CH0_CR_DDRCRDLLSTATUS_REG

#define DATADDR5CH0IL_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG                (0x00008758)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG

#define DATADDR5CH0IL_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG           (0x0000875C)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG

#define DATADDR5CH0IL_CR_DDRCRCOMPDQSDELAY_REG                         (0x00008760)
//Duplicate of DATA0CH0_CR_DDRCRCOMPDQSDELAY_REG

#define DATADDR5CH0IL_CR_DDRCRADC_REG                                  (0x00008764)
//Duplicate of DATA0CH0_CR_DDRCRADC_REG

#define DATADDR5CH0IL_CR_REFPIFSMCONTROL_REG                           (0x00008768)
//Duplicate of DATA0CH0_CR_REFPIFSMCONTROL_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK0LANE8_REG                       (0x0000876C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRDATADQRANK1LANE8_REG                       (0x00008770)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH0IL_CR_DDRCRDATAVREFPERBIT012_REG                    (0x00008774)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT012_REG

#define DATADDR5CH0IL_CR_DDRCRDATAVREFPERBIT345_REG                    (0x00008778)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT345_REG

#define DATADDR5CH0IL_CR_DDRCRDATAVREFPERBIT67DBI_REG                  (0x0000877C)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK0LANE0_REG                       (0x00008780)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK0LANE1_REG                       (0x00008784)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK0LANE2_REG                       (0x00008788)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK0LANE3_REG                       (0x0000878C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK0LANE4_REG                       (0x00008790)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK0LANE5_REG                       (0x00008794)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK0LANE6_REG                       (0x00008798)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK0LANE7_REG                       (0x0000879C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK1LANE0_REG                       (0x000087A0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK1LANE1_REG                       (0x000087A4)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK1LANE2_REG                       (0x000087A8)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK1LANE3_REG                       (0x000087AC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK1LANE4_REG                       (0x000087B0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK1LANE5_REG                       (0x000087B4)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK1LANE6_REG                       (0x000087B8)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK1LANE7_REG                       (0x000087BC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQSRANK0_REG                           (0x000087C0)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATADDR5CH1IL_CR_DDRDATADQSRANK1_REG                           (0x000087C4)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATADDR5CH1IL_CR_TXCONTROL0RANK0_REG                           (0x000087C8)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATADDR5CH1IL_CR_TXCONTROL0RANK1_REG                           (0x000087CC)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATADDR5CH1IL_CR_DDRCRDATAOFFSETTRAIN_REG                      (0x000087D0)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETTRAIN_REG

#define DATADDR5CH1IL_CR_DDRCRDATACONTROL2_REG                         (0x000087D4)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL2_REG

#define DATADDR5CH1IL_CR_DCCFSMCONTROL_REG                             (0x000087D8)
//Duplicate of DATA0CH0_CR_DCCFSMCONTROL_REG

#define DATADDR5CH1IL_CR_DCCCALCCONTROL_REG                            (0x000087DC)
//Duplicate of DATA0CH0_CR_DCCCALCCONTROL_REG

#define DATADDR5CH1IL_CR_DCCLANETARGET_REG                             (0x000087E0)
//Duplicate of DATA0CH0_CR_DCCLANETARGET_REG

#define DATADDR5CH1IL_CR_DDRCRRANKMUXDELAY_REG                         (0x000087E4)
//Duplicate of DATA0CH0_CR_DDRCRRANKMUXDELAY_REG

#define DATADDR5CH1IL_CR_DDRCRDLLCONTROL0_REG                          (0x000087E8)
//Duplicate of DATA0CH0_CR_DDRCRDLLCONTROL0_REG

#define DATADDR5CH1IL_CR_DCCPILUT0_REG                                 (0x000087EC)
//Duplicate of DATA0CH0_CR_DCCPILUT0_REG

#define DATADDR5CH1IL_CR_REFPICONTROL_REG                              (0x000087F0)
//Duplicate of DATA0CH0_CR_REFPICONTROL_REG

#define DATADDR5CH1IL_CR_SPARE_REG                                     (0x000087F4)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DATADDR5CH1IL_CR_DDRCRXTALKBIASCONTROL1_REG                    (0x000087F8)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL1_REG

#define DATADDR5CH1IL_CR_DDRCRDQSWCKDLLCONTROL0_REG                    (0x000087FC)
//Duplicate of DATA0CH0_CR_DDRCRDQSWCKDLLCONTROL0_REG

#define DATADDR5CH1IL_CR_TERDCCCONTROL0_REG                            (0x00008800)
//Duplicate of DATA0CH0_CR_TERDCCCONTROL0_REG

#define DATADDR5CH1IL_CR_DDRCRXTALKBIASCONTROL2_REG                    (0x00008804)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL2_REG

#define DATADDR5CH1IL_CR_DDRCRXTALKBIASCONTROL3_REG                    (0x00008808)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL3_REG

#define DATADDR5CH1IL_CR_DDRCRXTALKBIASCONTROL4_REG                    (0x0000880C)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL4_REG

#define DATADDR5CH1IL_CR_DDRCRXTALKBIASCONTROL5_REG                    (0x00008810)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL5_REG

#define DATADDR5CH1IL_CR_DDRDATADQDCCRANK0LANE0TO4_REG                 (0x00008814)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE0TO4_REG

#define DATADDR5CH1IL_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG    (0x00008818)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG

#define DATADDR5CH1IL_CR_DDRDATADQDCCRANK1LANE2TO6_REG                 (0x0000881C)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE2TO6_REG

#define DATADDR5CH1IL_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG          (0x00008820)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG

#define DATADDR5CH1IL_CR_SPARE1_REG                                    (0x00008824)
//Duplicate of DATA0CH0_CR_SPARE1_REG

#define DATADDR5CH1IL_CR_VCCCLKCOMPRXOFFSET_REG                        (0x00008834)
//Duplicate of DATA0CH0_CR_VCCCLKCOMPRXOFFSET_REG

#define DATADDR5CH1IL_CR_DDRCRWRRETRAININITRANK1_REG                   (0x0000884C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATADDR5CH1IL_CR_DDRCRWRRETRAININITRANK0_REG                   (0x00008850)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATADDR5CH1IL_CR_DDRCRRDRETRAININITRANK1_REG                   (0x0000885C)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATADDR5CH1IL_CR_DDRCRRDRETRAININITRANK0_REG                   (0x00008860)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATADDR5CH1IL_CR_DDRCRRXCTLE_REG                               (0x00008864)
//Duplicate of DATA0CH0_CR_DDRCRRXCTLE_REG

#define DATADDR5CH1IL_CR_RXCONTROL0RANK0_REG                           (0x00008868)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATADDR5CH1IL_CR_RXCONTROL0RANK1_REG                           (0x0000886C)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATADDR5CH1IL_CR_DDRDQREPLICACTLE_REG                          (0x00008870)
//Duplicate of DATA0CH0_CR_DDRDQREPLICACTLE_REG

#define DATADDR5CH1IL_CR_DDRCRDATAOFFSETCOMP_REG                       (0x00008878)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETCOMP_REG

#define DATADDR5CH1IL_CR_DDRCRDATACONTROL0_REG                         (0x0000887C)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL0_REG

#define DATADDR5CH1IL_CR_DDRCRDATACONTROL1_REG                         (0x00008880)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL1_REG

#define DATADDR5CH1IL_CR_DDRCRDATACONTROL5_REG                         (0x00008884)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL5_REG

#define DATADDR5CH1IL_CR_DDRCRRXEQTAP01_REG                            (0x00008888)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP01_REG

#define DATADDR5CH1IL_CR_DDRCRRXEQTAP_REG                              (0x0000888C)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP_REG

#define DATADDR5CH1IL_CR_DDRCRCMDBUSTRAIN_REG                          (0x00008890)
//Duplicate of DATA0CH0_CR_DDRCRCMDBUSTRAIN_REG

#define DATADDR5CH1IL_CR_DDRCRDATATCOCONTROL0_REG                      (0x00008894)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL0_REG

#define DATADDR5CH1IL_CR_DDRCRDATATCOCONTROL1_REG                      (0x00008898)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL1_REG

#define DATADDR5CH1IL_CR_DDRCRWRRETRAINCONTROLSTATUS_REG               (0x0000889C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATADDR5CH1IL_CR_DDRCRRDRETRAINCONTROLSTATUS_REG               (0x000088A0)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATADDR5CH1IL_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG              (0x000088A4)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG

#define DATADDR5CH1IL_CR_DDRCRWRRETRAINDELTARANK_REG                   (0x000088A8)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINDELTARANK_REG

#define DATADDR5CH1IL_CR_DDRCRRDRETRAINDELTARANK_REG                   (0x000088AC)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAINDELTARANK_REG

#define DATADDR5CH1IL_CR_DATATRAINFEEDBACK_REG                         (0x000088B0)
//Duplicate of DATA0CH0_CR_DATATRAINFEEDBACK_REG

#define DATADDR5CH1IL_CR_DCCFSMSTATUS_REG                              (0x000088B4)
//Duplicate of DATA0CH0_CR_DCCFSMSTATUS_REG

#define DATADDR5CH1IL_CR_DCCLANESTATUS0_REG                            (0x000088B8)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS0_REG

#define DATADDR5CH1IL_CR_DCCLANESTATUS1_REG                            (0x000088BC)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS1_REG

#define DATADDR5CH1IL_CR_DCCLANESTATUS2_REG                            (0x000088C0)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS2_REG

#define DATADDR5CH1IL_CR_DCCLANESTATUS3_REG                            (0x000088C4)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS3_REG

#define DATADDR5CH1IL_CR_DDRCRMARGINMODECONTROL0_REG                   (0x000088C8)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODECONTROL0_REG

#define DATADDR5CH1IL_CR_DDRCRMARGINMODEDEBUGMSB0_REG                  (0x000088CC)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATADDR5CH1IL_CR_DDRCRMARGINMODEDEBUGLSB0_REG                  (0x000088D0)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATADDR5CH1IL_CR_DDRCRDLLSTATUS_REG                            (0x000088D4)
//Duplicate of DATA0CH0_CR_DDRCRDLLSTATUS_REG

#define DATADDR5CH1IL_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG                (0x000088D8)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG

#define DATADDR5CH1IL_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG           (0x000088DC)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG

#define DATADDR5CH1IL_CR_DDRCRCOMPDQSDELAY_REG                         (0x000088E0)
//Duplicate of DATA0CH0_CR_DDRCRCOMPDQSDELAY_REG

#define DATADDR5CH1IL_CR_DDRCRADC_REG                                  (0x000088E4)
//Duplicate of DATA0CH0_CR_DDRCRADC_REG

#define DATADDR5CH1IL_CR_REFPIFSMCONTROL_REG                           (0x000088E8)
//Duplicate of DATA0CH0_CR_REFPIFSMCONTROL_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK0LANE8_REG                       (0x000088EC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRDATADQRANK1LANE8_REG                       (0x000088F0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH1IL_CR_DDRCRDATAVREFPERBIT012_REG                    (0x000088F4)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT012_REG

#define DATADDR5CH1IL_CR_DDRCRDATAVREFPERBIT345_REG                    (0x000088F8)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT345_REG

#define DATADDR5CH1IL_CR_DDRCRDATAVREFPERBIT67DBI_REG                  (0x000088FC)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK0LANE0_REG                       (0x00008900)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK0LANE1_REG                       (0x00008904)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK0LANE2_REG                       (0x00008908)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK0LANE3_REG                       (0x0000890C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK0LANE4_REG                       (0x00008910)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK0LANE5_REG                       (0x00008914)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK0LANE6_REG                       (0x00008918)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK0LANE7_REG                       (0x0000891C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK1LANE0_REG                       (0x00008920)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK1LANE1_REG                       (0x00008924)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK1LANE2_REG                       (0x00008928)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK1LANE3_REG                       (0x0000892C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK1LANE4_REG                       (0x00008930)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK1LANE5_REG                       (0x00008934)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK1LANE6_REG                       (0x00008938)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK1LANE7_REG                       (0x0000893C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQSRANK0_REG                           (0x00008940)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATADDR5CH2IL_CR_DDRDATADQSRANK1_REG                           (0x00008944)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATADDR5CH2IL_CR_TXCONTROL0RANK0_REG                           (0x00008948)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATADDR5CH2IL_CR_TXCONTROL0RANK1_REG                           (0x0000894C)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATADDR5CH2IL_CR_DDRCRDATAOFFSETTRAIN_REG                      (0x00008950)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETTRAIN_REG

#define DATADDR5CH2IL_CR_DDRCRDATACONTROL2_REG                         (0x00008954)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL2_REG

#define DATADDR5CH2IL_CR_DCCFSMCONTROL_REG                             (0x00008958)
//Duplicate of DATA0CH0_CR_DCCFSMCONTROL_REG

#define DATADDR5CH2IL_CR_DCCCALCCONTROL_REG                            (0x0000895C)
//Duplicate of DATA0CH0_CR_DCCCALCCONTROL_REG

#define DATADDR5CH2IL_CR_DCCLANETARGET_REG                             (0x00008960)
//Duplicate of DATA0CH0_CR_DCCLANETARGET_REG

#define DATADDR5CH2IL_CR_DDRCRRANKMUXDELAY_REG                         (0x00008964)
//Duplicate of DATA0CH0_CR_DDRCRRANKMUXDELAY_REG

#define DATADDR5CH2IL_CR_DDRCRDLLCONTROL0_REG                          (0x00008968)
//Duplicate of DATA0CH0_CR_DDRCRDLLCONTROL0_REG

#define DATADDR5CH2IL_CR_DCCPILUT0_REG                                 (0x0000896C)
//Duplicate of DATA0CH0_CR_DCCPILUT0_REG

#define DATADDR5CH2IL_CR_REFPICONTROL_REG                              (0x00008970)
//Duplicate of DATA0CH0_CR_REFPICONTROL_REG

#define DATADDR5CH2IL_CR_SPARE_REG                                     (0x00008974)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DATADDR5CH2IL_CR_DDRCRXTALKBIASCONTROL1_REG                    (0x00008978)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL1_REG

#define DATADDR5CH2IL_CR_DDRCRDQSWCKDLLCONTROL0_REG                    (0x0000897C)
//Duplicate of DATA0CH0_CR_DDRCRDQSWCKDLLCONTROL0_REG

#define DATADDR5CH2IL_CR_TERDCCCONTROL0_REG                            (0x00008980)
//Duplicate of DATA0CH0_CR_TERDCCCONTROL0_REG

#define DATADDR5CH2IL_CR_DDRCRXTALKBIASCONTROL2_REG                    (0x00008984)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL2_REG

#define DATADDR5CH2IL_CR_DDRCRXTALKBIASCONTROL3_REG                    (0x00008988)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL3_REG

#define DATADDR5CH2IL_CR_DDRCRXTALKBIASCONTROL4_REG                    (0x0000898C)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL4_REG

#define DATADDR5CH2IL_CR_DDRCRXTALKBIASCONTROL5_REG                    (0x00008990)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL5_REG

#define DATADDR5CH2IL_CR_DDRDATADQDCCRANK0LANE0TO4_REG                 (0x00008994)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE0TO4_REG

#define DATADDR5CH2IL_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG    (0x00008998)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG

#define DATADDR5CH2IL_CR_DDRDATADQDCCRANK1LANE2TO6_REG                 (0x0000899C)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE2TO6_REG

#define DATADDR5CH2IL_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG          (0x000089A0)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG

#define DATADDR5CH2IL_CR_SPARE1_REG                                    (0x000089A4)
//Duplicate of DATA0CH0_CR_SPARE1_REG

#define DATADDR5CH2IL_CR_VCCCLKCOMPRXOFFSET_REG                        (0x000089B4)
//Duplicate of DATA0CH0_CR_VCCCLKCOMPRXOFFSET_REG

#define DATADDR5CH2IL_CR_DDRCRWRRETRAININITRANK1_REG                   (0x000089CC)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATADDR5CH2IL_CR_DDRCRWRRETRAININITRANK0_REG                   (0x000089D0)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATADDR5CH2IL_CR_DDRCRRDRETRAININITRANK1_REG                   (0x000089DC)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATADDR5CH2IL_CR_DDRCRRDRETRAININITRANK0_REG                   (0x000089E0)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATADDR5CH2IL_CR_DDRCRRXCTLE_REG                               (0x000089E4)
//Duplicate of DATA0CH0_CR_DDRCRRXCTLE_REG

#define DATADDR5CH2IL_CR_RXCONTROL0RANK0_REG                           (0x000089E8)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATADDR5CH2IL_CR_RXCONTROL0RANK1_REG                           (0x000089EC)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATADDR5CH2IL_CR_DDRDQREPLICACTLE_REG                          (0x000089F0)
//Duplicate of DATA0CH0_CR_DDRDQREPLICACTLE_REG

#define DATADDR5CH2IL_CR_DDRCRDATAOFFSETCOMP_REG                       (0x000089F8)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETCOMP_REG

#define DATADDR5CH2IL_CR_DDRCRDATACONTROL0_REG                         (0x000089FC)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL0_REG

#define DATADDR5CH2IL_CR_DDRCRDATACONTROL1_REG                         (0x00008A00)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL1_REG

#define DATADDR5CH2IL_CR_DDRCRDATACONTROL5_REG                         (0x00008A04)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL5_REG

#define DATADDR5CH2IL_CR_DDRCRRXEQTAP01_REG                            (0x00008A08)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP01_REG

#define DATADDR5CH2IL_CR_DDRCRRXEQTAP_REG                              (0x00008A0C)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP_REG

#define DATADDR5CH2IL_CR_DDRCRCMDBUSTRAIN_REG                          (0x00008A10)
//Duplicate of DATA0CH0_CR_DDRCRCMDBUSTRAIN_REG

#define DATADDR5CH2IL_CR_DDRCRDATATCOCONTROL0_REG                      (0x00008A14)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL0_REG

#define DATADDR5CH2IL_CR_DDRCRDATATCOCONTROL1_REG                      (0x00008A18)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL1_REG

#define DATADDR5CH2IL_CR_DDRCRWRRETRAINCONTROLSTATUS_REG               (0x00008A1C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATADDR5CH2IL_CR_DDRCRRDRETRAINCONTROLSTATUS_REG               (0x00008A20)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATADDR5CH2IL_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG              (0x00008A24)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG

#define DATADDR5CH2IL_CR_DDRCRWRRETRAINDELTARANK_REG                   (0x00008A28)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINDELTARANK_REG

#define DATADDR5CH2IL_CR_DDRCRRDRETRAINDELTARANK_REG                   (0x00008A2C)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAINDELTARANK_REG

#define DATADDR5CH2IL_CR_DATATRAINFEEDBACK_REG                         (0x00008A30)
//Duplicate of DATA0CH0_CR_DATATRAINFEEDBACK_REG

#define DATADDR5CH2IL_CR_DCCFSMSTATUS_REG                              (0x00008A34)
//Duplicate of DATA0CH0_CR_DCCFSMSTATUS_REG

#define DATADDR5CH2IL_CR_DCCLANESTATUS0_REG                            (0x00008A38)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS0_REG

#define DATADDR5CH2IL_CR_DCCLANESTATUS1_REG                            (0x00008A3C)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS1_REG

#define DATADDR5CH2IL_CR_DCCLANESTATUS2_REG                            (0x00008A40)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS2_REG

#define DATADDR5CH2IL_CR_DCCLANESTATUS3_REG                            (0x00008A44)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS3_REG

#define DATADDR5CH2IL_CR_DDRCRMARGINMODECONTROL0_REG                   (0x00008A48)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODECONTROL0_REG

#define DATADDR5CH2IL_CR_DDRCRMARGINMODEDEBUGMSB0_REG                  (0x00008A4C)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATADDR5CH2IL_CR_DDRCRMARGINMODEDEBUGLSB0_REG                  (0x00008A50)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATADDR5CH2IL_CR_DDRCRDLLSTATUS_REG                            (0x00008A54)
//Duplicate of DATA0CH0_CR_DDRCRDLLSTATUS_REG

#define DATADDR5CH2IL_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG                (0x00008A58)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG

#define DATADDR5CH2IL_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG           (0x00008A5C)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG

#define DATADDR5CH2IL_CR_DDRCRCOMPDQSDELAY_REG                         (0x00008A60)
//Duplicate of DATA0CH0_CR_DDRCRCOMPDQSDELAY_REG

#define DATADDR5CH2IL_CR_DDRCRADC_REG                                  (0x00008A64)
//Duplicate of DATA0CH0_CR_DDRCRADC_REG

#define DATADDR5CH2IL_CR_REFPIFSMCONTROL_REG                           (0x00008A68)
//Duplicate of DATA0CH0_CR_REFPIFSMCONTROL_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK0LANE8_REG                       (0x00008A6C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRDATADQRANK1LANE8_REG                       (0x00008A70)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH2IL_CR_DDRCRDATAVREFPERBIT012_REG                    (0x00008A74)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT012_REG

#define DATADDR5CH2IL_CR_DDRCRDATAVREFPERBIT345_REG                    (0x00008A78)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT345_REG

#define DATADDR5CH2IL_CR_DDRCRDATAVREFPERBIT67DBI_REG                  (0x00008A7C)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK0LANE0_REG                       (0x00008A80)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK0LANE1_REG                       (0x00008A84)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK0LANE2_REG                       (0x00008A88)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK0LANE3_REG                       (0x00008A8C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK0LANE4_REG                       (0x00008A90)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK0LANE5_REG                       (0x00008A94)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK0LANE6_REG                       (0x00008A98)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK0LANE7_REG                       (0x00008A9C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK1LANE0_REG                       (0x00008AA0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK1LANE1_REG                       (0x00008AA4)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK1LANE2_REG                       (0x00008AA8)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK1LANE3_REG                       (0x00008AAC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK1LANE4_REG                       (0x00008AB0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK1LANE5_REG                       (0x00008AB4)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK1LANE6_REG                       (0x00008AB8)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK1LANE7_REG                       (0x00008ABC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQSRANK0_REG                           (0x00008AC0)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATADDR5CH3IL_CR_DDRDATADQSRANK1_REG                           (0x00008AC4)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATADDR5CH3IL_CR_TXCONTROL0RANK0_REG                           (0x00008AC8)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATADDR5CH3IL_CR_TXCONTROL0RANK1_REG                           (0x00008ACC)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATADDR5CH3IL_CR_DDRCRDATAOFFSETTRAIN_REG                      (0x00008AD0)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETTRAIN_REG

#define DATADDR5CH3IL_CR_DDRCRDATACONTROL2_REG                         (0x00008AD4)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL2_REG

#define DATADDR5CH3IL_CR_DCCFSMCONTROL_REG                             (0x00008AD8)
//Duplicate of DATA0CH0_CR_DCCFSMCONTROL_REG

#define DATADDR5CH3IL_CR_DCCCALCCONTROL_REG                            (0x00008ADC)
//Duplicate of DATA0CH0_CR_DCCCALCCONTROL_REG

#define DATADDR5CH3IL_CR_DCCLANETARGET_REG                             (0x00008AE0)
//Duplicate of DATA0CH0_CR_DCCLANETARGET_REG

#define DATADDR5CH3IL_CR_DDRCRRANKMUXDELAY_REG                         (0x00008AE4)
//Duplicate of DATA0CH0_CR_DDRCRRANKMUXDELAY_REG

#define DATADDR5CH3IL_CR_DDRCRDLLCONTROL0_REG                          (0x00008AE8)
//Duplicate of DATA0CH0_CR_DDRCRDLLCONTROL0_REG

#define DATADDR5CH3IL_CR_DCCPILUT0_REG                                 (0x00008AEC)
//Duplicate of DATA0CH0_CR_DCCPILUT0_REG

#define DATADDR5CH3IL_CR_REFPICONTROL_REG                              (0x00008AF0)
//Duplicate of DATA0CH0_CR_REFPICONTROL_REG

#define DATADDR5CH3IL_CR_SPARE_REG                                     (0x00008AF4)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DATADDR5CH3IL_CR_DDRCRXTALKBIASCONTROL1_REG                    (0x00008AF8)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL1_REG

#define DATADDR5CH3IL_CR_DDRCRDQSWCKDLLCONTROL0_REG                    (0x00008AFC)
//Duplicate of DATA0CH0_CR_DDRCRDQSWCKDLLCONTROL0_REG

#define DATADDR5CH3IL_CR_TERDCCCONTROL0_REG                            (0x00008B00)
//Duplicate of DATA0CH0_CR_TERDCCCONTROL0_REG

#define DATADDR5CH3IL_CR_DDRCRXTALKBIASCONTROL2_REG                    (0x00008B04)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL2_REG

#define DATADDR5CH3IL_CR_DDRCRXTALKBIASCONTROL3_REG                    (0x00008B08)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL3_REG

#define DATADDR5CH3IL_CR_DDRCRXTALKBIASCONTROL4_REG                    (0x00008B0C)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL4_REG

#define DATADDR5CH3IL_CR_DDRCRXTALKBIASCONTROL5_REG                    (0x00008B10)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL5_REG

#define DATADDR5CH3IL_CR_DDRDATADQDCCRANK0LANE0TO4_REG                 (0x00008B14)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE0TO4_REG

#define DATADDR5CH3IL_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG    (0x00008B18)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG

#define DATADDR5CH3IL_CR_DDRDATADQDCCRANK1LANE2TO6_REG                 (0x00008B1C)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE2TO6_REG

#define DATADDR5CH3IL_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG          (0x00008B20)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG

#define DATADDR5CH3IL_CR_SPARE1_REG                                    (0x00008B24)
//Duplicate of DATA0CH0_CR_SPARE1_REG

#define DATADDR5CH3IL_CR_VCCCLKCOMPRXOFFSET_REG                        (0x00008B34)
//Duplicate of DATA0CH0_CR_VCCCLKCOMPRXOFFSET_REG

#define DATADDR5CH3IL_CR_DDRCRWRRETRAININITRANK1_REG                   (0x00008B4C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATADDR5CH3IL_CR_DDRCRWRRETRAININITRANK0_REG                   (0x00008B50)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATADDR5CH3IL_CR_DDRCRRDRETRAININITRANK1_REG                   (0x00008B5C)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATADDR5CH3IL_CR_DDRCRRDRETRAININITRANK0_REG                   (0x00008B60)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATADDR5CH3IL_CR_DDRCRRXCTLE_REG                               (0x00008B64)
//Duplicate of DATA0CH0_CR_DDRCRRXCTLE_REG

#define DATADDR5CH3IL_CR_RXCONTROL0RANK0_REG                           (0x00008B68)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATADDR5CH3IL_CR_RXCONTROL0RANK1_REG                           (0x00008B6C)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATADDR5CH3IL_CR_DDRDQREPLICACTLE_REG                          (0x00008B70)
//Duplicate of DATA0CH0_CR_DDRDQREPLICACTLE_REG

#define DATADDR5CH3IL_CR_DDRCRDATAOFFSETCOMP_REG                       (0x00008B78)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETCOMP_REG

#define DATADDR5CH3IL_CR_DDRCRDATACONTROL0_REG                         (0x00008B7C)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL0_REG

#define DATADDR5CH3IL_CR_DDRCRDATACONTROL1_REG                         (0x00008B80)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL1_REG

#define DATADDR5CH3IL_CR_DDRCRDATACONTROL5_REG                         (0x00008B84)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL5_REG

#define DATADDR5CH3IL_CR_DDRCRRXEQTAP01_REG                            (0x00008B88)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP01_REG

#define DATADDR5CH3IL_CR_DDRCRRXEQTAP_REG                              (0x00008B8C)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP_REG

#define DATADDR5CH3IL_CR_DDRCRCMDBUSTRAIN_REG                          (0x00008B90)
//Duplicate of DATA0CH0_CR_DDRCRCMDBUSTRAIN_REG

#define DATADDR5CH3IL_CR_DDRCRDATATCOCONTROL0_REG                      (0x00008B94)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL0_REG

#define DATADDR5CH3IL_CR_DDRCRDATATCOCONTROL1_REG                      (0x00008B98)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL1_REG

#define DATADDR5CH3IL_CR_DDRCRWRRETRAINCONTROLSTATUS_REG               (0x00008B9C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATADDR5CH3IL_CR_DDRCRRDRETRAINCONTROLSTATUS_REG               (0x00008BA0)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATADDR5CH3IL_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG              (0x00008BA4)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG

#define DATADDR5CH3IL_CR_DDRCRWRRETRAINDELTARANK_REG                   (0x00008BA8)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINDELTARANK_REG

#define DATADDR5CH3IL_CR_DDRCRRDRETRAINDELTARANK_REG                   (0x00008BAC)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAINDELTARANK_REG

#define DATADDR5CH3IL_CR_DATATRAINFEEDBACK_REG                         (0x00008BB0)
//Duplicate of DATA0CH0_CR_DATATRAINFEEDBACK_REG

#define DATADDR5CH3IL_CR_DCCFSMSTATUS_REG                              (0x00008BB4)
//Duplicate of DATA0CH0_CR_DCCFSMSTATUS_REG

#define DATADDR5CH3IL_CR_DCCLANESTATUS0_REG                            (0x00008BB8)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS0_REG

#define DATADDR5CH3IL_CR_DCCLANESTATUS1_REG                            (0x00008BBC)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS1_REG

#define DATADDR5CH3IL_CR_DCCLANESTATUS2_REG                            (0x00008BC0)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS2_REG

#define DATADDR5CH3IL_CR_DCCLANESTATUS3_REG                            (0x00008BC4)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS3_REG

#define DATADDR5CH3IL_CR_DDRCRMARGINMODECONTROL0_REG                   (0x00008BC8)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODECONTROL0_REG

#define DATADDR5CH3IL_CR_DDRCRMARGINMODEDEBUGMSB0_REG                  (0x00008BCC)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATADDR5CH3IL_CR_DDRCRMARGINMODEDEBUGLSB0_REG                  (0x00008BD0)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATADDR5CH3IL_CR_DDRCRDLLSTATUS_REG                            (0x00008BD4)
//Duplicate of DATA0CH0_CR_DDRCRDLLSTATUS_REG

#define DATADDR5CH3IL_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG                (0x00008BD8)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG

#define DATADDR5CH3IL_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG           (0x00008BDC)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG

#define DATADDR5CH3IL_CR_DDRCRCOMPDQSDELAY_REG                         (0x00008BE0)
//Duplicate of DATA0CH0_CR_DDRCRCOMPDQSDELAY_REG

#define DATADDR5CH3IL_CR_DDRCRADC_REG                                  (0x00008BE4)
//Duplicate of DATA0CH0_CR_DDRCRADC_REG

#define DATADDR5CH3IL_CR_REFPIFSMCONTROL_REG                           (0x00008BE8)
//Duplicate of DATA0CH0_CR_REFPIFSMCONTROL_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK0LANE8_REG                       (0x00008BEC)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRDATADQRANK1LANE8_REG                       (0x00008BF0)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATADDR5CH3IL_CR_DDRCRDATAVREFPERBIT012_REG                    (0x00008BF4)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT012_REG

#define DATADDR5CH3IL_CR_DDRCRDATAVREFPERBIT345_REG                    (0x00008BF8)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT345_REG

#define DATADDR5CH3IL_CR_DDRCRDATAVREFPERBIT67DBI_REG                  (0x00008BFC)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG

#define DATA_CR_DDRDATADQRANK0LANE0_REG                                (0x00008C00)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK0LANE1_REG                                (0x00008C04)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK0LANE2_REG                                (0x00008C08)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK0LANE3_REG                                (0x00008C0C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK0LANE4_REG                                (0x00008C10)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK0LANE5_REG                                (0x00008C14)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK0LANE6_REG                                (0x00008C18)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK0LANE7_REG                                (0x00008C1C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK1LANE0_REG                                (0x00008C20)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK1LANE1_REG                                (0x00008C24)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK1LANE2_REG                                (0x00008C28)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK1LANE3_REG                                (0x00008C2C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK1LANE4_REG                                (0x00008C30)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK1LANE5_REG                                (0x00008C34)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK1LANE6_REG                                (0x00008C38)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK1LANE7_REG                                (0x00008C3C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQSRANK0_REG                                    (0x00008C40)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATA_CR_DDRDATADQSRANK1_REG                                    (0x00008C44)
//Duplicate of DATA0CH0_CR_DDRDATADQSRANK0_REG

#define DATA_CR_TXCONTROL0RANK0_REG                                    (0x00008C48)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATA_CR_TXCONTROL0RANK1_REG                                    (0x00008C4C)
//Duplicate of DATA0CH0_CR_TXCONTROL0RANK0_REG

#define DATA_CR_DDRCRDATAOFFSETTRAIN_REG                               (0x00008C50)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETTRAIN_REG

#define DATA_CR_DDRCRDATACONTROL2_REG                                  (0x00008C54)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL2_REG

#define DATA_CR_DCCFSMCONTROL_REG                                      (0x00008C58)
//Duplicate of DATA0CH0_CR_DCCFSMCONTROL_REG

#define DATA_CR_DCCCALCCONTROL_REG                                     (0x00008C5C)
//Duplicate of DATA0CH0_CR_DCCCALCCONTROL_REG

#define DATA_CR_DCCLANETARGET_REG                                      (0x00008C60)
//Duplicate of DATA0CH0_CR_DCCLANETARGET_REG

#define DATA_CR_DDRCRRANKMUXDELAY_REG                                  (0x00008C64)
//Duplicate of DATA0CH0_CR_DDRCRRANKMUXDELAY_REG

#define DATA_CR_DDRCRDLLCONTROL0_REG                                   (0x00008C68)
//Duplicate of DATA0CH0_CR_DDRCRDLLCONTROL0_REG

#define DATA_CR_DCCPILUT0_REG                                          (0x00008C6C)
//Duplicate of DATA0CH0_CR_DCCPILUT0_REG

#define DATA_CR_REFPICONTROL_REG                                       (0x00008C70)
//Duplicate of DATA0CH0_CR_REFPICONTROL_REG

#define DATA_CR_SPARE_REG                                              (0x00008C74)
//Duplicate of DATA0CH0_CR_SPARE_REG

#define DATA_CR_DDRCRXTALKBIASCONTROL1_REG                             (0x00008C78)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL1_REG

#define DATA_CR_DDRCRDQSWCKDLLCONTROL0_REG                             (0x00008C7C)
//Duplicate of DATA0CH0_CR_DDRCRDQSWCKDLLCONTROL0_REG

#define DATA_CR_TERDCCCONTROL0_REG                                     (0x00008C80)
//Duplicate of DATA0CH0_CR_TERDCCCONTROL0_REG

#define DATA_CR_DDRCRXTALKBIASCONTROL2_REG                             (0x00008C84)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL2_REG

#define DATA_CR_DDRCRXTALKBIASCONTROL3_REG                             (0x00008C88)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL3_REG

#define DATA_CR_DDRCRXTALKBIASCONTROL4_REG                             (0x00008C8C)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL4_REG

#define DATA_CR_DDRCRXTALKBIASCONTROL5_REG                             (0x00008C90)
//Duplicate of DATA0CH0_CR_DDRCRXTALKBIASCONTROL5_REG

#define DATA_CR_DDRDATADQDCCRANK0LANE0TO4_REG                          (0x00008C94)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE0TO4_REG

#define DATA_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG             (0x00008C98)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK0LANE5TO7RANK1LANE0TO1_REG

#define DATA_CR_DDRDATADQDCCRANK1LANE2TO6_REG                          (0x00008C9C)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE2TO6_REG

#define DATA_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG                   (0x00008CA0)
//Duplicate of DATA0CH0_CR_DDRDATADQDCCRANK1LANE7DQSDBIR0R1_REG

#define DATA_CR_SPARE1_REG                                             (0x00008CA4)
//Duplicate of DATA0CH0_CR_SPARE1_REG

#define DATA_CR_VCCCLKCOMPRXOFFSET_REG                                 (0x00008CB4)
//Duplicate of DATA0CH0_CR_VCCCLKCOMPRXOFFSET_REG

#define DATA_CR_DDRCRWRRETRAININITRANK1_REG                            (0x00008CCC)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATA_CR_DDRCRWRRETRAININITRANK0_REG                            (0x00008CD0)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAININITRANK1_REG

#define DATA_CR_DDRCRRDRETRAININITRANK1_REG                            (0x00008CDC)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATA_CR_DDRCRRDRETRAININITRANK0_REG                            (0x00008CE0)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAININITRANK1_REG

#define DATA_CR_DDRCRRXCTLE_REG                                        (0x00008CE4)
//Duplicate of DATA0CH0_CR_DDRCRRXCTLE_REG

#define DATA_CR_RXCONTROL0RANK0_REG                                    (0x00008CE8)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATA_CR_RXCONTROL0RANK1_REG                                    (0x00008CEC)
//Duplicate of DATA0CH0_CR_RXCONTROL0RANK0_REG

#define DATA_CR_DDRDQREPLICACTLE_REG                                   (0x00008CF0)
//Duplicate of DATA0CH0_CR_DDRDQREPLICACTLE_REG

#define DATA_CR_DDRCRDATAOFFSETCOMP_REG                                (0x00008CF8)
//Duplicate of DATA0CH0_CR_DDRCRDATAOFFSETCOMP_REG

#define DATA_CR_DDRCRDATACONTROL0_REG                                  (0x00008CFC)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL0_REG

#define DATA_CR_DDRCRDATACONTROL1_REG                                  (0x00008D00)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL1_REG

#define DATA_CR_DDRCRDATACONTROL5_REG                                  (0x00008D04)
//Duplicate of DATA0CH0_CR_DDRCRDATACONTROL5_REG

#define DATA_CR_DDRCRRXEQTAP01_REG                                     (0x00008D08)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP01_REG

#define DATA_CR_DDRCRRXEQTAP_REG                                       (0x00008D0C)
//Duplicate of DATA0CH0_CR_DDRCRRXEQTAP_REG

#define DATA_CR_DDRCRCMDBUSTRAIN_REG                                   (0x00008D10)
//Duplicate of DATA0CH0_CR_DDRCRCMDBUSTRAIN_REG

#define DATA_CR_DDRCRDATATCOCONTROL0_REG                               (0x00008D14)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL0_REG

#define DATA_CR_DDRCRDATATCOCONTROL1_REG                               (0x00008D18)
//Duplicate of DATA0CH0_CR_DDRCRDATATCOCONTROL1_REG

#define DATA_CR_DDRCRWRRETRAINCONTROLSTATUS_REG                        (0x00008D1C)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA_CR_DDRCRRDRETRAINCONTROLSTATUS_REG                        (0x00008D20)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINCONTROLSTATUS_REG

#define DATA_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG                       (0x00008D24)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINSWIZZLECONTROL_REG

#define DATA_CR_DDRCRWRRETRAINDELTARANK_REG                            (0x00008D28)
//Duplicate of DATA0CH0_CR_DDRCRWRRETRAINDELTARANK_REG

#define DATA_CR_DDRCRRDRETRAINDELTARANK_REG                            (0x00008D2C)
//Duplicate of DATA0CH0_CR_DDRCRRDRETRAINDELTARANK_REG

#define DATA_CR_DATATRAINFEEDBACK_REG                                  (0x00008D30)
//Duplicate of DATA0CH0_CR_DATATRAINFEEDBACK_REG

#define DATA_CR_DCCFSMSTATUS_REG                                       (0x00008D34)
//Duplicate of DATA0CH0_CR_DCCFSMSTATUS_REG

#define DATA_CR_DCCLANESTATUS0_REG                                     (0x00008D38)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS0_REG

#define DATA_CR_DCCLANESTATUS1_REG                                     (0x00008D3C)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS1_REG

#define DATA_CR_DCCLANESTATUS2_REG                                     (0x00008D40)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS2_REG

#define DATA_CR_DCCLANESTATUS3_REG                                     (0x00008D44)
//Duplicate of DATA0CH0_CR_DCCLANESTATUS3_REG

#define DATA_CR_DDRCRMARGINMODECONTROL0_REG                            (0x00008D48)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODECONTROL0_REG

#define DATA_CR_DDRCRMARGINMODEDEBUGMSB0_REG                           (0x00008D4C)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA_CR_DDRCRMARGINMODEDEBUGLSB0_REG                           (0x00008D50)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define DATA_CR_DDRCRDLLSTATUS_REG                                     (0x00008D54)
//Duplicate of DATA0CH0_CR_DDRCRDLLSTATUS_REG

#define DATA_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG                         (0x00008D58)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG

#define DATA_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG                    (0x00008D5C)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG

#define DATA_CR_DDRCRCOMPDQSDELAY_REG                                  (0x00008D60)
//Duplicate of DATA0CH0_CR_DDRCRCOMPDQSDELAY_REG

#define DATA_CR_DDRCRADC_REG                                           (0x00008D64)
//Duplicate of DATA0CH0_CR_DDRCRADC_REG

#define DATA_CR_REFPIFSMCONTROL_REG                                    (0x00008D68)
//Duplicate of DATA0CH0_CR_REFPIFSMCONTROL_REG

#define DATA_CR_DDRDATADQRANK0LANE8_REG                                (0x00008D6C)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRDATADQRANK1LANE8_REG                                (0x00008D70)
//Duplicate of DATA0CH0_CR_DDRDATADQRANK0LANE0_REG

#define DATA_CR_DDRCRDATAVREFPERBIT012_REG                             (0x00008D74)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT012_REG

#define DATA_CR_DDRCRDATAVREFPERBIT345_REG                             (0x00008D78)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT345_REG

#define DATA_CR_DDRCRDATAVREFPERBIT67DBI_REG                           (0x00008D7C)
//Duplicate of DATA0CH0_CR_DDRCRDATAVREFPERBIT67DBI_REG

#define CH0DDR5_CR_DDRCRCLKCOMP_REG                                    (0x00008F00)
//Duplicate of DDRPHY_DDRCOMP_CR_DDRCRCACOMP_REG

#define CH0DDR5_CR_DDRCRCTLCOMP_REG                                    (0x00008F04)
//Duplicate of DDRPHY_DDRCOMP_CR_DDRCRCACOMP_REG

#define CH0DDR5_CR_DDRCRCACOMP_REG                                     (0x00008F08)
//Duplicate of DDRPHY_DDRCOMP_CR_DDRCRCACOMP_REG

#define CH0DDR5_CR_DDRCRCLKCTLCACOMPOFFSET_REG                         (0x00008F0C)
//Duplicate of CH0CCC_CR_DDRCRCLKCTLCACOMPOFFSET_REG

#define CH0DDR5_CR_DDRCRCCCLANE0_REG                                   (0x00008F10)
//Duplicate of CH0CCC_CR_DDRCRCCCLANE0_REG

#define CH0DDR5_CR_DDRCRCCCLANE1_REG                                   (0x00008F14)
//Duplicate of CH0CCC_CR_DDRCRCCCLANE0_REG

#define CH0DDR5_CR_DDRCRCCCLANE2_REG                                   (0x00008F18)
//Duplicate of CH0CCC_CR_DDRCRCCCLANE0_REG

#define CH0DDR5_CR_DDRCRCCCLANE3_REG                                   (0x00008F1C)
//Duplicate of CH0CCC_CR_DDRCRCCCLANE0_REG

#define CH0DDR5_CR_DDRCRCCCLANE4_REG                                   (0x00008F20)
//Duplicate of CH0CCC_CR_DDRCRCCCLANE0_REG

#define CH0DDR5_CR_DDRCRCCCLANE5_REG                                   (0x00008F24)
//Duplicate of CH0CCC_CR_DDRCRCCCLANE5_REG

#define CH0DDR5_CR_DDRCRCCCLANE6_REG                                   (0x00008F28)
//Duplicate of CH0CCC_CR_DDRCRCCCLANE0_REG

#define CH0DDR5_CR_DDRCRCCCLANE7_REG                                   (0x00008F2C)
//Duplicate of CH0CCC_CR_DDRCRCCCLANE0_REG

#define CH0DDR5_CR_DDRCRCCCLANE8_REG                                   (0x00008F30)
//Duplicate of CH0CCC_CR_DDRCRCCCLANE0_REG

#define CH0DDR5_CR_DDRCRCCCLANE9_REG                                   (0x00008F34)
//Duplicate of CH0CCC_CR_DDRCRCCCLANE0_REG

#define CH0DDR5_CR_DDRCRCCCPICODES_REG                                 (0x00008F38)
//Duplicate of CH0CCC_CR_DDRCRCCCPICODES_REG

#define CH0DDR5_CR_DDRCRPERBITDESKEWRISEFALL_REG                       (0x00008F3C)
//Duplicate of CH0CCC_CR_DDRCRPERBITDESKEWRISEFALL_REG

#define CH0DDR5_CR_DCCFSMCONTROL_REG                                   (0x00008F40)
//Duplicate of CH0CCC_CR_DCCFSMCONTROL_REG

#define CH0DDR5_CR_DCCCALCCONTROL_REG                                  (0x00008F44)
//Duplicate of CH0CCC_CR_DCCCALCCONTROL_REG

#define CH0DDR5_CR_REFPICONTROL_REG                                    (0x00008F48)
//Duplicate of DATA0CH0_CR_REFPICONTROL_REG

#define CH0DDR5_CR_DDRCRBSCANDATA_REG                                  (0x00008F50)
//Duplicate of CH0CCC_CR_DDRCRBSCANDATA_REG

#define CH0DDR5_CR_REFPIFSMCONTROL_REG                                 (0x00008F54)
//Duplicate of DATA0CH0_CR_REFPIFSMCONTROL_REG

#define CH0DDR5_CR_DCCFSMSTATUS_REG                                    (0x00008F58)
//Duplicate of CH0CCC_CR_DCCFSMSTATUS_REG

#define CH0DDR5_CR_DCCLANESTATUS0_REG                                  (0x00008F5C)
//Duplicate of CH0CCC_CR_DCCLANESTATUS0_REG

#define CH0DDR5_CR_DCCLANESTATUS1_REG                                  (0x00008F60)
//Duplicate of CH0CCC_CR_DCCLANESTATUS1_REG

#define CH0DDR5_CR_DDRCRMARGINMODECONTROL_REG                          (0x00008F64)
//Duplicate of DDRDATA_SHARED0_CR_DDRCRMARGINMODECONTROL_REG

#define CH0DDR5_CR_DDRCRMARGINMODEDEBUGMSB_REG                         (0x00008F68)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define CH0DDR5_CR_DDRCRMARGINMODEDEBUGLSB_REG                         (0x00008F6C)
//Duplicate of DATA0CH0_CR_DDRCRMARGINMODEDEBUGMSB0_REG

#define CH0DDR5_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG                      (0x00008F70)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSOR_REG

#define CH0DDR5_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG                 (0x00008F74)
//Duplicate of DATA0CH0_CR_DDRCRVCCCLKFFCURRENTSENSORCOUNT_REG

#define CH0DDR5_CR_DDRCRADC_REG                                        (0x00008F78)
//Duplicate of DATA0CH0_CR_DDRCRADC_REG

#define CH0DDR5_CR_DFXCCMON_REG                                        (0x00008F7C)
//Duplicate of DDRPHY_DDRCOMP_CR_DFXCCMON_REG

#define CH0DDR5_CR_DDRCRMARGINMODECONTROL1_REG                         (0x00008F80)
//Duplicate of CH0CCC_CR_DDRCRMARGINMODECONTROL1_REG

#define CH0DDR5_CR_CBB_BONUS0_REG                                      (0x00008F84)
//Duplicate of CH0CCC_CR_CBB_BONUS0_REG

#define CH0DDR5_CR_BONUS0_REG                                          (0x00008F88)
//Duplicate of CH0CCC_CR_BONUS0_REG

#define CH0DDR5_CR_REFPICLKOFFSET_REG                                  (0x00008F8C)
//Duplicate of CH0CCC_CR_REFPICLKOFFSET_REG

#define CH0DDR5_CR_LPMODE4_FLYBY_REG                                   (0x00008F90)
//Duplicate of CH0CCC_CR_LPMODE4_FLYBY_REG

#define CH0DDR5_CR_CCC_OVRDCTL_REG                                     (0x00008F94)
//Duplicate of CH0CCC_CR_CCC_OVRDCTL_REG

#define CH0DDR5_DDRTXDLL_CR_PICODELUT0_REG                             (0x00008F98)
//Duplicate of DDRDATA_SHARED0_DDRTXDLL_CR_PICODELUT0_REG

#define CH0DDR5_DDRTXDLL_CR_PICODELUT1_REG                             (0x00008F9C)
//Duplicate of DDRDATA_SHARED0_DDRTXDLL_CR_PICODELUT1_REG

#define CH0DDR5_DDRTXDLL_CR_PICODELUT2_REG                             (0x00008FA0)
//Duplicate of DDRDATA_SHARED0_DDRTXDLL_CR_PICODELUT2_REG

#define CH0DDR5_DDRTXDLL_CR_PICODELUT3_REG                             (0x00008FA4)
//Duplicate of DDRDATA_SHARED0_DDRTXDLL_CR_PICODELUT3_REG

#define CH0DDR5_CR_TERDCCCONTROL0_REG                                  (0x00008FA8)
//Duplicate of DATA0CH0_CR_TERDCCCONTROL0_REG

#define CH0DDR5_CR_CS_GEARDOWN_REG                                     (0x00008FAC)
//Duplicate of CH0CCC_CR_CS_GEARDOWN_REG

#define CH0DDR5_CR_DDRCRCCCDCCCLKLANE5_REG                             (0x00008FB0)
//Duplicate of CH0CCC_CR_DDRCRCCCDCCCLKLANE5_REG

#define CH0DDR5_CR_COMPUPDATEOVERRIDE_REG                              (0x00008FB4)
//Duplicate of CH0CCC_CR_COMPUPDATEOVERRIDE_REG

#define CH0DDR5_CR_SPARE_REG                                           (0x00008FB8)
//Duplicate of DATA0CH0_CR_SPARE_REG



#pragma pack(pop)
#endif /* __MrcRegisterPtl8xxx_h__ */







