/** @file

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2017 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/

//
// Automatically generated by ACE ver 1.63 PIRQTRANS
// Please DO NOT modify !!!
//


PCI_OPTION_ROM_TABLE mPciOptionRomTable_Default[] = {
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0xff05,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x8a51,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x8a52,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x8a70,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1906,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1913,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1916,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1921,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1926,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x190b,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x191b,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x192b,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x193b,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x192d,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x193d,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x190e,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1915,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x191e,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x190a,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x191a,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x192a,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x193a,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1902,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1912,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1917,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x1932,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x191d,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5906,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5913,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5916,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5921,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5926,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x590b,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x591b,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x592b,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x593b,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x590e,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5915,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x591e,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x590a,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x591a,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x592a,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x593a,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5902,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5912,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5917,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5932,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x591d,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x593d,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x2a42,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x106,                                            // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x116,                                            // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x126,                                            // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0xa02,                                            // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x102,                                            // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x112,                                            // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x122,                                            // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x10a,                                            // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5a51,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5a52,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5a5a,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5a42,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5a4a,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5a62,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5a54,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5a44,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5a55,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    MOBILE_ONBOARD_VIDEO_OPTION_ROM_FILE_GUID,          // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x2,                                              // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x5a45,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    RAID_OPTION_ROM_FILE_GUID,                        // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x17,                                             // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x282a,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    RAID_OPTION_ROM_FILE_GUID,                        // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x17,                                             // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x2822,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    RSTE_OPTION_ROM_FILE_GUID,                        // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x17,                                             // Device Number
    0x0,                                              // Function Number
    0x8086,                                           // Vendor ID
    0x2826,                                           // Device ID
  },
  //
  // Option Rom for
  //
  {
    PXE_OPTION_ROM_FILE_GUID,                         // Guid
    0x0,                                              // Segment
    0x0,                                              // Bus Number
    0x1f,                                             // Device Number
    0x6,                                              // Function Number
    0xffff,                                           // Vendor ID
    0xffff,                                           // Device ID
  },
  //
  // End of OptionRom Entries
  //
  {
    NULL_ROM_FILE_GUID,                               // Guid
    0,                                                // Segment
    0,                                                // Bus Number
    0,                                                // Device Number
    0,                                                // Function Number
    0xffff,                                           // Vendor ID
    0xffff,                                           // Device ID
  }
};

