//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//

/** @file

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2022 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification
**/

//
// Define CNV NVS Area operation region.
//
#ifndef _CNV_PKG_NVS_AREA_DEF_H_
#define _CNV_PKG_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  UINT8    BluetoothSar;                            ///< Offset 0       BluetoothSar
  UINT8    BluetoothSarBr;                          ///< Offset 1       BluetoothSarBr
  UINT8    BluetoothSarEdr2;                        ///< Offset 2       BluetoothSarEdr2
  UINT8    BluetoothSarEdr3;                        ///< Offset 3       BluetoothSarEdr3
  UINT8    BluetoothSarLe;                          ///< Offset 4       BluetoothSarLe
  UINT8    BluetoothSarLe2Mhz;                      ///< Offset 5       BluetoothSarLe2Mhz
  UINT8    BluetoothSarLeLr;                        ///< Offset 6       BluetoothSarLeLr
  UINT32   WlanWakeGpio;                            ///< Offset 7       WLAN Wake Gpio pin
  UINT8    WlanRootPortNumber;                      ///< Offset 11      WLAN Root Port Number
  UINT8    DiscreteUsbBtPort;                       ///< Offset 12      Discrete USB BT Port
  UINT8    IntegratedUsbBtPort;                     ///< Offset 13      Integrated USB BT Port
  UINT32   BtModuleRfKillGpio;                      ///< Offset 14      Gpio for Bluetooth RfKill
  UINT32   BtModuleIrqGpio;                         ///< Offset 18      Gpio for Bluetooth interrupt
  UINT8    SkipVidDidCheck;                         ///< Offset 22      Skip VDID check
  UINT8    CnvDlvrRfim;                             ///< Offset 23      CNV DLVR RFI Mitigation
  UINT32   WlanRstGpio;                             ///< Offset 24      WLAN Reset Gpio pin
  UINT64   WlanDeviceCapRegOffset;                  ///< Offset 28      Wlan Device Capabilities Reg Base Address
  UINT64   WlanVsecHeaderOffset;                    ///< Offset 36      Wlan VSEC Control Reg Base Address
  UINT32   DiscreteWlanRfKillGpio;                  ///< Offset 44      Gpio for WiFi RF-Kill
  UINT8    CnvGuidLockStatus;                       ///< Offset 48      CNV Guid Lock Status ACPI Indicator
  //
  // Temp Register CNVd Pci Cfg Reg
  //
  UINT32   CNVdRegister[4];                         ///< Offset 49      Max No-Snoop Latency, Max Snoop Latency
                                                    ///< Offset 53      L1 PM Substates Control 1 Register
                                                    ///< Offset 57      L1 PM Substates Control 2 Register
                                                    ///< Offset 61      PTM
} CNV_PKG_NVS_AREA;

#pragma pack(pop)
#endif
