//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//

/** @file

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2022 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/

  //
  // Define VMD NVS Area operation region.
  //
#ifndef _VMD_NVS_AREA_DEF_H_
#define _VMD_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  UINT8    VmdEnable;                               ///< Offset 0       VMD Device Enable
  UINT32   VmdSocPciePorts;                         ///< Offset 1       VMD SOC and IOE PCIe RP mapped under VMD
  UINT32   VmdPchPcieRp;                            ///< Offset 5       VMD PCH PCIe RP mapped under VMD
  UINT8    VmdSataPort0to7;                         ///< Offset 9       VMD SATA PORT 0 to 7 mapped under VMD
  UINT8    PchRpBusNo;                              ///< Offset 10      PCH ROOT PORT BUS Number
} VMD_NVS_AREA;

#pragma pack(pop)
#endif
