//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//

/** @file
  ACPI DPTF table

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2011 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification
**/

  // Define a Global region of ACPI NVS Region that may be used for any
  // type of implementation.  The starting offset and size will be fixed
  // up by the System BIOS during POST.  Note that the Size must be a word
  // in size to be fixed up correctly.

#ifndef _DPTF_NVS_AREA_DEF_H_
#define _DPTF_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  //
  // Intel(R) Dynamic Tuning Technology Devices and trip points
  //
  UINT8    EnableDptf;                              ///< Offset 0       EnableDptf
  UINT32   EnableDCFG;                              ///< Offset 1       EnableDCFG
  UINT8    EnableFan1Device;                        ///< Offset 5       EnableFan1Device
  UINT8    EnableFan2Device;                        ///< Offset 6       EnableFan2Device
  UINT8    EnableFan3Device;                        ///< Offset 7       EnableFan3Device
  UINT8    EnableChargerParticipant;                ///< Offset 8       EnableChargerParticipant
  UINT8    EnableBatteryParticipant;                ///< Offset 9       EnableBatteryParticipant
  UINT8    EnableSen1Participant;                   ///< Offset 10      EnableSen1Participant
  UINT8    EnableSen2Participant;                   ///< Offset 11      EnableSen2Participant
  UINT8    EnableSen3Participant;                   ///< Offset 12      EnableSen3Participant
  UINT8    EnableSen4Participant;                   ///< Offset 13      EnableSen4Participant
  UINT8    EnableSen5Participant;                   ///< Offset 14      EnableSen5Participant
  UINT8    EnablePchFivrParticipant;                ///< Offset 15      EnablePchFivrParticipant
  //
  // Miscellaneous Intel(R) Dynamic Tuning Technology
  //
  UINT32   PpccStepSize;                            ///< Offset 16      PPCC Step Size
  UINT8    EnablePowerParticipant;                  ///< Offset 20      EnablePowerParticipant
  UINT16   PowerParticipantPollingRate;             ///< Offset 21      PowerParticipantPollingRate
  UINT8    OemDesignVariable0;                      ///< Offset 23      Intel(R) Dynamic Tuning Technology Oem Design Variables
  UINT8    OemDesignVariable1;                      ///< Offset 24      Intel(R) Dynamic Tuning Technology Oem Design Variables
  UINT8    OemDesignVariable2;                      ///< Offset 25      Intel(R) Dynamic Tuning Technology Oem Design Variables
  UINT8    OemDesignVariable3;                      ///< Offset 26      Intel(R) Dynamic Tuning Technology Oem Design Variables
  UINT8    OemDesignVariable4;                      ///< Offset 27      Intel(R) Dynamic Tuning Technology Oem Design Variables
  UINT8    OemDesignVariable5;                      ///< Offset 28      Intel(R) Dynamic Tuning Technology Oem Design Variables
  //
  // Enabling Auto Mode
  //
  UINT8    EnableFanAutoMode;                       ///< Offset 29      Enabling Auto Mode for DTT
} DPTF_NVS_AREA;

#pragma pack(pop)
#endif
