/** @file
  Display_Mem.h

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2007 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification

  This file contains Silicon register definitions.

  This is a generated file; please do not modify it directly.

**/

#ifndef _DISPLAY_MEM_h
#define _DISPLAY_MEM_h


//************************************************ RegisterStructs

#ifdef SV_HOOKS

/** SDE_CHKN_BIOS_SECURED desc:
  */

#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_REG (0x000c2004U)

typedef union {
  struct {
    UINT32 spare_0 : 1;
    UINT32 spare_1 : 1;
    UINT32 spare_2 : 1;
    UINT32 spare_3 : 1;
    UINT32 spare_4 : 1;
    UINT32 spare_5 : 1;
    UINT32 spare_6 : 1;
    UINT32 spare_7 : 1;
    UINT32 spare_8 : 1;
    UINT32 spare_9 : 1;
    UINT32 spare_10 : 1;
    UINT32 spare_11 : 1;
    UINT32 spare_12 : 1;
    UINT32 spare_13 : 1;
    UINT32 spare_14 : 1;
    UINT32 spare_15 : 1;
    UINT32 spare_16 : 1;
    UINT32 spare_17 : 1;
    UINT32 spare_18 : 1;
    UINT32 spare_19 : 1;
    UINT32 spare_20 : 1;
    UINT32 spare_21 : 1;
    UINT32 spare_22 : 1;
    UINT32 spare_23 : 1;
    UINT32 spare_24 : 1;
    UINT32 spare_25 : 1;
    UINT32 spare_26 : 1;
    UINT32 spare_27 : 1;
    UINT32 spare_28 : 1;
    UINT32 spare_29 : 1;
    UINT32 spare_30 : 1;
    UINT32 spare_31 : 1;
  }     Bits;
  UINT32 Data;
  UINT16 Data16[2];
  UINT8  Data8[4];
} SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_STRUCT;

#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_WIDTH 32
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_DEFAULT 0x00000000U
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_ENDPOINT DISPLAY_MEM

#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_0_LSB 0x0000
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_0_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_1_LSB 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_1_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_2_LSB 0x0002
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_2_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_3_LSB 0x0003
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_3_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_4_LSB 0x0004
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_4_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_5_LSB 0x0005
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_5_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_6_LSB 0x0006
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_6_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_7_LSB 0x0007
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_7_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_8_LSB 0x0008
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_8_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_9_LSB 0x0009
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_9_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_10_LSB 0x000a
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_10_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_11_LSB 0x000b
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_11_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_12_LSB 0x000c
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_12_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_13_LSB 0x000d
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_13_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_14_LSB 0x000e
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_14_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_15_LSB 0x000f
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_15_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_16_LSB 0x0010
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_16_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_17_LSB 0x0011
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_17_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_18_LSB 0x0012
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_18_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_19_LSB 0x0013
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_19_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_20_LSB 0x0014
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_20_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_21_LSB 0x0015
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_21_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_22_LSB 0x0016
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_22_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_23_LSB 0x0017
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_23_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_24_LSB 0x0018
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_24_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_25_LSB 0x0019
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_25_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_26_LSB 0x001a
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_26_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_27_LSB 0x001b
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_27_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_28_LSB 0x001c
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_28_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_29_LSB 0x001d
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_29_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_30_LSB 0x001e
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_30_SIZE 0x0001
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_31_LSB 0x001f
#define SDE_CHKN_BIOS_SECURED_DISPLAY_MEM_SPARE_31_SIZE 0x0001

#endif      // SV_HOOKS

#ifdef SV_HOOKS

/** PCH_RESET_PREP_ACK_TIMEOUT desc:
  */

#define PCH_RESET_PREP_ACK_TIMEOUT_DISPLAY_MEM_REG (0x000c5164U)

typedef union {
  struct {
    UINT32 reset_prep_ack_timeout : 32;
  }     Bits;
  UINT32 Data;
  UINT16 Data16[2];
  UINT8  Data8[4];
} PCH_RESET_PREP_ACK_TIMEOUT_DISPLAY_MEM_STRUCT;

#define PCH_RESET_PREP_ACK_TIMEOUT_DISPLAY_MEM_WIDTH 32
#define PCH_RESET_PREP_ACK_TIMEOUT_DISPLAY_MEM_DEFAULT 0x00afc800U
#define PCH_RESET_PREP_ACK_TIMEOUT_DISPLAY_MEM_ENDPOINT DISPLAY_MEM

#define PCH_RESET_PREP_ACK_TIMEOUT_DISPLAY_MEM_RESET_PREP_ACK_TIMEOUT_LSB 0x0000
#define PCH_RESET_PREP_ACK_TIMEOUT_DISPLAY_MEM_RESET_PREP_ACK_TIMEOUT_SIZE 0x0020

#endif      // SV_HOOKS

/** PP_CONTROL desc:
  */

#define PP_CONTROL_DISPLAY_MEM_REG       (0x000c7204U)

typedef union {
  struct {
    UINT32 power_state_target : 1;
    UINT32 power_down_on_reset : 1;
    UINT32 backlight_enable : 1;
    UINT32 vdd_override : 1;
    UINT32 power_cycle_delay : 5;
    UINT32 rsvd_0 : 7;
    UINT32 spare_31_16 : 16;
  }     Bits;
  UINT32 Data;
  UINT16 Data16[2];
  UINT8  Data8[4];
} PP_CONTROL_DISPLAY_MEM_STRUCT;

#define PP_CONTROL_DISPLAY_MEM_WIDTH 32
#define PP_CONTROL_DISPLAY_MEM_DEFAULT 0x00000000U
#define PP_CONTROL_DISPLAY_MEM_ENDPOINT DISPLAY_MEM

#define PP_CONTROL_DISPLAY_MEM_POWER_STATE_TARGET_LSB 0x0000
#define PP_CONTROL_DISPLAY_MEM_POWER_STATE_TARGET_SIZE 0x0001
#define PP_CONTROL_DISPLAY_MEM_POWER_DOWN_ON_RESET_LSB 0x0001
#define PP_CONTROL_DISPLAY_MEM_POWER_DOWN_ON_RESET_SIZE 0x0001
#define PP_CONTROL_DISPLAY_MEM_BACKLIGHT_ENABLE_LSB 0x0002
#define PP_CONTROL_DISPLAY_MEM_BACKLIGHT_ENABLE_SIZE 0x0001
#define PP_CONTROL_DISPLAY_MEM_VDD_OVERRIDE_LSB 0x0003
#define PP_CONTROL_DISPLAY_MEM_VDD_OVERRIDE_SIZE 0x0001
#define PP_CONTROL_DISPLAY_MEM_POWER_CYCLE_DELAY_LSB 0x0004
#define PP_CONTROL_DISPLAY_MEM_POWER_CYCLE_DELAY_SIZE 0x0005
#define PP_CONTROL_DISPLAY_MEM_SPARE_31_16_LSB 0x0010
#define PP_CONTROL_DISPLAY_MEM_SPARE_31_16_SIZE 0x0010


/** PP_CONTROL_2 desc:
  */

#define PP_CONTROL_2_DISPLAY_MEM_REG     (0x000c7304U)

typedef union {
  struct {
    UINT32 power_state_target : 1;
    UINT32 power_down_on_reset : 1;
    UINT32 backlight_enable : 1;
    UINT32 vdd_override : 1;
    UINT32 power_cycle_delay : 5;
    UINT32 rsvd_0 : 7;
    UINT32 spare_31_16 : 16;
  }     Bits;
  UINT32 Data;
  UINT16 Data16[2];
  UINT8  Data8[4];
} PP_CONTROL_2_DISPLAY_MEM_STRUCT;

#define PP_CONTROL_2_DISPLAY_MEM_WIDTH 32
#define PP_CONTROL_2_DISPLAY_MEM_DEFAULT 0x00000000U
#define PP_CONTROL_2_DISPLAY_MEM_ENDPOINT DISPLAY_MEM

#define PP_CONTROL_2_DISPLAY_MEM_POWER_STATE_TARGET_LSB 0x0000
#define PP_CONTROL_2_DISPLAY_MEM_POWER_STATE_TARGET_SIZE 0x0001
#define PP_CONTROL_2_DISPLAY_MEM_POWER_DOWN_ON_RESET_LSB 0x0001
#define PP_CONTROL_2_DISPLAY_MEM_POWER_DOWN_ON_RESET_SIZE 0x0001
#define PP_CONTROL_2_DISPLAY_MEM_BACKLIGHT_ENABLE_LSB 0x0002
#define PP_CONTROL_2_DISPLAY_MEM_BACKLIGHT_ENABLE_SIZE 0x0001
#define PP_CONTROL_2_DISPLAY_MEM_VDD_OVERRIDE_LSB 0x0003
#define PP_CONTROL_2_DISPLAY_MEM_VDD_OVERRIDE_SIZE 0x0001
#define PP_CONTROL_2_DISPLAY_MEM_POWER_CYCLE_DELAY_LSB 0x0004
#define PP_CONTROL_2_DISPLAY_MEM_POWER_CYCLE_DELAY_SIZE 0x0005
#define PP_CONTROL_2_DISPLAY_MEM_SPARE_31_16_LSB 0x0010
#define PP_CONTROL_2_DISPLAY_MEM_SPARE_31_16_SIZE 0x0010

//************************************************ /RegisterStructs


#endif      // _DISPLAY_MEM_h
