/** @file
 Entry point of VTIO Setup DXE driver.

 This driver will collect platform specific information to be consumed by VTIO platform independent driver.

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2021 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/

#include <Library/BaseLib.h>
#include <Library/UefiRuntimeServicesTableLib.h>
#include <Library/UefiBootServicesTableLib.h>
#include <Library/DevicePathLib.h>
#include <Library/BaseMemoryLib.h>
#include <Library/HiiLib.h>
#include <Library/UefiLib.h>
#include <Library/DebugLib.h>
#include <Library/PrintLib.h>
#include <Library/MemoryAllocationLib.h>
#include <Protocol/HiiConfigRouting.h>
#include <Protocol/HiiConfigAccess.h>
#include <Protocol/DevicePath.h>
#include <Guid/MdeModuleHii.h>
#include <Uefi.h>
#include <VtioSetup.h>

// These variables definitions are autogenerated by build system
extern UINT8 VtioSetupVfrBin[];
extern UINT8 VtioSetupStrings[];

VTIO_SETUP_DATA_STRUCT           gVtioSetupData                 = {0};
EFI_HII_CONFIG_ACCESS_PROTOCOL   gVtioSetupMenuCallbackProtocol = {0};
EFI_HII_CONFIG_ROUTING_PROTOCOL  *mHiiConfigRouting             = NULL;

typedef enum {
  UINT_TYPE_8bit = 0,
  UINT_TYPE_16bit,
  UINT_TYPE_64bit
}VTIO_DATA_TYPE;

typedef struct {
  VENDOR_DEVICE_PATH           VendorDevicePath;
  EFI_DEVICE_PATH_PROTOCOL     End;
} HII_VENDOR_DEVICE_PATH;

GLOBAL_REMOVE_IF_UNREFERENCED HII_VENDOR_DEVICE_PATH  gVtioSetupMenuHiiVendorDevicePath = {
  {
    {
      HARDWARE_DEVICE_PATH,
      HW_VENDOR_DP,
      {
        (UINT8) (sizeof (VENDOR_DEVICE_PATH)),
        (UINT8) ((sizeof (VENDOR_DEVICE_PATH)) >> 8)
      }
    },
    VTIO_FORMSET_GUID
  },
  {
    END_DEVICE_PATH_TYPE,
    END_ENTIRE_DEVICE_PATH_SUBTYPE,
    {
      (UINT8) (END_DEVICE_PATH_LENGTH),
      (UINT8) ((END_DEVICE_PATH_LENGTH) >> 8)
    }
  }
};

/**
  Dump Array Contents

  @param[in] ArrPtr Pointer to the Array containing 16bit element.
  @param[in] Length Length of the Array.
  @param[in] Type   enum datatype.
**/
VOID
DebugArrayDmp (
  IN VOID *ArrPtr,
  IN UINT16 Length,
  IN VTIO_DATA_TYPE Type
  )
{
  switch (Type)
  {
    case UINT_TYPE_8bit:
    for (UINT16 i = 0; i < Length; i++)
    {
      DEBUG ((DEBUG_INFO, "%016llx ", ((UINT8 *)ArrPtr)[i]));
    }
      break;
    case UINT_TYPE_16bit:
    for (UINT16 i = 0; i < Length; i++)
    {
      DEBUG ((DEBUG_INFO, "%016llx ", ((UINT16 *)ArrPtr)[i]));
    }
      break;
    case UINT_TYPE_64bit:
    for (UINT16 i = 0; i < Length; i++)
    {
      DEBUG ((DEBUG_INFO, "%016llx ", ((UINT64 *)ArrPtr)[i]));
    }
      break;
    default:
      DEBUG ((DEBUG_ERROR, "Data Type Not Supported"));
      break;
  }
  DEBUG ((DEBUG_INFO, "\n"));
}

/**
  This function is used for printing VTIO setup data passed from VtioSetup driver

  @param[in]  VTIO_SETUP_DATA_STRUCT*   Pointer to VTIO_SETUP_DATA_STRUCT
**/
VOID
ShowConfig (
  IN VTIO_SETUP_DATA_STRUCT *Cfg
  )
{
  DEBUG ((DEBUG_INFO, "VtioSupport= %x\n",Cfg->VtioSupport));
  DEBUG ((DEBUG_INFO, "SdevCio2Entry= %x\n",Cfg->SdevCio2Entry));
  DEBUG ((DEBUG_INFO, "SdevIspEntry= %x\n",Cfg->SdevIspEntry));
  DEBUG ((DEBUG_INFO, "SdevHeciEntry= %x\n",Cfg->SdevHeciEntry));
  DEBUG ((DEBUG_INFO, "SdevSpi1Entry= %x\n",Cfg->SdevSpi1Entry));
  DEBUG ((DEBUG_INFO, "SdevSpi2Entry= %x\n",Cfg->SdevSpi2Entry));
  DEBUG ((DEBUG_INFO, "SdevXhciEntry= %x\n",Cfg->SdevXhciEntry));
  DEBUG ((DEBUG_INFO, "SdevNumberOfSensors= "));
  DebugArrayDmp (Cfg->SdevNumberOfSensors, 5, UINT_TYPE_16bit);
  DEBUG ((DEBUG_INFO, "SdevSensorEntry1= "));
  DebugArrayDmp (Cfg->SdevSensorEntry1, 5, UINT_TYPE_16bit);
  DEBUG ((DEBUG_INFO, "SdevSensorEntry2= "));
  DebugArrayDmp (Cfg->SdevSensorEntry2, 5, UINT_TYPE_16bit);
  DEBUG ((DEBUG_INFO, "SdevXhciNumberOfDevices= %x\n",Cfg->SdevXhciNumberOfDevices));
  DEBUG ((DEBUG_INFO, "SdevXhciDeviceAttributes= "));
  DebugArrayDmp (Cfg->SdevXhciDeviceAttributes, 2, UINT_TYPE_8bit);
  DEBUG ((DEBUG_INFO, "SdevXhciRootPortNumber= "));
  DebugArrayDmp (Cfg->SdevXhciRootPortNumber, 2, UINT_TYPE_8bit);
  DEBUG ((DEBUG_INFO, "SdevXhciVendorId= "));
  DebugArrayDmp (Cfg->SdevXhciVendorId, 2, UINT_TYPE_16bit);
  DEBUG ((DEBUG_INFO, "SdevXhciProductId= "));
  DebugArrayDmp (Cfg->SdevXhciProductId, 2, UINT_TYPE_16bit);
  DEBUG ((DEBUG_INFO, "SdevXhciRevision= "));
  DebugArrayDmp (Cfg->SdevXhciRevision, 2, UINT_TYPE_16bit);
  DEBUG ((DEBUG_INFO, "SdevXhciInterfaceNumber= "));
  DebugArrayDmp (Cfg->SdevXhciInterfaceNumber, 2, UINT_TYPE_8bit);
  DEBUG ((DEBUG_INFO, "SdevXhciClass= "));
  DebugArrayDmp (Cfg->SdevXhciClass, 2, UINT_TYPE_8bit);
  DEBUG ((DEBUG_INFO, "SdevXhciSubClass= "));
  DebugArrayDmp (Cfg->SdevXhciSubClass, 2, UINT_TYPE_8bit);
  DEBUG ((DEBUG_INFO, "SdevXhciProtocol= "));
  DebugArrayDmp (Cfg->SdevXhciProtocol, 2, UINT_TYPE_8bit);
  DEBUG ((DEBUG_INFO, "SdevXhciAcpiPathStringOffset= "));
  DebugArrayDmp (Cfg->SdevXhciAcpiPathStringOffset, 2, UINT_TYPE_16bit);
  DEBUG ((DEBUG_INFO, "SdevXhciAcpiPathStringLength= "));
  DebugArrayDmp (Cfg->SdevXhciAcpiPathStringLength, 2, UINT_TYPE_16bit);
  DEBUG ((DEBUG_INFO, "SdevXhciFirmwareHashDevice1= "));
  DebugArrayDmp (Cfg->SdevXhciFirmwareHashDevice1, 4, UINT_TYPE_64bit);
  DEBUG ((DEBUG_INFO, "SdevXhciFirmwareHashDevice2= "));
  DebugArrayDmp (Cfg->SdevXhciFirmwareHashDevice2, 4, UINT_TYPE_64bit);
  DEBUG ((DEBUG_INFO, "SdevXhciAcpiPathNameDevice1= %s\n",Cfg->SdevXhciAcpiPathNameDevice1));
  DEBUG ((DEBUG_INFO, "SdevXhciAcpiPathNameDevice2= %s\n",Cfg->SdevXhciAcpiPathNameDevice2));
  DEBUG ((DEBUG_INFO, "SdevFlags= "));
  DebugArrayDmp (Cfg->SdevFlags, 5, UINT_TYPE_8bit);
  DEBUG ((DEBUG_INFO, "SdevXhciFlags= %x\n",Cfg->SdevXhciFlags));
}


/**
  Construct Request String (L"&OFFSET=%x&WIDTH=%x") base on the input Offset and Width.
  If the input RequestString is not NULL, new request will be cat at the end of it. The full
  request string will be constructed and return. Caller is responsible to free it.

  @param[in] RequestString   Current request string.
  @param[in] Offset          Offset of data in Storage.
  @param[in] Width           Width of data.

  @return String             Request string with input Offset and Width.
**/
EFI_STRING
EFIAPI
HiiConstructRequestString (
  IN EFI_STRING      RequestString, OPTIONAL
  IN UINTN           Offset,
  IN UINTN           Width
  )
{
  CHAR16             RequestElement[30];
  UINTN              StringLength;
  EFI_STRING         NewString;

  StringLength = UnicodeSPrint (
                   RequestElement,
                   sizeof (RequestElement),
                   L"&OFFSET=%x&WIDTH=%x",
                   Offset,
                   Width
                   );
  if (RequestString != NULL) {
    StringLength = StringLength + StrLen (RequestString);
  }
  NewString = AllocateZeroPool ((StringLength + 1) * sizeof (CHAR16));
  if (NewString == NULL) {
    return NULL;
  }
  if (RequestString != NULL) {
    StrCatS (NewString, ((StringLength + 1) * sizeof (CHAR16)) / sizeof (CHAR16), RequestString);
    FreePool (RequestString);
  }
  StrCatS (NewString, ((StringLength + 1) * sizeof (CHAR16)) / sizeof (CHAR16), RequestElement);
  return NewString;
}

/**
  Initializes xHCI ACPI Path Name and String Length

  @retval EFI_SUCCESS            Successfully completed updates.
  @retval EFI_NOT_FOUND          Setup data not found.
  @retval EFI_OUT_OF_RESOURCES   Allocation failure for Setup data.
**/
EFI_STATUS
SdevXhciAcpiPathNameUpdate (
  VOID
  )
{
  VTIO_SETUP_DATA_STRUCT *CurrentUserSetupData;
  UINTN                   VarSize;
  EFI_STATUS              Status;
  EFI_STRING              RequestString             = NULL;
  UINT16                  Device1AcpiPathName[]     = DEVICE_PATH_NAME1;
  UINT16                  Device2AcpiPathName[]     = DEVICE_PATH_NAME2;

  VarSize              = sizeof (VTIO_SETUP_DATA_STRUCT);
  CurrentUserSetupData = AllocatePool (VarSize);
  ASSERT (CurrentUserSetupData != NULL);

  if (CurrentUserSetupData == NULL) {
    return EFI_OUT_OF_RESOURCES;
  }

  Status = HiiGetBrowserData (&gVtioSetupGuid, VTIO_CFG_VARIABLE_NAME, VarSize, (UINT8 *) CurrentUserSetupData);
  ASSERT_EFI_ERROR (Status);
  if (Status != TRUE) {
    FreePool (CurrentUserSetupData);
    return EFI_NOT_FOUND;
  }

  ///
  /// Populate xHCI Device 1 ACPI Path Name and Length with default value
  ///
  if (CurrentUserSetupData->SdevXhciAcpiPathNameDevice1[0] == 0x0) {
    ZeroMem (CurrentUserSetupData->SdevXhciAcpiPathNameDevice1, sizeof (CurrentUserSetupData->SdevXhciAcpiPathNameDevice1));
    CurrentUserSetupData->SdevXhciAcpiPathStringLength[0] = (UINT16) (StrLen (Device1AcpiPathName) + 1);
    CopyMem (CurrentUserSetupData->SdevXhciAcpiPathNameDevice1, Device1AcpiPathName, StrSize (Device2AcpiPathName));
  }

  ///
  /// Populate xHCI Device 2 ACPI Path Name and Length with default value
  ///
  if (CurrentUserSetupData->SdevXhciAcpiPathNameDevice2[0] == 0x0) {
    ZeroMem (CurrentUserSetupData->SdevXhciAcpiPathNameDevice2, sizeof (CurrentUserSetupData->SdevXhciAcpiPathNameDevice2));
    CurrentUserSetupData->SdevXhciAcpiPathStringLength[1] = (UINT16) (StrLen (Device2AcpiPathName) + 1);
    CopyMem (CurrentUserSetupData->SdevXhciAcpiPathNameDevice2, Device2AcpiPathName, StrSize (Device2AcpiPathName));
  }

  RequestString = HiiConstructRequestString (RequestString, OFFSET_OF (VTIO_SETUP_DATA_STRUCT, SdevXhciAcpiPathNameDevice1), sizeof (CurrentUserSetupData->SdevXhciAcpiPathNameDevice1));
  RequestString = HiiConstructRequestString (RequestString, OFFSET_OF (VTIO_SETUP_DATA_STRUCT, SdevXhciAcpiPathNameDevice2), sizeof (CurrentUserSetupData->SdevXhciAcpiPathNameDevice2));
  RequestString = HiiConstructRequestString (RequestString, OFFSET_OF (VTIO_SETUP_DATA_STRUCT, SdevXhciAcpiPathStringLength), sizeof (CurrentUserSetupData->SdevXhciAcpiPathStringLength));

  if (RequestString != NULL) {
    VarSize = sizeof (VTIO_SETUP_DATA_STRUCT);
    Status = HiiSetBrowserData (&gVtioSetupGuid, VTIO_CFG_VARIABLE_NAME, VarSize, (UINT8 *) CurrentUserSetupData, RequestString);
    ASSERT_EFI_ERROR (Status);
    FreePool (RequestString);
    if (Status != TRUE) {
      return EFI_NOT_FOUND;
    }
  }

  FreePool (CurrentUserSetupData);

  return EFI_SUCCESS;
}

/**
  Updates xHCI ACPI Path Name and String Length

  @param[IN]       EFI_FORM_CALLBACK_PROTOCOL   *This
  @param[IN]       EFI_BROWSER_ACTION           Action,
  @param[IN]       EFI_QUESTION_ID              KeyValue
  @param[IN]       UINT8                        Type,
  @param[IN]       EFI_IFR_TYPE_VALUE           *Value,
  @param[IN]       EFI_BROWSER_ACTION_REQUEST   *ActionRequest

  @retval EFI_SUCCESS            Successfully completed updates.
  @retval EFI_NOT_FOUND          Setup data not found.
  @retval EFI_UNSUPPORTED        Unsupported browser action.
  @retval EFI_OUT_OF_RESOURCES   Allocation failure for Setup data.
**/
EFI_STATUS
EFIAPI
VtioFormCallBack (
  IN CONST EFI_HII_CONFIG_ACCESS_PROTOCOL *This,
  IN EFI_BROWSER_ACTION                   Action,
  IN EFI_QUESTION_ID                      KeyValue,
  IN UINT8                                Type,
  IN EFI_IFR_TYPE_VALUE                   *Value,
  OUT EFI_BROWSER_ACTION_REQUEST          *ActionRequest
  )
{
  VTIO_SETUP_DATA_STRUCT              *CurrentUserSetupData = 0;
  UINTN                                VarSize = 0;
  EFI_STATUS                           Status;
  EFI_STRING                           RequestString = NULL;
  UINT8                                Index = 0;

  DEBUG ((DEBUG_INFO, "%a start\n", __FUNCTION__));

  ///
  /// No action to perform on Action Changing
  ///
  if (Action == EFI_BROWSER_ACTION_CHANGING) {
    return EFI_SUCCESS;
  }

  ///
  /// Initializations on form open
  ///
  if (Action == EFI_BROWSER_ACTION_FORM_OPEN) {
    return SdevXhciAcpiPathNameUpdate ();
  }

  ///
  /// No action to perform on Action Changed
  ///
  if (Action != EFI_BROWSER_ACTION_CHANGED) {
    return EFI_UNSUPPORTED;
  }

  VarSize               = sizeof (VTIO_SETUP_DATA_STRUCT);
  CurrentUserSetupData  = AllocatePool (VarSize);
  ASSERT (CurrentUserSetupData != NULL);

  if (CurrentUserSetupData == NULL) {
    return EFI_OUT_OF_RESOURCES;
  }

  ///
  /// GetBrowserData by VarStore Name (VtioCfg)
  ///
  Status = HiiGetBrowserData (&gVtioSetupGuid, VTIO_CFG_VARIABLE_NAME, VarSize, (UINT8 *) CurrentUserSetupData);
  ASSERT_EFI_ERROR (Status);
  if (Status != TRUE) {
    FreePool (CurrentUserSetupData);
    return EFI_NOT_FOUND;
  }

  switch (KeyValue) {
    case KEY_SdevXhciAcpiPathNameDevice1:
      ///
      /// Update xHCI ACPI Path Name
      /// Ensure last entry is NULL terminator
      ///
      CurrentUserSetupData->SdevXhciAcpiPathNameDevice1[48] = 0x00;

      ///
      /// Update xHCI ACPI Path String Length
      ///
      if (CurrentUserSetupData->SdevXhciAcpiPathNameDevice1[0] == 0x0) {
        CurrentUserSetupData->SdevXhciAcpiPathStringLength[0] = 0;
      } else {
        Index = 0;
        while (CurrentUserSetupData->SdevXhciAcpiPathNameDevice1[Index] != 0x0) {
          Index++;
        }
        CurrentUserSetupData->SdevXhciAcpiPathStringLength[0] = Index + 1;
      }

      RequestString = HiiConstructRequestString (RequestString, OFFSET_OF (VTIO_SETUP_DATA_STRUCT, SdevXhciAcpiPathStringLength), sizeof (CurrentUserSetupData->SdevXhciAcpiPathStringLength));
      RequestString = HiiConstructRequestString (RequestString, OFFSET_OF (VTIO_SETUP_DATA_STRUCT, SdevXhciAcpiPathNameDevice1), sizeof (CurrentUserSetupData->SdevXhciAcpiPathNameDevice1));
      if (RequestString != NULL) {
        VarSize = sizeof (VTIO_SETUP_DATA_STRUCT);
        Status = HiiSetBrowserData (&gVtioSetupGuid, VTIO_CFG_VARIABLE_NAME, VarSize, (UINT8 *) CurrentUserSetupData, RequestString);
        ASSERT_EFI_ERROR (Status);
        FreePool (RequestString);
        if (Status != TRUE) {
          FreePool (CurrentUserSetupData);
          Status = EFI_NOT_FOUND;
        }
      }
      Status = EFI_SUCCESS;
      break;

    case KEY_SdevXhciAcpiPathNameDevice2:
      ///
      /// Update xHCI ACPI Path Name
      /// Ensure last entry is NULL terminator
      ///
      CurrentUserSetupData->SdevXhciAcpiPathNameDevice2[48] = 0x00;

      ///
      /// Update xHCI ACPI Path String Length
      ///
      if (CurrentUserSetupData->SdevXhciAcpiPathNameDevice2[0] == 0x0) {
        CurrentUserSetupData->SdevXhciAcpiPathStringLength[1] = 0;
      } else {
        Index = 0;
        while (CurrentUserSetupData->SdevXhciAcpiPathNameDevice2[Index] != 0x0) {
          Index++;
        }
        CurrentUserSetupData->SdevXhciAcpiPathStringLength[1] = Index + 1;
      }

      RequestString = HiiConstructRequestString (RequestString, OFFSET_OF (VTIO_SETUP_DATA_STRUCT, SdevXhciAcpiPathStringLength), sizeof (CurrentUserSetupData->SdevXhciAcpiPathStringLength));
      RequestString = HiiConstructRequestString (RequestString, OFFSET_OF (VTIO_SETUP_DATA_STRUCT, SdevXhciAcpiPathNameDevice2), sizeof (CurrentUserSetupData->SdevXhciAcpiPathNameDevice2));
      if (RequestString != NULL) {
        VarSize = sizeof (VTIO_SETUP_DATA_STRUCT);
        Status = HiiSetBrowserData (&gVtioSetupGuid, VTIO_CFG_VARIABLE_NAME, VarSize, (UINT8 *) CurrentUserSetupData, RequestString);
        ASSERT_EFI_ERROR (Status);
        FreePool (RequestString);
        if (Status != TRUE) {
          FreePool (CurrentUserSetupData);
          Status = EFI_NOT_FOUND;
        }
      }
      Status = EFI_SUCCESS;
      break;
  default:
    Status = EFI_UNSUPPORTED;
  }

  FreePool (CurrentUserSetupData);

  return Status;
}

/**
  See UEFI spec for the general meaning of ExtractConfig function.
  ExtractConfig function for VtioSetup driver

  @param[in]  This               Points to the EFI_HII_CONFIG_ACCESS_PROTOCOL.
  @param[in]  Request            A null-terminated Unicode string in <ConfigRequest> format.
  @param[out] Progress           On return, points to a character in the Request string.
                                 Points to the string's null terminator if request was successful.
                                 Points to the most recent '&' before the first failing name/value pair (or
                                 the beginning of the string if the failure is in the first name/value pair)
                                 if the request was not successful.
  @param[out] Results            A null-terminated Unicode string in <ConfigAltResp> format which has
                                 all values filled in for the names in the Request string. String to
                                 be allocated by the called function.

  @retval EFI_SUCCESS            The Results is filled with the requested values.
  @retval EFI_OUT_OF_RESOURCES   Not enough memory to store the results.
  @retval EFI_INVALID_PARAMETER  Request is illegal syntax, or unknown name.
  @retval EFI_NOT_FOUND          Routing data doesn't match any storage in this driver.
**/
EFI_STATUS
EFIAPI
VtioFormExtractConfig (
  IN CONST EFI_HII_CONFIG_ACCESS_PROTOCOL   *This,
  IN CONST EFI_STRING                       Request,
  OUT EFI_STRING                            *Progress,
  OUT EFI_STRING                            *Results
  )
{
  EFI_STATUS                                Status;
  UINTN                                     BufferSize;
  EFI_STRING                                ConfigRequest;
  VTIO_SETUP_DATA_STRUCT                    lVtioSetupData;

  DEBUG ((DEBUG_INFO, "%a start\n", __FUNCTION__));
  ZeroMem (&lVtioSetupData, sizeof (VTIO_SETUP_DATA_STRUCT));

  // Check for valid parameters
  if (Progress == NULL || Results == NULL) {
    return EFI_INVALID_PARAMETER;
  }

  // Initialize the local variables.
  ConfigRequest = NULL;
  *Progress = Request;

  // Get Buffer Storage data from EFI variable.
  // Try to get the current setting from variable.
  BufferSize = sizeof (VTIO_SETUP_DATA_STRUCT);

  Status = gRT->GetVariable (
                VTIO_CFG_VARIABLE_NAME,
                &gVtioSetupGuid,
                NULL,
                &BufferSize,
                &lVtioSetupData
                );

  ShowConfig(&lVtioSetupData);

  if (EFI_ERROR (Status)) {
    return EFI_NOT_FOUND;
  }

  if (lVtioSetupData.VtioSupport == 1) {
    DEBUG ((DEBUG_INFO, "Overriding defaults if VTIO was previously enabled\n"));
    // Check routing data in <ConfigHdr>.
    // Note: if only one Storage is used, then this checking could be skipped.
    if (!HiiIsConfigHdrMatch (Request, &gVtioSetupGuid, NULL)) {
      return EFI_NOT_FOUND;
    }
    // Set Request to the unified request string.
    ConfigRequest = Request;
    // Convert buffer data to <ConfigResp> by helper function BlockToConfig()
    Status = mHiiConfigRouting->BlockToConfig (
                                 mHiiConfigRouting,
                                 ConfigRequest,
                                 (UINT8 *) &lVtioSetupData,
                                 BufferSize,
                                 Results, Progress
                                 );
  } else {
    return EFI_NOT_FOUND;
  }

  return EFI_SUCCESS;
}

/**
  See UEFI spec for the general meaning of RouteConfig function.
  RouteConfig function for VtioSetup driver

  @param[in]  This               Points to the EFI_HII_CONFIG_ACCESS_PROTOCOL.
  @param[in]  Configuration      A null-terminated Unicode string in <ConfigResp>
                                 format.
  @param[out] Progress           A pointer to a string filled in with the offset of
                                 the most recent '&' before the first failing
                                 name/value pair (or the beginning of the string if
                                 the failure is in the first name/value pair) or
                                 the terminating NULL if all was successful.

  @retval EFI_SUCCESS            The Results is processed successfully.
  @retval EFI_INVALID_PARAMETER  Configuration is NULL.
  @retval EFI_NOT_FOUND          Routing data doesn't match any storage in this
                                 driver.
**/
EFI_STATUS
EFIAPI
VtioFormRouteConfig (
  IN CONST EFI_HII_CONFIG_ACCESS_PROTOCOL *This,
  IN CONST EFI_STRING                     Configuration,
  OUT EFI_STRING                          *Progress
  )
{
  EFI_STATUS                   Status;
  VTIO_SETUP_DATA_STRUCT       VtioSetupData;
  UINTN                        VariableSize;
  UINT32                       VtioSetupVarAttr;

  DEBUG ((DEBUG_INFO, "%a start\n", __FUNCTION__));

  VariableSize = sizeof(VTIO_SETUP_DATA_STRUCT);

  Status = mHiiConfigRouting->ConfigToBlock (mHiiConfigRouting, Configuration, (UINT8 *) &VtioSetupData, &VariableSize, Progress);

  if (EFI_ERROR (Status)) {
    DEBUG ((DEBUG_ERROR, "VTIO: Error observed while fetching data from HiiConfigRouting. Status = %d\n", Status));
    return Status;
  }

  CopyMem (&gVtioSetupData, &VtioSetupData, sizeof (VTIO_SETUP_DATA_STRUCT));

  VariableSize = sizeof(VTIO_SETUP_DATA_STRUCT);
  VtioSetupVarAttr = EFI_VARIABLE_BOOTSERVICE_ACCESS | EFI_VARIABLE_NON_VOLATILE;
  Status = gRT->SetVariable (
                  VTIO_CFG_VARIABLE_NAME,
                  &gVtioSetupGuid,
                  VtioSetupVarAttr,
                  VariableSize,
                  &gVtioSetupData
                  );
  if (EFI_ERROR (Status)) {
    DEBUG ((DEBUG_ERROR, "VTIO: Error observed while setting struct in RouteConfig. Status = %d\n", Status));
    return Status;
  }

  ShowConfig (&gVtioSetupData);

  return Status;
}

/**
  Driver's entry point. Checks if VTIO is supported and publishes
  setup formset into setup browser.

  @param[in] ImageHandle      The firmware allocated handle for the EFI image.
  @param[in] SystemTable      A pointer to the EFI System Table.

  @retval EFI_SUCCESS         VTIO driver initialized successfully
  @retval EFI_UNSUPPORTED     Feature is not supported by the FW
  @retval Others              VTIO driver initialization failed
**/
EFI_STATUS
EFIAPI
VtioSetupEntry (
  IN EFI_HANDLE        ImageHandle,
  IN EFI_SYSTEM_TABLE* SystemTable
  )
{
  EFI_HII_HANDLE               VtioHiiHandle;
  EFI_STATUS                   Status;
  EFI_HANDLE                   DriverHandle = NULL;
  UINTN                        VariableSize = 0;
  UINT32                       VtioSetupVarAttr;

  DEBUG ((DEBUG_INFO, "%a start\n", __FUNCTION__));

  VariableSize = sizeof (VTIO_SETUP_DATA_STRUCT);
  // Check if VtioSetup variable present in EFI variables
  Status = gRT->GetVariable (
                  VTIO_CFG_VARIABLE_NAME,
                  &gVtioSetupGuid,
                  &VtioSetupVarAttr,
                  &VariableSize,
                  &gVtioSetupData
                  );

  if (EFI_ERROR (Status)) {
    // Create EFI variable
    DEBUG ((DEBUG_INFO, "VTIO: EFI variable not found creating one. Status = %d\n", Status));
    VtioSetupVarAttr = EFI_VARIABLE_BOOTSERVICE_ACCESS | EFI_VARIABLE_NON_VOLATILE;
    VariableSize = sizeof (VTIO_SETUP_DATA_STRUCT);
    Status = gRT->SetVariable (
                    VTIO_CFG_VARIABLE_NAME,
                    &gVtioSetupGuid,
                    VtioSetupVarAttr,
                    VariableSize,
                    &gVtioSetupData
                    );
    if (EFI_ERROR (Status)) {
      DEBUG ((DEBUG_ERROR, "VTIO: Error in setting variable. Status = %d\n", Status));
      return Status;
    }
  }

  PcdSet64S(PcdVtioSetupDataPtr, (UINT64)&gVtioSetupData);

  gVtioSetupMenuCallbackProtocol.ExtractConfig = VtioFormExtractConfig;
  gVtioSetupMenuCallbackProtocol.RouteConfig   = VtioFormRouteConfig;
  gVtioSetupMenuCallbackProtocol.Callback      = VtioFormCallBack;

  //
  // Locate required Hii protocols
  //
  Status = gBS->LocateProtocol (
                  &gEfiHiiConfigRoutingProtocolGuid,
                  NULL,
                  (VOID **) &mHiiConfigRouting
                  );
  ASSERT_EFI_ERROR (Status);
  if (EFI_ERROR (Status)) {
    return Status;
  }

  //
  // Install Device Path Protocol and Config Access protocol to driver handle
  //
  Status = gBS->InstallMultipleProtocolInterfaces (
                  &DriverHandle,
                  &gEfiDevicePathProtocolGuid,
                  &gVtioSetupMenuHiiVendorDevicePath,
                  &gEfiHiiConfigAccessProtocolGuid,
                  &gVtioSetupMenuCallbackProtocol,
                  NULL
                  );
  ASSERT_EFI_ERROR (Status);
  if (EFI_ERROR (Status)) {
    return Status;
  }
  //
  // Publish our HII data
  //
  VtioHiiHandle = HiiAddPackages (
                     &gVtioSetupGuid,
                     DriverHandle,
                     VtioSetupStrings,
                     VtioSetupVfrBin,
                     NULL
                     );
  ASSERT (VtioHiiHandle != NULL);
  if (VtioHiiHandle == NULL) {
    return EFI_DEVICE_ERROR;
  }
  return EFI_SUCCESS;
}
