/** @file
  This file abstracts Bdat Access Handler Protocol.

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 1999 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/
#ifndef _BDAT_ACCESS_PROTOCOL_H_
#define _BDAT_ACCESS_PROTOCOL_H_

/**
  BDAT access protocol - For accessing some data generated by MRC or PCIe modules.
**/
typedef struct {
  UINTN bdat;
} BDAT_ACCESS_PROTOCOL;

extern EFI_GUID gBdatAccessGuid;

#endif
