//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//

/**@file

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2023 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification
**/

//
// Define DTBT NVS Area operation region.
//
#ifndef _D_TBT_NVS_AREA_DEF_H_
#define _D_TBT_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  UINT8    DiscreteTbtSupport;                      ///< Offset 0       Thunderbolt (TM) support
  UINT8    RootportSelected0;                       ///< Offset 1       Root port Selected by the User
  UINT8    RootportSelected0Type;                   ///< Offset 2       Root port Type
  UINT8    RootportAcpiNumber0;                     ///< Offset 3       Number within Root port ACPI name
  UINT32   DTbtWakeGpioPin0;                        ///< Offset 4       DTBT Wake GPIO pin
  UINT8    RootportSelected1;                       ///< Offset 8       Root port Selected by the User
  UINT8    RootportSelected1Type;                   ///< Offset 9       Root port Type
  UINT8    RootportAcpiNumber1;                     ///< Offset 10      Number within Root port ACPI name
  UINT32   DTbtWakeGpioPin1;                        ///< Offset 11      DTBT Wake GPIO pin
  UINT8    RootportEnabled0;                        ///< Offset 15      Root port Enabled by the User
  UINT8    RootportEnabled1;                        ///< Offset 16      Root port Enabled by the User
  UINT8    DTbtRtd3;                                ///< Offset 17      DTBT Rtd3.
  UINT16   DTbtRtd3OffDelay;                        ///< Offset 18      DTBT RTD3 Off delay in ms.
  UINT8    DTbtRtd3ClkReq;                          ///< Offset 20      Enable DTBT RTD3 CLKREQ mask.
  UINT16   DTbtRtd3ClkReqDelay;                     ///< Offset 21      DTBT RTD3 CLKREQ mask delay.
  UINT8    Usb4ClassOption;                         ///< Offset 23      Indicator of USB4 Host Router Class Code for loading USB4 driver
} DTBT_NVS_AREA;

#pragma pack(pop)
#endif
