/** @file
  USBC Capsule Mapping Table

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2023 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/

#include <Uefi.h>
#include <Usb4Debug/Usb4LogMappingEntry.h>
#include "UsbCCapsuleLogEvents.h"

//
// USBC Capsule Log string mapping table based on USBC Capsule Log Event ID.
// Log Event ID is used as index for string mapping table look up
// Log Event ID of mapping entry must align with its entry index in Log Mapping Table.
// Event ID definition change may be required if any Log mapping entry is removed.
// Otherwise, Event ID of mapping entry may not align with the mapping entry index.
//
const USB4_LOG_MAPPING_ENTRY  mUsbCCapsuleLogMappingTable [] = {
  // UsbC Retimer Capsule - PD Drive/Restore
  { USBC_RETIMER_CAPSULE_EVT_CODE_PD_DRIVE_START, USBC_RETIMER_CAPSULE_STR_ID_PD_DRIVE_START},
  { USBC_RETIMER_CAPSULE_EVT_CODE_PD_RESTORE_START, USBC_RETIMER_CAPSULE_STR_ID_PD_RESTORE_START},
  { USBC_RETIMER_CAPSULE_EVT_CODE_DRIVE_PD_CHANGE_MODE_FAIL, USBC_RETIMER_CAPSULE_STR_ID_DRIVE_PD_CHANGE_MODE_FAIL},
  { USBC_RETIMER_CAPSULE_EVT_CODE_RESTORE_PD_CHANGE_MODE_FAIL, USBC_RETIMER_CAPSULE_STR_ID_RESTORE_PD_CHANGE_MODE_FAIL},
  { USBC_RETIMER_CAPSULE_EVT_CODE_DRIVE_PD_FIRST_GET_MODE_FAIL, USBC_RETIMER_CAPSULE_STR_ID_DRIVE_PD_FIRST_GET_MODE_FAIL},
  { USBC_RETIMER_CAPSULE_EVT_CODE_DRIVE_PD_ALREADY_IN_UPDATE_MODE, USBC_RETIMER_CAPSULE_STR_ID_DRIVE_PD_ALREADY_IN_UPDATE_MODE},
  { USBC_RETIMER_CAPSULE_EVT_CODE_RESTORE_PD_ALREADY_IN_UPDATE_MODE, USBC_RETIMER_CAPSULE_STR_ID_RESTORE_PD_ALREADY_IN_UPDATE_MODE},
  { USBC_RETIMER_CAPSULE_EVT_CODE_DRIVE_PD_SET_MODE_FAIL, USBC_RETIMER_CAPSULE_STR_ID_DRIVE_PD_SET_MODE_FAIL},
  { USBC_RETIMER_CAPSULE_EVT_CODE_DRIVE_PD_SECOND_GET_MODE_FAIL, USBC_RETIMER_CAPSULE_STR_ID_DRIVE_PD_SECOND_GET_MODE_FAIL},
  { USBC_RETIMER_CAPSULE_EVT_CODE_DRIVE_PD_SET_MODE_NOT_COMPLETE, USBC_RETIMER_CAPSULE_STR_ID_DRIVE_PD_SET_MODE_NOT_COMPLETE},
  { USBC_RETIMER_CAPSULE_EVT_CODE_DRIVE_PD_ENTER_FW_UPDATE_MODE, USBC_RETIMER_CAPSULE_STR_ID_DRIVE_PD_ENTER_FW_UPDATE_MODE},
  { USBC_RETIMER_CAPSULE_EVT_CODE_RESTORE_PD_ENTER_FW_UPDATE_MODE, USBC_RETIMER_CAPSULE_STR_ID_RESTORE_PD_ENTER_FW_UPDATE_MODE},
  { USBC_RETIMER_CAPSULE_EVT_CODE_PD_DRIVE_END, USBC_RETIMER_CAPSULE_STR_ID_PD_DRIVE_END},
  { USBC_RETIMER_CAPSULE_EVT_CODE_PD_RESTORE_END, USBC_RETIMER_CAPSULE_STR_ID_PD_RESTORE_END},
  { USBC_RETIMER_CAPSULE_EVT_CODE_DRIVE_PD_FIRST_GET_MODE_EC_STATUS, USBC_RETIMER_CAPSULE_STR_ID_DRIVE_PD_FIRST_GET_MODE_EC_STATUS},
  { USBC_RETIMER_CAPSULE_EVT_CODE_RESTORE_PD_FIRST_GET_MODE_EC_STATUS, USBC_RETIMER_CAPSULE_STR_ID_RESTORE_PD_FIRST_GET_MODE_EC_STATUS},
  { USBC_RETIMER_CAPSULE_EVT_CODE_DRIVE_PD_SECOND_GET_MODE_EC_STATUS, USBC_RETIMER_CAPSULE_STR_ID_DRIVE_PD_SECOND_GET_MODE_EC_STATUS},
  { USBC_RETIMER_CAPSULE_EVT_CODE_RESTORE_PD_SECOND_GET_MODE_EC_STATUS, USBC_RETIMER_CAPSULE_STR_ID_RESTORE_PD_SECOND_GET_MODE_EC_STATUS},
  // UsbC Retimer Capsule - TBT Command
  { USBC_RETIMER_CAPSULE_EVT_CODE_UPDATE_RETIMER_PAYLOAD, USBC_RETIMER_CAPSULE_STR_ID_UPDATE_RETIMER_PAYLOAD},
  { USBC_RETIMER_CAPSULE_EVT_CODE_TBTCMD_SEND_ENUM_CMD, USBC_RETIMER_CAPSULE_STR_ID_TBTCMD_SEND_ENUM_CMD},
  { USBC_RETIMER_CAPSULE_EVT_CODE_TBTCMD_SEND_ENUM_CMD_FAIL, USBC_RETIMER_CAPSULE_STR_ID_TBTCMD_SEND_ENUM_CMD_FAIL},
  { USBC_RETIMER_CAPSULE_EVT_CODE_TBTCMD_SEND_LSUP_CMD, USBC_RETIMER_CAPSULE_STR_ID_TBTCMD_SEND_LSUP_CMD},
  { USBC_RETIMER_CAPSULE_EVT_CODE_TBTCMD_SEND_LSUP_CMD_FAIL, USBC_RETIMER_CAPSULE_STR_ID_TBTCMD_SEND_LSUP_CMD_FAIL},
  { USBC_RETIMER_CAPSULE_EVT_CODE_TBTCMD_SEND_USUP_CMD, USBC_RETIMER_CAPSULE_STR_ID_TBTCMD_SEND_USUP_CMD},
  { USBC_RETIMER_CAPSULE_EVT_CODE_TBTCMD_SEND_USUP_CMD_FAIL, USBC_RETIMER_CAPSULE_STR_ID_TBTCMD_SEND_USUP_CMD_FAIL},
  { USBC_RETIMER_CAPSULE_EVT_CODE_TBTCMD_SEND_LSEN_CMD, USBC_RETIMER_CAPSULE_STR_ID_TBTCMD_SEND_LSEN_CMD},
  { USBC_RETIMER_CAPSULE_EVT_CODE_TBTCMD_SEND_LSEN_CMD_FAIL, USBC_RETIMER_CAPSULE_STR_ID_TBTCMD_SEND_LSEN_CMD_FAIL},
  // UsbC dTBT Capsule
  { USBC_DTBT_CAPSULE_EVT_CODE_DTBT_UPDATE_START, USBC_DTBT_CAPSULE_STR_ID_DTBT_UPDATE_START},
  { USBC_DTBT_CAPSULE_EVT_CODE_DTBT_UPDATE_INFO, USBC_DTBT_CAPSULE_STR_ID_DTBT_UPDATE_INFO},
  { USBC_DTBT_CAPSULE_EVT_CODE_CREATE_DTBT_DEV_INST, USBC_DTBT_CAPSULE_STR_ID_CREATE_DTBT_DEV_INST},
  { USBC_DTBT_CAPSULE_EVT_CODE_CREATE_DTBT_DEV_INST_FAIL_STATUS, USBC_DTBT_CAPSULE_STR_ID_CREATE_DTBT_DEV_INST_FAIL_STATUS},
  { USBC_DTBT_CAPSULE_EVT_CODE_UPDATE_DTBT_NVM_FW, USBC_DTBT_CAPSULE_STR_ID_UPDATE_DTBT_NVM_FW},
  { USBC_DTBT_CAPSULE_EVT_CODE_UPDATE_DTBT_NVM_FW_FAIL_STATUS, USBC_DTBT_CAPSULE_STR_ID_UPDATE_DTBT_NVM_FW_FAIL_STATUS},
};

UINT32 mUsbCCapsuleLogMappingEntries = (UINT32) (sizeof (mUsbCCapsuleLogMappingTable) / sizeof (USB4_LOG_MAPPING_ENTRY));