/** @file
  USBC Capsule Log Event ID Definitions

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2024 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/

#ifndef _USBC_CAPSULE_EVT_ID_H_
#define _USBC_CAPSULE_EVT_ID_H_

#include <Uefi.h>

typedef enum {
  ///
  /// EVT_ID - FmpDeviceLibTbtRetimer
  ///
  EVT_ID_GETVERSION_FAIL_GET_SETUP_VARIABLE = 0,
  EVT_ID_CHECKIMAGE_UPDATABLE_NULL,
  EVT_ID_CHECKIMAGE_POINTER_NULL,
  EVT_ID_CHECKIMAGE_PAYLOAD_SIGNATURE_NOT_DETECTED,
  EVT_ID_CHECKIMAGE_PAYLOAD_HEADER_ZERO,
  EVT_ID_CHECKIMAGE_PAYLOAD_SIZE_TOO_SMALL,
  EVT_ID_CHECKIMAGE_PAYLOAD_OUT_BOUNDS,
  EVT_ID_CONSTRUCT_INSTANCE_TOTAL_PAYLOAD,
  EVT_ID_CONSTRUCT_INSTANCE_MAX_INSTANCE_TOO_SMALL,
  EVT_ID_CONSTRUCT_INSTANCE_ADDRESS_BUS_DEVICE,
  EVT_ID_CONSTRUCT_INSTANCE_ADDRESS_FUNC,
  EVT_ID_CONSTRUCT_INSTANCE_ADDRESS_PORT_INDEX,
  EVT_ID_CONSTRUCT_INSTANCE_PCIE_TYPE_RP,
  EVT_ID_CONSTRUCT_INSTANCE_FIRMWARETYPE_ERROR,
  EVT_ID_CONSTRUCT_INSTANCE_CREATE_RETIMER_FAIL,
  EVT_ID_CONSTRUCT_INSTANCE_CREATE_HR_FAIL,
  EVT_ID_FMP_UPDATE_START,
  EVT_ID_FMP_UPDATE_PROGRESS_NULL,
  EVT_ID_FMP_UPDATE_PROGRESS_FAIL,
  EVT_ID_FMP_UPDATE_LOCATE_USBCRETIMER_PROTOCOL_FAIL,
  EVT_ID_FMP_UPDATE_LOCATE_USBCPROGRESS_PROTOCOL_FAIL,
  EVT_ID_FMP_UPDATE_CONSTRUCT_RETIMER_INSTANCE_FAILED,
  EVT_ID_FMP_UPDATE_DISCONNECT_CONTROLLER_START,
  EVT_ID_FMP_UPDATE_DISCONNECT_CONTROLLER_HANDLEINDEX,
  EVT_ID_FMP_UPDATE_SEND_OFFLINEMODE_FAIL,
  EVT_ID_FMP_UPDATE_DRIVE_TBTMODE_START,
  EVT_ID_FMP_UPDATE_DRIVE_TBTMODE_FAIL,
  EVT_ID_FMP_UPDATE_WAIT_FOR_RETIMER_DEVICE,
  EVT_ID_FMP_UPDATE_ASSERT_RETIMER_FP_GPIO,
  EVT_ID_FMP_UPDATE_ASSERT_RETIMER_FP_GPIO_FAILED,
  EVT_ID_FMP_UPDATE_RETIMER_START,
  EVT_ID_FMP_UPDATE_TOTAL_RETIMER_PAYLOAD,
  EVT_ID_FMP_UPDATE_UPDATE_RETIMER_PAYLOAD,
  EVT_ID_FMP_UPDATE_PAYLOAD_OFFSET_SIZE,
  EVT_ID_FMP_UPDATE_INITRETIMERHW_FAIL,
  EVT_ID_FMP_UPDATE_NVM_VERSION,
  EVT_ID_FMP_UPDATE_NVM_VERSION1,
  EVT_ID_FMP_UPDATE_TERMINATE_RETIMER_HW_FAIL,
  EVT_ID_FMP_UPDATE_DEASSERT_RETIMER_FP_GPIO,
  EVT_ID_FMP_UPDATE_DEASSERT_RETIMER_FP_GPIO_FAILED,
  EVT_ID_FMP_UPDATE_RESTORE_TBTMODE_FAIL,
  EVT_ID_FMP_UPDATE_CONNECT_CONTROLLER_USB2HC,
  EVT_ID_FMP_UPDATE_DESTORY_RETIMER_INSTANCE,
  EVT_ID_FMP_UPDATE_END,
  EVT_ID_FMP_DEVICE_LOCK,

  ///
  /// EVT_ID - FmpDeviceLibDiscreteTbt
  ///
  EVT_ID_DTBT_CHECKIMAGE_UPDATABLE_NULL,
  EVT_ID_DTBT_CHECKIMAGE_POINTER_NULL,
  EVT_ID_DTBT_CHECKIMAGE_PAYLOAD_SIGNATURE_UNDETECTED,
  EVT_ID_DTBT_CHECKIMAGE_PAYLOAD_HEADER_ZERO,
  EVT_ID_DTBT_CHECKIMAGE_CHECKIMAGE_PAYLOAD_COUNT_INVALID,
  EVT_ID_DTBT_CHECKIMAGE_CHECKIMAGE_PAYLOAD_SIZE_TOO_SMALL,
  EVT_ID_DTBT_CHECKIMAGE_CHECKIMAGE_PAYLOAD_OUT_BOUNDS,
  EVT_ID_DTBT_FMP_UPDATE_START,
  EVT_ID_DTBT_FMP_UPDATE_PROGRESS_NULL,
  EVT_ID_DTBT_FMP_UPDATE_PROGRESS_FAIL,
  EVT_ID_DTBT_FMP_UPDATE_DTBT_START,
  EVT_ID_DTBT_PAYLOAD_OUT_BOUNDS,
  EVT_ID_DTBT_UPDATE,
  EVT_ID_DTBT_PAYLOAD_OFFSET_SIZE,
  EVT_ID_DTBT_DISCONNECT_CONTROLLER,
  EVT_ID_DTBT_PCIE_TYPE_RP,
  EVT_ID_DTBT_FIRMWARETYPE_ERROR,
  EVT_ID_DTBT_CREATE_DEV_INST,
  EVT_ID_DTBT_INITIALIZE_FAIL,
  EVT_ID_DTBT_UPDATE_NVM_FW,
  EVT_ID_DTBT_INSTANCE_UPDATE_FAIL,
  EVT_ID_DTBT_FMP_UPDATE_END,
  EVT_ID_DTBT_FMP_DEVICE_LOCK,

  ///
  /// EVT_ID - PD Drive/Restore - TbtRetimerNvmUpdateLib
  ///
  ///< TbtRetimerNvmUpdateLib.c - start
  EVT_ID_HR_DEV_COUNT_ZERO,                      ///< CreateHrDevInstance()
  EVT_ID_HR_DEV_ALREADY,
  EVT_ID_HR_DEV_CREATE_START,
  EVT_ID_RT_BDF_ALLOCATE_MEM_FAIL,               ///< CreateRetimerDevInstance()
  EVT_ID_RT_RP_ALLOCATE_MEM_FAIL,
  EVT_ID_RT_DEV_ADDRESS_ERROR,
  EVT_ID_RT_DEV_CREATE_FAIL,
  EVT_ID_CREATE_TBT_ALLOCATE_MEM_FAIL,           ///< CreateTBTDevInstance()
  EVT_ID_CREATE_TBT_DMA_FAIL,
  EVT_ID_READ_NVM_VERSION_ERROR,                 ///< ReadRetimerNvmVersion()
  EVT_ID_READ_NVM_VERSION_INFO,
  EVT_ID_READ_NVM_VERSION_INFO2,
  EVT_ID_UPDATE_RT_GET_VARIABLE_FAIL,            ///< UpdateRetimerNvmInformation()
  EVT_ID_UPDATE_RT_FW_TYPE_UNSUPPORT,
  EVT_ID_UPDATE_RT_INVALID_RETIMER_INDEX,
  EVT_ID_UPDATE_RT_CONFIG_MATCH,
  EVT_ID_UPDATE_RT_CONFIG_NOT_MATCH,
  EVT_ID_UPDATE_RT_SET_VARIABLE_FAIL,
  EVT_ID_INIT_RT_HW_START,                       ///< InitRetimerHW()
  EVT_ID_INIT_RT_HW_GOT_ERROR,
  EVT_ID_INIT_RT_HW_SUCCESS,
  EVT_ID_TERMINATE_START,                        ///< TerminateRetimerHW()
  EVT_ID_TERMINATE_GOT_ERROR,
  EVT_ID_TERMINATE_SUCCESS,
  EVT_ID_UPDATE_NVM_RT_FW_START,                 ///< UpdateRetimerNvmFirmware()
  EVT_ID_UPDATE_NVM_FATAL_ERROR,
  EVT_ID_UPDATE_NVM_WRITE_DATA,
  EVT_ID_UPDATE_NVM_WRITE_SIZE,
  EVT_ID_UPDATE_NVM_WRITE_INFO,
  EVT_ID_UPDATE_NVM_WRITE_INFO2,
  EVT_ID_UPDATE_NVM_ERROR_OFFSET,
  EVT_ID_UPDATE_NVM_WRITE_FINISH,
  EVT_ID_UPDATE_NVM_WRITE_IM_ERROR,
  EVT_ID_UPDATE_NVM_DEV_ERROR,
  EVT_ID_UPDATE_NVM_AUTH_SUCCESS,
  EVT_ID_UPDATE_DTBT_START,                       ///< UpdateDiscreteTbtNvmFirmware()
  EVT_ID_UPDATE_DTBT_FW_AUTH_SUCCESS,
  EVT_ID_TBT_PD_GET_MODE_FAIL,                    ///< TbtPdRetimerFwUpdateModeChange()
  EVT_ID_TBT_PD_DRIVE_FIRST_GET_MODE,
  EVT_ID_TBT_PD_RESTORE_PD_FIRST_GET_MODE,
  EVT_ID_TBT_PD_DRIVE_SECOND_GET_MODE,
  EVT_ID_TBT_PD_RESTORE_PD_SECOND_GET_MODE,
  EVT_ID_TBT_PD_CONTROLLER_ALREADY,
  EVT_ID_TBT_PD_CONTROLLER_EXITED,
  EVT_ID_TBT_PD_SET_MODE_FAIL,
  EVT_ID_TBT_PD_CONTROLLER_SET_MODE_INCOMPLETE,
  EVT_ID_TBT_PD_CONTROLLER_UPDATE_MODE_STATUS,
  EVT_ID_TBT_PD_CONTROLLER_UPDATE_MODE_ENTER,
  EVT_ID_TBT_PD_RESTORE_CONTROLLER_MODE_STATUS,
  EVT_ID_TBT_PD_CONTROLLER_UPDATE_MODE_EXIT,
  EVT_ID_DRIVE_START,                             ///< DriveToFwUpdateMode()
  EVT_ID_DRIVE_GUID_CHECK_FAILED,
  EVT_ID_DRIVE_USBC_RT_UNSUPPORT,
  EVT_ID_DRIVE_CHANGE_MODE_FAIL,
  EVT_ID_DRIVE_END,
  EVT_ID_RESTORE_START,                           ///< RestoreToOriginalMode()
  EVT_ID_RESTORE_GUID_CHECK_FAILED,
  EVT_ID_RESTORE_USBC_RT_UNSUPPORT,
  EVT_ID_RESTORE_CHANGE_MODE_FAIL,
  EVT_ID_RESTORE_END,
  ///< TbtRetimerNvmUpdateLib.c - end

  ///
  /// EVT_ID - Force power on YFL router
  ///
  ///< TbtNvmDrvYflRouter.c - start
  EVT_ID_YFL_FORCE_PWR_PERF,
  EVT_ID_YFL_FORCE_PWR_DISABLE,
  EVT_ID_YFL_FORCE_PWR_PCI_IO_NULL,
  EVT_ID_YFL_FORCE_PWR_PARAMETER_NULL,
  EVT_ID_YFL_FORCE_PWR_READ_PCIE_REG_ERROR,
  EVT_ID_YFL_TBT_CONTROLLER_READY,
  EVT_ID_YFL_TBT_CONTROLLER_NOT_READY,
  EVT_ID_YFL_FORCE_PWR_WAIT_ERROR,
  ///< TbtNvmDrvYflRouter.c - end

  ///
  /// EVT_ID - TBT Command
  ///
  ///< TbtNvmDrvRetimerThruHr.c - start
  EVT_ID_TBTCMD_WRITE_IECS_LENGTH,
  EVT_ID_TBTCMD_WRITE_IECS_REG_NUM_LENGTH,
  EVT_ID_TBTCMD_WRITE_IECS_DATA_ERROR,
  EVT_ID_TBTCMD_WRITE_IECS_USB4_REG,
  EVT_ID_TBTCMD_WRITE_IECS_FAIL,
  EVT_ID_TBTCMD_WRITE_IECS_REGNUM_DATA,
  EVT_ID_TBTCMD_WRITE_IECS_LENGTH_STATUS,
  EVT_ID_TBTCMD_WRITE_IECS_RETRY_FAIL,
  EVT_ID_TBTCMD_WRITE_IECS_RETRY_REG,
  EVT_ID_TBTCMD_WRITE_IECS_OFFSET_CMD,
  EVT_ID_TBTCMD_READ_IECS_REG,
  EVT_ID_TBTCMD_READ_IECS_DATA_ERROR,
  EVT_ID_TBTCMD_READ_IECS_RETRYCNT,
  EVT_ID_TBTCMD_READ_IECS_OFFSET_REG,
  EVT_ID_TBTCMD_READ_IECS_OPERATION_FAIL,
  EVT_ID_TBTCMD_CAPABILITY_PARSING,
  EVT_ID_TBTCMD_CAPABILITY_PARSING_DEV_NULL,
  EVT_ID_TBTCMD_CAPABILITY_PARSING_READ_DATA,
  EVT_ID_TBTCMD_CAPABILITY_PARSING_READ_ERROR,
  EVT_ID_TBTCMD_CAPABILITY_PARSING_READ_NEXT,
  EVT_ID_TBTCMD_CAPABILITY_USB4_FOUND_ERROR,
  EVT_ID_TBTCMD_CAPABILITY_ID,
  EVT_ID_TBTCMD_CAPABILITY_USB4_OFFSET,
  EVT_ID_TBTCMD_CAPABILITY_PARSING_FAIL,
  EVT_ID_TBTCMD_SEND_ENUM_CMD,
  EVT_ID_TBTCMD_SEND_ENUM_CMD_FAIL,
  EVT_ID_TBTCMD_SEND_LSUP_CMD,
  EVT_ID_TBTCMD_SEND_LSUP_CMD_FAIL,
  EVT_ID_TBTCMD_SEND_USUP_CMD,
  EVT_ID_TBTCMD_SEND_USUP_CMD_FAIL,
  EVT_ID_TBTCMD_DTOR_CALL,
  EVT_ID_TBTCMD_THRU_ALLOCATE_MEM_FAIL,
  EVT_ID_TBTCMD_DEV_ALLOCATE_MEM_FAIL,
  EVT_ID_TBTCMD_CREATE_DMA_FAIL,
  EVT_ID_TBTCMD_RT_CAPABILITY_PARSING_FAIL,
  ///< TbtNvmDrvRetimerThruHr.c - end

  ///< TbtNvmDrvRetimerThruHrHelpers.c - start
  EVT_ID_TBTCMD_WAIT_CMD_READ_DATA,
  EVT_ID_TBTCMD_WAIT_CMD_READ_REG_FAIL,
  EVT_ID_TBTCMD_WAIT_CMD_READ_TRAN_DATA,
  EVT_ID_TBTCMD_WAIT_CMD_LC_STUCK_ERROR,
  EVT_ID_TBTCMD_WAIT_CMD_LC_DATA,
  EVT_ID_TBTCMD_WAIT_CMD_LC_DATA2,
  EVT_ID_TBTCMD_WAIT_CMD_LC_TIMEOUT,
  EVT_ID_TBTCMD_WAIT_CMD_LC_INVALID,
  EVT_ID_TBTCMD_WAIT_CMD_RETRY_STATUS,
  EVT_ID_TBTCMD_LOCAL_LC_WRITE_ERROR,
  EVT_ID_TBTCMD_LOCAL_LC_WRITE_USB4_CAP,
  EVT_ID_TBTCMD_LOCAL_LC_WRITE_CMD_ERROR,
  EVT_ID_TBTCMD_LOCAL_LC_WAIT_CMD_COMPLETE_ERROR,
  EVT_ID_TBTCMD_LOCAL_LC_CMD_TIMEOUT,
  EVT_ID_TBTCMD_LOCAL_LC_REPORTED_ERROR,
  EVT_ID_TBTCMD_SEND_ENUM_THRU_CMD,
  EVT_ID_TBTCMD_SEND_ENUM_THRU_CMD_FAIL,
  EVT_ID_TBTCMD_SEND_ENUM_THRU_CMD_SUCCESS,
  EVT_ID_TBTCMD_SEND_USUP_RETIMER_INDEX,
  EVT_ID_TBTCMD_SEND_USUP_FAIL,
  EVT_ID_TBTCMD_SEND_USUP_SUCCESS,
  EVT_ID_TBTCMD_SEND_LSUP_RETIMER_INDEX,
  EVT_ID_TBTCMD_SEND_LSUP_SUCCESS,
  EVT_ID_TBTCMD_SEND_LSUP_FAIL,
  EVT_ID_TBTCMD_SEND_LSEN_CMD,
  EVT_ID_TBTCMD_SEND_LSEN_CMD1,
  EVT_ID_TBTCMD_SEND_LSEN_CMD_FAIL,
  ///< TbtNvmDrvRetimerThruHrHelpers.c - end

  ///
  /// EVT_ID - Driver ready
  ///
  ///< TbtNvmDrvHr.c - start
  EVT_ID_TBT_DRV_GEN_CRC_FAIL,
  EVT_ID_TBT_DRV_RDY_CMD_SEND_FAIL,
  EVT_ID_TBT_DRV_RDY_CMD_RECEIVE_FAIL,
  EVT_ID_TBT_DRV_CMD_SUCCESS,
  EVT_ID_TBT_DRV_WRITE_CIO_REG,
  EVT_ID_TBT_DRV_WRITE_CIO_CONFIG,
  EVT_ID_TBT_DRV_WRITE_CIO_DATA,
  EVT_ID_TBT_DRV_WRITE_ALLOCATE_MEM_ERROR,
  EVT_ID_TBT_DRV_AVOID_BUFFER,
  EVT_ID_TBT_DRV_WRITE_CIO_GEN_CRC_FAIL,
  EVT_ID_TBT_DRV_TRANSMIT_DMA_ERROR,
  EVT_ID_TBT_DRV_RECEIVE_ERROR,
  EVT_ID_TBT_DRV_READ_AVOID_BUFFER,
  EVT_ID_TBT_DRV_READ_CIO_CONFIG,
  EVT_ID_TBT_DRV_READ_CIO_CONFIG2,
  EVT_ID_TBT_DRV_READ_CIO_ALLOCATE_MEM_ERROR,
  EVT_ID_TBT_DRV_READ_CIO_GEN_CRC_FAIL,
  EVT_ID_TBT_DRV_READ_CIO_TRANSMIT_DMA_FAIL,
  EVT_ID_TBT_DRV_READ_CIO_RECEIVE_REG_FAIL,
  EVT_ID_TBT_DRV_READ_CIO_READ_DATA,
  EVT_ID_TBT_DRV_GET_HOST_ROUTER_LIST,            ///< GetTbtHostRouterList()
  EVT_ID_TBT_DRV_HOST_ROUTER_INFO,
  EVT_ID_TBT_DRV_HOST_ROUTER_INFO2,
  EVT_ID_TBT_DRV_HOST_ROUTER_INFO3,
  EVT_ID_TBT_DRV_HOST_ROUTER_INFO4,
  EVT_ID_TBT_DRV_HOST_ROUTER_INFO5,
  EVT_ID_TBT_DRV_ADD_ROUTER_LIST,                 ///< AddTbtHostRouterList()
  EVT_ID_TBT_DRV_ADD_ROUTER_ERROR,
  EVT_ID_TBT_DRV_REMOVE_ROUTER_LIST,              ///< RemoveTbtHostRouterList()
  EVT_ID_TBT_DRV_REMOVE_ROUTER_ERROR,
  EVT_ID_TBT_DRV_DTOR,                            ///< TbtNvmDrvHrDtor()
  EVT_ID_TBT_DRV_CTOR_PROTOCOL_FAIL,              ///< TbtNvmDrvHrCtor()
  EVT_ID_TBT_DRV_CTOR_ALLOCATE_MEM_FAIL,
  EVT_ID_TBT_DRV_CTOR_TYPE_PCH,
  EVT_ID_TBT_DRV_CTOR_TYPE_PCH1,
  EVT_ID_TBT_DRV_CTOR_TYPE_CPU,
  EVT_ID_TBT_DRV_CTOR_TYPE_CPU1,
  EVT_ID_TBT_DRV_CTOR_TYPE_FAIL,
  EVT_ID_TBT_DRV_CTOR_HANDLE_PROTOCOL_FAIL,
  EVT_ID_TBT_DRV_CTOR_PCI_READ_FAIL,
  EVT_ID_TBT_DRV_CTOR_CHECK_USB_FAIL,
  EVT_ID_TBT_DRV_CTOR_PCI_DEV_CLASS,
  EVT_ID_TBT_DRV_CTOR_PCI_DEV_CLASS2,
  EVT_ID_TBT_DRV_CTOR_USB4_PCI,
  EVT_ID_TBT_DRV_CTOR_LOCATION_GET_FAIL,
  EVT_ID_TBT_DRV_CTOR_CONTROLLER,
  EVT_ID_TBT_DRV_CTOR_PCI_INFO,
  EVT_ID_TBT_DRV_CTOR_PCI_INFO2,
  EVT_ID_TBT_DRV_CTOR_PCI_INFO3,
  EVT_ID_TBT_DRV_CTOR_CONTROLLER_FOUND,
  EVT_ID_TBT_DRV_CTOR_NOT_FOUND_FOR_ITBT_RETIMER,
  EVT_ID_TBT_DRV_CTOR_NOT_FOUND_FOR_ITBT_RETIMER2,
  EVT_ID_TBT_DRV_CTOR_NOT_FOUND_FOR_DTBT_RETIMER,
  EVT_ID_TBT_DRV_CTOR_ATTRIBUTES_GET_FAIL,
  EVT_ID_TBT_DRV_CTOR_ATTRIBUTES_SET_FAIL,
  EVT_ID_TBT_DRV_CTOR_FORCE_PWR_ITBT,
  EVT_ID_TBT_DRV_CTOR_PERFORM_PWR_ERROR,
  EVT_ID_TBT_DRV_CTOR_FORCE_PWR_DEV,
  EVT_ID_TBT_DRV_CTOR_INIT_DMA_FAIL,
  EVT_ID_TBT_DRV_HOST_ALLOCATE_MEM_FAIL,
  EVT_ID_TBT_DRV_ITBT_INFO_HOB_NOT_FOUND,
  EVT_ID_TBT_DRV_CM_MODE,
  EVT_ID_TBT_DRV_SEND_DRIVER_RDY_FAIL,
  EVT_ID_TBT_DRV_HR_CTOR_COMPLETE,
  ///< TbtNvmDrvHr.c - end

  ///
  /// EVT_ID - TBT DMA
  ///
  ///< TbtNvmDrvDma.c - start
  EVT_ID_TBT_DRV_DMA_ERROR,                       ///< TbtNvmDrvGetTxBuf()
  EVT_ID_TBT_DRV_DMA_TX_RING_FULL,
  EVT_ID_TBT_DRV_DMA_TX_PACKET_INFO,              ///< TbtNvmDrvInitiateTx()
  EVT_ID_TBT_DRV_DMA_TX_PACKET_INFO2,
  EVT_ID_TBT_DRV_DMA_TX_FRAME_ERROR,
  EVT_ID_TBT_DRV_DMA_RX_PTR_INFO,
  EVT_ID_TBT_DRV_DMA_RX_PTR_INFO2,
  EVT_ID_TBT_DRV_DMA_RX_STALL_ERROR,
  EVT_ID_TBT_DRV_DMA_RX_WAIT_TIMEOUT,
  EVT_ID_TBT_DRV_DMA_RX_WAIT_TIMEOUT2,
  EVT_ID_TBT_DRV_DMA_RX_DESCRIPT,
  EVT_ID_TBT_DRV_DMA_RX_FRAME_INFO,
  EVT_ID_TBT_DRV_DMA_RX_FRAME_INFO2,
  EVT_ID_TBT_DRV_DMA_RX_PTR_INFO_AFTER,
  EVT_ID_TBT_DRV_DMA_RX_RESP_WAIT_TIMEOUT,
  EVT_ID_TBT_DRV_DMA_RX_RECEIVED_ERROR,           ///< TbtNvmDrvRxCfgPkt()
  EVT_ID_TBT_DRV_DMA_RX_RECEIVED_EXP,
  EVT_ID_TBT_DRV_DMA_WRITE_MMIO,                  ///< TbtNvmDrvDmaWriteMmio()
  EVT_ID_TBT_DRV_DMA_READ_MMIO,                   ///< TbtNvmDrvDmaReadMmio()
  EVT_ID_TBT_DRV_DMA_SYMBOL,                      ///< TbtNvmDrvDmaDebugPrint()
  EVT_ID_TBT_DRV_DMA_STATE_PRINT,
  EVT_ID_TBT_DRV_DMA_ARC_DEBUG,
  EVT_ID_TBT_DRV_DMA_TX_RING,
  EVT_ID_TBT_DRV_DMA_TX_RING_TABLE,
  EVT_ID_TBT_DRV_DMA_RX_RING,
  EVT_ID_TBT_DRV_DMA_RX_RING_TABLE,
  EVT_ID_TBT_DRV_DMA_NEWLINE,
  EVT_ID_TBT_DRV_DMA_DTOR,                        ///< TbtNvmDrvDmaDtor()
  EVT_ID_TBT_DRV_DMA_CTOR_ALLOCATE_MEM_FAIL,      ///< TbtNvmDrvDmaCtor()
  EVT_ID_TBT_DRV_DMA_CTOR_ALLOCATE_BUF_FAIL,
  EVT_ID_TBT_DRV_DMA_CTOR_INVALID_FUNCTION_NUMBER,
  EVT_ID_TBT_DRV_DMA_CTOR_USE_PEI_DMA_BUF,
  EVT_ID_TBT_DRV_DMA_CTOR_PEI_DMA_BUF_DOES_NOT_EXIST,
  EVT_ID_TBT_DRV_DMA_CTOR_MAP_FAIL,
  EVT_ID_TBT_DRV_DMA_CTOR_MAP_RETURN,
  EVT_ID_TBT_DRV_DMA_CTOR_INIT_MEM_FAIL,
  ///< TbtNvmDrvDma.c - end

  ///< TbtNvmRetimerDrvHelpers.c - start
  EVT_ID_NVM_IECS_CALL,                           ///< TbtNvmDrvWaitForCmdCpl()
  EVT_ID_NVM_IECS_CHECK_REG,
  EVT_ID_NVM_IECS_READ_GOT_ERROR,
  EVT_ID_NVM_IECS_READ_GOT_ERROR1,
  EVT_ID_NVM_IECS_CMD_TIMEOUT,
  EVT_ID_NVM_IECS_CMD_NOT_SUP,
  EVT_ID_NVM_IECS_READ_CMD_NOT_SUP1,
  EVT_ID_NVM_IECS_CMD_GOT_ERR,
  EVT_ID_NVM_IECS_CMD_GOT_ERR1,
  EVT_ID_NVM_IECS_CMD_READ_GOT_ERR,
  EVT_ID_NVM_TBT_CMD_TIMEOUT,
  EVT_ID_NVM_TBT_CMD_NOT_SUP,
  EVT_ID_NVM_TBT_CMD_DATA_ERR,
  EVT_ID_NVM_TBT_CMD_DATA_ERR1,
  EVT_ID_NVM_SEND_IECS_CMD,                       ///< TbtNvmDrvSendCmd()
  EVT_ID_NVM_WRITE_IECS_CMD_FAIL,
  EVT_ID_NVM_WRITE_IECS_CMD_REG_FAIL,
  EVT_ID_NVM_WRITE_IECS_CMD,
  EVT_ID_NVM_WRITE_BLK_LENGTH,                    ///< TbtNvmDrvDeviceWrBlk()
  EVT_ID_NVM_WRITE_BLK_WDATA_ERROR,
  EVT_ID_NVM_SEND_BLK_CMD_ERROR,
  EVT_ID_NVM_SEND_BLK_OP_CMD_ERROR,
  EVT_ID_NVM_WRITE_BLK_FINISH,
  EVT_ID_NVM_WRITE_OFFSET,                        ///< TbtNvmDrvDeviceWrOffset()
  EVT_ID_NVM_WRITE_DATA_ERROR,
  EVT_ID_NVM_SEND_CMD_ERROR,
  EVT_ID_NVM_WRITE_RG_ERROR,
  EVT_ID_NVM_WRITE_DV_FINISH,
  EVT_ID_SEND_AUTH_COMMAND,                       ///< TbtNvmDrvDeviceExecAuth()
  EVT_ID_IECS_DATA_GOT_ERROR,
  EVT_ID_IECS_CMD_GOT_ERROR,
  EVT_ID_WAIT_AUTH_SECONDS,
  EVT_ID_RT_ENUMERATE_ERROR,
  EVT_ID_AUTH_FAIL,
  EVT_ID_AUTH_IECS_DATA_GOT_ERROR,
  EVT_ID_AUTH_METADATA_FAIL,
  EVT_ID_WRITE_META_REG_ERROR,
  EVT_ID_WRITE_CMD_REG_ERROR,
  EVT_ID_AUTH_WAIT_SECONDS,
  EVT_ID_AUTH_SUCCESS,
  EVT_ID_NVM_READ_DW_OFFSET,                      ///< TbtDrvReadDwFromNvm()
  EVT_ID_WRITE_IECS_ERROR,
  EVT_ID_IECS_CMD_ERROR,
  EVT_ID_IECS_READ_REG_ERROR,
  EVT_ID_IECS_WRITE_REG_ERROR,
  EVT_ID_SEND_CMD_ERROR,
  EVT_ID_READ_DATA_ERROR,
  EVT_ID_READ_DW_OFFSET,
  EVT_ID_NVM_READ_VERSION,                        ///< TbtDrvReadNvmVersion()
  EVT_ID_NVM_READ_VERSION_FAIL,
  EVT_ID_NVM_READ_VERSION_FINISH,
  ///< TbtNvmRetimerDrvHelpers.c - end

  ///< FmpDeviceLibPdBridge.c - start
  EVT_ID_FMP_DEV_PD_BRIDGE_CHECKIMAGE,                   ///< FmpDeviceCheckImageWithStatus()
  EVT_ID_FMP_DEV_PD_BRIDGE_CHECKIMAGE_POINTER_NULL,
  EVT_ID_FMP_DEV_PD_BRIDGE_SIGNATURE_NOT_DETECTED,
  EVT_ID_FMP_DEV_PD_BRIDGE_PAYLOAD_ZERO,
  EVT_ID_FMP_DEV_PD_BRIDGE_PAYLOAD_SIZE_SMALL,
  EVT_ID_FMP_DEV_PD_BRIDGE_PAYLOAD_OUT_BOUNDS1,
  EVT_ID_FMP_DEV_PD_BRIDGE_GET_VERSION_VARIABLE_FAILED,  ///< UpdatePdBridgeVersion()
  EVT_ID_FMP_DEV_PD_BRIDGE_SET_IMAGE_START,              ///< FmpDeviceSetImageWithStatus()
  EVT_ID_FMP_DEV_PD_BRIDGE_IMAGE_NULL,
  EVT_ID_FMP_DEV_PD_BRIDGE_PROGRESS_IS_NULL,
  EVT_ID_FMP_DEV_PD_BRIDGE_PROGRESS_CALLBACK_FAILED,
  EVT_ID_FMP_DEV_PD_BRIDGE_UPDATE_START,
  EVT_ID_FMP_DEV_PD_BRIDGE_LOCATE_PROTOCOL_FAILED,
  EVT_ID_FMP_DEV_PD_BRIDGE_PAYLOAD_COUNT,
  EVT_ID_FMP_DEV_PD_BRIDGE_PAYLOAD_IMAGE_OFFSET_SIZE,
  EVT_ID_FMP_DEV_PD_BRIDGE_PAYLOAD_CNTRL_INDEX_SHARE_FLASH_MODE,
  EVT_ID_FMP_DEV_PD_BRIDGE_PAYLOAD_PD_BRIDGE_TYPE,
  EVT_ID_FMP_DEV_PD_BRIDGE_PAYLOAD_OUT_BOUNDS2,
  EVT_ID_FMP_DEV_PD_BRIDGE_UNSUPPORT_FW_TYPE,
  EVT_ID_FMP_DEV_PD_BRIDGE_INVALID_SHARE_FLASH_MODE_VALUE,
  EVT_ID_FMP_DEV_PD_BRIDGE_INVALID_PD_BRIDGE_TYPE_VALUE,
  EVT_ID_FMP_DEV_PD_BRIDGE_INIT_VENDOR_CMD_DATA_FAILED,
  EVT_ID_FMP_DEV_PD_BRIDGE_FW_VERSION_INDEX,
  EVT_ID_FMP_DEV_PD_BRIDGE_FW_VERSION,
  EVT_ID_FMP_DEV_PD_BRIDGE_UPDATE_FAILED_AT_INDEX,
  EVT_ID_FMP_DEV_PD_BRIDGE_SET_IMAGE_END,
  EVT_ID_FMP_DEV_PD_BRIDGE_LOCK,                         ///< FmpDeviceLock()
  ///< FmpDeviceLibPdBridge.c - end

  ///< UsbCPdBridgeUpdateLib.c - start
  EVT_ID_USBC_PD_BRIDGE_NVM_READ_LENGTH_INVALID,         ///< NvmRead()
  EVT_ID_USBC_PD_BRIDGE_NVM_READ_OUTPUT_DATA_NULL,
  EVT_ID_USBC_PD_BRIDGE_NVM_READ_OFFSET_LENGTH,
  EVT_ID_USBC_PD_BRIDGE_NVM_READ_DATA_INDEX,
  EVT_ID_USBC_PD_BRIDGE_NVM_VENDOR_CMD_FAIL,
  EVT_ID_USBC_PD_BRIDGE_NVM_SET_OFFSET_INDEX,            ///< NvmSetOffset()
  EVT_ID_USBC_PD_BRIDGE_NVM_SET_OFFSET_VENDOR_CMD_FAIL,
  EVT_ID_USBC_PD_BRIDGE_NVM_SET_OFFSET_SUCCESS,
  EVT_ID_USBC_PD_BRIDGE_NVM_WRITE_NULL,                  ///< NvmWrite()
  EVT_ID_USBC_PD_BRIDGE_NVM_WRITE_INVALID_BUFFER_SIZE,
  EVT_ID_USBC_PD_BRIDGE_NVM_WRITE_VENDOR_CMD_FAIL,
  EVT_ID_USBC_PD_BRIDGE_NVM_AUTH_CMD_INDEX,              ///< NvmAuthenticateWrite()
  EVT_ID_USBC_PD_BRIDGE_NVM_AUTH_VENDOR_CMD_FAIL,
  EVT_ID_USBC_PD_BRIDGE_NVM_AUTH_WRITE_CMD_SUCCESS,
  EVT_ID_USBC_PD_BRIDGE_NVM_STALL_INDEX,                 ///< NvmStallNvmAccess()
  EVT_ID_USBC_PD_BRIDGE_NVM_STALL_VENDOR_CMD_FAIL,
  EVT_ID_USBC_PD_BRIDGE_NVM_STALL_CMD_SUCCESS,
  EVT_ID_USBC_PD_BRIDGE_NVM_RESET_INDEX,                 ///< NvmReset()
  EVT_ID_USBC_PD_BRIDGE_NVM_RESET_VENDOR_CMD_FAIL,
  EVT_ID_USBC_PD_BRIDGE_NVM_RESET_CMD_SUCCESS,
  EVT_ID_USBC_PD_BRIDGE_ENTER_NVM_UPDATE_MODE_INDEX,                 ///< EnterNvmUpdateMode()
  EVT_ID_USBC_PD_BRIDGE_ENTER_NVM_UPDATE_MODE_VENDOR_CMD_FAILED,
  EVT_ID_USBC_PD_BRIDGE_ENTER_NVM_UPDATE_MODE_CMD_SUCCESS,
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_START,             ///< UpdatePdBridgeNvmFirmware()
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_SET_OFFSET_FAIL,
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_ENTER_NVM_UPDATE_MODE_FAILED,
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_TOTAL_SIZE,
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_WRITTEN_SO_FAR,
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_NVMWRITE_FAIL,
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_WRITE_FINISH,
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_GOT_ERROR_RECOVERY,
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_DEV_ERROR,
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_STALLNVM_FAIL,
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_AUTHWRITE_FAIL,
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_NVMRESET_FAIL,
  EVT_ID_USBC_PD_BRIDGE_NVM_FW_UPDATE_SUCCESS
  ///< UsbCPdBridgeUpdateLib.c - end
} USBC_CAPSULE_EVT_ID;
#endif
