/**@file
   Nvmrsecure driver is an API for Sh256 key request and generation.

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2020 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/
#include <Library/BaseMemoryLib.h>
#include <Library/BaseCryptLib.h>
#include <Library/MemoryAllocationLib.h>
#include <Library/DebugLib.h>
#include <Library/RngLib.h>

//
// Max Known Digest Size is SHA512 Output (64 bytes) by far
//
#define MAX_DIGEST_SIZE        64
#define INITIAL_VECTOR_SIZE    16
#define RPMB_WRAPPED_KEY_SIZE  32
#define AES256_KEY_BYTE_SIZE   32
#define AES256_KEY_BIT_SIZE    AES256_KEY_BYTE_SIZE * 8

extern GLOBAL_REMOVE_IF_UNREFERENCED UINT8  mRpmbKey256[RPMB_WRAPPED_KEY_SIZE];


//
// At most we have two wrapped keys.
// (1) Seed wrapped key.
// (2) Pin wrapped key.
//
#define AES256_WRAPPED_KEY_MAX_COUNT         0x2

typedef enum {
  AES_256_CBC = 0
} NVME_KEY_ALG_TYPE;

typedef enum {
  SEED_WRAPPED = 0,
  PIN_WRAPPED
} WRAPPED_KEY_TAG;

#define NVME_PRIVATE_DATA_IN_RPMB_SIGNATURE  SIGNATURE_32 ('N','R','D','P')
#define NVME_PRIVATE_DATA_IN_RPMB_REVISION   0x1

typedef struct {
  UINT32    Signature;           // Signature: NRDP
  UINT16    Revision;            // Revision: 0x1
  UINT16    HeaderSize;
  UINT16    TotalSize;
  UINT8     Reserved1[2];
  UINT32    WrappedKeyInfoList;  // Offset from Signature to this table
  UINT8     Reserved2[112];
} NVME_PRIVATE_DATA_IN_RPMB;

#define WRAPPED_KEY_INFO_LIST_REVISION  0x1

typedef struct {
  UINT16    Revision;
  UINT16    HeaderSize;
  UINT32    Count;
  UINT32    CryptoAlg;   // Should be one of the NVME_KEY_ALG_TYPE
} WRAPPED_KEY_INFO_LIST;

typedef struct {
  UINT8     InitialVector[INITIAL_VECTOR_SIZE];  // 16-byte
  UINT16    WrappedKeySize;
  UINT8     Reserved[2];
  UINT32    KeyTag;
  UINT8     WrappedKey[RPMB_WRAPPED_KEY_SIZE];   // 256-bit
} AES256_WRAPPED_KEY;

/**
  This function completes the HMAC-SHA256 hash calculation
  and retrieves the digest value into the specified memory.
  When DigestFlag is FALSE, return a pointer to Digest From Host.

  @param[in, out]  Digest      On input, If DigestFlag is TRUE, a pointer to Digest From Nvme controller.
                               On output When DigestFlag is FALSE, return a pointer to Digest From Host.
  @param[in]       Data        Pointer to the buffer containing the data to be digested.
  @param[in]       DataSize    Size of Data buffer in bytes.
  @param[in]       DigestFlag  Determine whether Digest has a value generated by the NVME controller.

  @retval TRUE     HmacSha256Request data digest succeeded.
  @retval FALSE    HmacSha256Request data digest failed.
**/
BOOLEAN
EFIAPI
HmacSha256Request (
  IN  OUT         UINT8   *Digest,
  IN       CONST  VOID    *Data,
  IN              UINTN   DataSize,
  IN              BOOLEAN DigestFlag
  );

/**
  This function completes the Aes SHA256 hash calculation
  and retrieves the encrypted value into the specified memory.
  When DigestFlag is FALSE, return a pointer to Digest From Host.

  @param[out]     KeyGeneration         On input, If DigestFlag is TRUE, a pointer to the encryption key
                                        On output When DigestFlag is FALSE, return a pointer to the decryption
                                        key.
  @param[in]      WrappingKey           Pointer to the buffer containing the Csme seed requested by Bios.
  @param[in]      Data                  Pointer to the buffer containing the data to be encrypted/decrypted.
  @param[in]      DataSize              Size of Data buffer in bytes.
  @param[in/out]  Ivec                  Random Data of the InitVector.
  @param[in]      EncryptOrDecryptFlag  Determine whether do encryption or decryption.

  @retval TRUE     AesCbcSha256Request data digest succeeded.
  @retval FALSE    AesCbcSha256Request data digest failed.
**/
BOOLEAN
EFIAPI
AesCbcRequest (
  OUT         UINT8         *KeyGeneration,
  IN          CONST  UINT8  *WrappingKey,
  IN          CONST  UINT8  *Data,
  IN          UINTN         DataSize,
  IN          UINT8         *Ivec,
  IN          BOOLEAN       EncryptOrDecryptFlag
  );

