/**@file

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2020 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/
#include "NvmeSecure.h"


/**
  This function completes the HMAC-SHA256 hash calculation
  and retrieves the digest value into the specified memory.
  When DigestFlag is FALSE, return a pointer to Digest From Host.

  @param[in, out]  Digest      On input, If DigestFlag is TRUE, a pointer to Digest From Nvme controller.
                               On output When DigestFlag is FALSE, return a pointer to Digest From Host.
  @param[in]       Data        Pointer to the buffer containing the data to be digested.
  @param[in]       DataSize    Size of Data buffer in bytes.
  @param[in]       DigestFlag  Determine whether Digest has a value generated by the NVME controller.

  @retval TRUE     HmacSha256Request data digest succeeded.
  @retval FALSE    HmacSha256Request data digest failed.
**/
BOOLEAN
EFIAPI
HmacSha256Request (
  IN  OUT         UINT8   *Digest,
  IN       CONST  VOID    *Data,
  IN              UINTN   DataSize,
  IN              BOOLEAN DigestFlag
  )
{
  BOOLEAN  Status;
  VOID     *HmacCtx;
  UINT8    DigestFormHost[MAX_DIGEST_SIZE];

  HmacCtx = NULL;

  //
  // Check input parameters.
  //
  if (Digest == NULL || Data == NULL) {
    return FALSE;
  }

  //
  // Allocates and initializes one HMAC_CTX context for subsequent HMAC-SHA256 use
  //
  HmacCtx = HmacSha256New ();
  if (HmacCtx == NULL) {
    DEBUG ((DEBUG_ERROR, "HmacSha256Request->HmacSha256New error. \n"));
    return FALSE;
  }

  //
  // Set user-supplied key for subsequent use. It must be done before any
  // calling to HmacSha256Update().
  //
  Status = HmacSha256SetKey (HmacCtx, mRpmbKey256, SHA256_DIGEST_SIZE);
  if (Status != TRUE) {
    DEBUG ((DEBUG_ERROR, "HmacSha256Request->HmacSha256SetKey error. \n"));
    return Status;
  }

  //
  // Digests the input data and updates HMAC-SHA256 context.
  //

  Status = HmacSha256Update (HmacCtx, Data, DataSize);
  if (Status != TRUE) {
    DEBUG ((DEBUG_ERROR, "HmacSha256Request->HmacSha256Update error. \n"));
    return Status;
  }

  //
  // Completes computation of the HMAC-SHA256 digest value.
  //
  Status = HmacSha256Final (HmacCtx, DigestFormHost);
  if (Status != TRUE) {
    DEBUG ((DEBUG_ERROR, "HmacSha256Request->HmacSha256Final error. \n"));
    return Status;
  }

  if (DigestFlag == FALSE) {
    CopyMem ((VOID *) Digest, (VOID *) DigestFormHost, SHA256_DIGEST_SIZE);
  } else {
    //
    // Compare whether the HMAC value generated by HOST is consistent with
    // the HMAC value generated by NVME Controlroller.
    //
    if (CompareMem (DigestFormHost, Digest, SHA256_DIGEST_SIZE) != 0) {
      DEBUG ((DEBUG_ERROR, "DigestFormHost != DigestFromNvme.\n"));
      return FALSE;
    }
    DEBUG ((DEBUG_INFO, "DigestFormHost = DigestFromNvme.\n"));
  }

  return TRUE;
}

/**
  This function completes the Aes SHA256 hash calculation
  and retrieves the encrypted value into the specified memory.
  When DigestFlag is FALSE, return a pointer to Digest From Host.

  @param[out]     KeyGeneration         On input, If DigestFlag is TRUE, a pointer to the encryption key
                                        On output When DigestFlag is FALSE, return a pointer to the decryption
                                        key.
  @param[in]      WrappingKey           Pointer to the buffer containing the Csme seed requested by Bios.
  @param[in]      Data                  Pointer to the buffer containing the data to be encrypted/decrypted.
  @param[in]      DataSize              Size of Data buffer in bytes.
  @param[in/out]  Ivec                  Random Data of the InitVector.
  @param[in]      EncryptOrDecryptFlag  Determine whether do encryption or decryption.

  @retval TRUE     AesCbcSha256Request data digest succeeded.
  @retval FALSE    AesCbcSha256Request data digest failed.
**/
BOOLEAN
EFIAPI
AesCbcRequest (
  OUT         UINT8         *KeyGeneration,
  IN          CONST  UINT8  *WrappingKey,
  IN          CONST  UINT8  *Data,
  IN          UINTN         DataSize,
  IN OUT      UINT8         *Ivec,
  IN          BOOLEAN       EncryptOrDecryptFlag
  )
{
  BOOLEAN  Status;
  VOID     *AesContext;
  UINTN    AesContextSize;
  UINT64   TempSeed[2];

  //
  // Check input parameters.
  //
  if (KeyGeneration == NULL || Data == NULL || Ivec == NULL) {
    DEBUG ((DEBUG_ERROR, "AesCbcRequest : invalid parameter. \n"));
    return FALSE;
  }

  //
  // If it is encrypt operation, generate the random IV.
  //
  if (EncryptOrDecryptFlag) {
    if (GetRandomNumber128 (TempSeed) != TRUE) {
      ASSERT (FALSE);
      return FALSE;
    }
    CopyMem (Ivec, TempSeed, INITIAL_VECTOR_SIZE);
  }

  AesContextSize = AesGetContextSize();
  AesContext = AllocatePool (AesContextSize);
  if (AesContext == NULL) {
     DEBUG ((DEBUG_ERROR, "Run out of resource during allocate AesContext. \n"));
     return FALSE;
  }

  Status = AesInit (AesContext, WrappingKey, AES256_KEY_BIT_SIZE);
  if ((AesContext == NULL) || (Status != TRUE)) {
    DEBUG ((DEBUG_ERROR, "AesCbcRequest->AesInit is failed, Status = [%x]. \n", Status));
    return FALSE;
  }

  if (EncryptOrDecryptFlag) {
    //
    // Do Encrytion to generate wrapped_key
    //
    Status = AesCbcEncrypt (AesContext, Data, DataSize, Ivec, KeyGeneration);
    if (Status != TRUE) {
      DEBUG ((DEBUG_ERROR, "AesCbcRequest->AesCbcEncrypt is failed. \n"));
      return FALSE;
    }
  } else {
    //
    // Do Decrytion to generate rpmb_key
    //
    Status = AesCbcDecrypt (AesContext, Data, DataSize, Ivec, KeyGeneration);
    if (Status != TRUE) {
      DEBUG ((DEBUG_ERROR, "AesCbcRequest->AesCbcDecrypt is failed. \n"));
      return FALSE;
    }
  }

  return TRUE;
}

