//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//

/**@file

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2022 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/

  //
  // Define IPU NVS Area operation region.
  //
#ifndef _IPU_NVS_AREA_DEF_H_
#define _IPU_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  UINT8    IpuAcpiMode;                             ///< Offset 0       IPU ACPI device type (0=Disabled, 1=AVStream virtual device as child of GFX)
} IPU_NVS_AREA;

#pragma pack(pop)
#endif
