/** @file
  Auto generated header - DO NOT MODIFY!!!
  Generated by the PmonDiscoveryTableGenerator.py

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2022 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:

**/

#ifndef _PMON_GLOBAL_H_
#define _PMON_GLOBAL_H_
static UINT8 gPmonGlobal[] =
{
  0x00, 0x04, 0x06, 0x00, 0x00, 0x00, 0x00, 0x20,
  0x00, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x08, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
#endif /*_PMON_GLOBAL_H_*/
