//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//


/** @file
  USB PORT MAP NVS Area table

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2023 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification
**/

  // Define a Global region of UsbPortMap NVS Region that may be used for any
  // type of implementation.  The starting offset and size will be fixed
  // up by the System BIOS during POST.  Note that the Size must be a word
  // in size to be fixed up correctly.

  // Naming Rule
  // First 2 chars:
  //   AX - PCH USB2 Port#
  //   BX - PCH USB3 Port#
  //   DX - TCSS USB2 Port#
  //   EX - TCSS USB3 Port#
  // Last 2 chars:
  //   GP - Group Position
  //   VS - Visibility
  //   CN - Connectable
  //   TP - Type
  //   CP - Capability

#ifndef _USB_PORT_MAP_NVS_AREA_DEF_H_
#define _USB_PORT_MAP_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  UINT8    PchUsb2PortGroupPosition[14];            ///< Offset 0       PCH USB2 Port1 Group Position for _PLD
                                                    ///< Offset 1       PCH USB2 Port2 Group Position for _PLD
                                                    ///< Offset 2       PCH USB2 Port3 Group Position for _PLD
                                                    ///< Offset 3       PCH USB2 Port4 Group Position for _PLD
                                                    ///< Offset 4       PCH USB2 Port5 Group Position for _PLD
                                                    ///< Offset 5       PCH USB2 Port6 Group Position for _PLD
                                                    ///< Offset 6       PCH USB2 Port7 Group Position for _PLD
                                                    ///< Offset 7       PCH USB2 Port8 Group Position for _PLD
                                                    ///< Offset 8       PCH USB2 Port9 Group Position for _PLD
                                                    ///< Offset 9       PCH USB2 PortA Group Position for _PLD
                                                    ///< Offset 10      PCH USB2 PortB Group Position for _PLD
                                                    ///< Offset 11      PCH USB2 PortC Group Position for _PLD
                                                    ///< Offset 12      PCH USB2 PortD Group Position for _PLD
                                                    ///< Offset 13      PCH USB2 PortE Group Position for _PLD
  UINT8    PchUsb2PortVisibility[14];               ///< Offset 14      PCH USB2 Port1 Visibility for _PLD
                                                    ///< Offset 15      PCH USB2 Port2 Visibility for _PLD
                                                    ///< Offset 16      PCH USB2 Port3 Visibility for _PLD
                                                    ///< Offset 17      PCH USB2 Port4 Visibility for _PLD
                                                    ///< Offset 18      PCH USB2 Port5 Visibility for _PLD
                                                    ///< Offset 19      PCH USB2 Port6 Visibility for _PLD
                                                    ///< Offset 20      PCH USB2 Port7 Visibility for _PLD
                                                    ///< Offset 21      PCH USB2 Port8 Visibility for _PLD
                                                    ///< Offset 22      PCH USB2 Port9 Visibility for _PLD
                                                    ///< Offset 23      PCH USB2 PortA Visibility for _PLD
                                                    ///< Offset 24      PCH USB2 PortB Visibility for _PLD
                                                    ///< Offset 25      PCH USB2 PortC Visibility for _PLD
                                                    ///< Offset 26      PCH USB2 PortD Visibility for _PLD
                                                    ///< Offset 27      PCH USB2 PortE Visibility for _PLD
  UINT8    PchUsb2PortConnectable[14];              ///< Offset 28      PCH USB2 Port1 Connectable for _UPC
                                                    ///< Offset 29      PCH USB2 Port2 Connectable for _UPC
                                                    ///< Offset 30      PCH USB2 Port3 Connectable for _UPC
                                                    ///< Offset 31      PCH USB2 Port4 Connectable for _UPC
                                                    ///< Offset 32      PCH USB2 Port5 Connectable for _UPC
                                                    ///< Offset 33      PCH USB2 Port6 Connectable for _UPC
                                                    ///< Offset 34      PCH USB2 Port7 Connectable for _UPC
                                                    ///< Offset 35      PCH USB2 Port8 Connectable for _UPC
                                                    ///< Offset 36      PCH USB2 Port9 Connectable for _UPC
                                                    ///< Offset 37      PCH USB2 PortA Connectable for _UPC
                                                    ///< Offset 38      PCH USB2 PortB Connectable for _UPC
                                                    ///< Offset 39      PCH USB2 PortC Connectable for _UPC
                                                    ///< Offset 40      PCH USB2 PortD Connectable for _UPC
                                                    ///< Offset 41      PCH USB2 PortE Connectable for _UPC
  UINT8    PchUsb2PortType[14];                     ///< Offset 42      PCH USB2 Port1 Type for _UPC
                                                    ///< Offset 43      PCH USB2 Port2 Type for _UPC
                                                    ///< Offset 44      PCH USB2 Port3 Type for _UPC
                                                    ///< Offset 45      PCH USB2 Port4 Type for _UPC
                                                    ///< Offset 46      PCH USB2 Port5 Type for _UPC
                                                    ///< Offset 47      PCH USB2 Port6 Type for _UPC
                                                    ///< Offset 48      PCH USB2 Port7 Type for _UPC
                                                    ///< Offset 49      PCH USB2 Port8 Type for _UPC
                                                    ///< Offset 50      PCH USB2 Port9 Type for _UPC
                                                    ///< Offset 51      PCH USB2 PortA Type for _UPC
                                                    ///< Offset 52      PCH USB2 PortB Type for _UPC
                                                    ///< Offset 53      PCH USB2 PortC Type for _UPC
                                                    ///< Offset 54      PCH USB2 PortD Type for _UPC
                                                    ///< Offset 55      PCH USB2 PortE Type for _UPC
  UINT8    PchUsb2PortCapability[14];               ///< Offset 56      PCH USB2 Port1 Capability for _UPC
                                                    ///< Offset 57      PCH USB2 Port2 Capability for _UPC
                                                    ///< Offset 58      PCH USB2 Port3 Capability for _UPC
                                                    ///< Offset 59      PCH USB2 Port4 Capability for _UPC
                                                    ///< Offset 60      PCH USB2 Port5 Capability for _UPC
                                                    ///< Offset 61      PCH USB2 Port6 Capability for _UPC
                                                    ///< Offset 62      PCH USB2 Port7 Capability for _UPC
                                                    ///< Offset 63      PCH USB2 Port8 Capability for _UPC
                                                    ///< Offset 64      PCH USB2 Port9 Capability for _UPC
                                                    ///< Offset 65      PCH USB2 PortA Capability for _UPC
                                                    ///< Offset 66      PCH USB2 PortB Capability for _UPC
                                                    ///< Offset 67      PCH USB2 PortC Capability for _UPC
                                                    ///< Offset 68      PCH USB2 PortD Capability for _UPC
                                                    ///< Offset 69      PCH USB2 PortE Capability for _UPC
  UINT8    PchUsb3PortGroupPosition[10];            ///< Offset 70      PCH USB3 Port1 Group Position for _PLD
                                                    ///< Offset 71      PCH USB3 Port2 Group Position for _PLD
                                                    ///< Offset 72      PCH USB3 Port3 Group Position for _PLD
                                                    ///< Offset 73      PCH USB3 Port4 Group Position for _PLD
                                                    ///< Offset 74      PCH USB3 Port5 Group Position for _PLD
                                                    ///< Offset 75      PCH USB3 Port6 Group Position for _PLD
                                                    ///< Offset 76      PCH USB3 Port7 Group Position for _PLD
                                                    ///< Offset 77      PCH USB3 Port8 Group Position for _PLD
                                                    ///< Offset 78      PCH USB3 Port9 Group Position for _PLD
                                                    ///< Offset 79      PCH USB3 PortA Group Position for _PLD
  UINT8    PchUsb3PortVisibility[10];               ///< Offset 80      PCH USB3 Port1 Visibility for _PLD
                                                    ///< Offset 81      PCH USB3 Port2 Visibility for _PLD
                                                    ///< Offset 82      PCH USB3 Port3 Visibility for _PLD
                                                    ///< Offset 83      PCH USB3 Port4 Visibility for _PLD
                                                    ///< Offset 84      PCH USB3 Port5 Visibility for _PLD
                                                    ///< Offset 85      PCH USB3 Port6 Visibility for _PLD
                                                    ///< Offset 86      PCH USB3 Port7 Visibility for _PLD
                                                    ///< Offset 87      PCH USB3 Port8 Visibility for _PLD
                                                    ///< Offset 88      PCH USB3 Port9 Visibility for _PLD
                                                    ///< Offset 89      PCH USB3 PortA Visibility for _PLD
  UINT8    PchUsb3PortConnectable[10];              ///< Offset 90      PCH USB3 Port1 Connectable for _UPC
                                                    ///< Offset 91      PCH USB3 Port2 Connectable for _UPC
                                                    ///< Offset 92      PCH USB3 Port3 Connectable for _UPC
                                                    ///< Offset 93      PCH USB3 Port4 Connectable for _UPC
                                                    ///< Offset 94      PCH USB3 Port5 Connectable for _UPC
                                                    ///< Offset 95      PCH USB3 Port6 Connectable for _UPC
                                                    ///< Offset 96      PCH USB3 Port7 Connectable for _UPC
                                                    ///< Offset 97      PCH USB3 Port8 Connectable for _UPC
                                                    ///< Offset 98      PCH USB3 Port9 Connectable for _UPC
                                                    ///< Offset 99      PCH USB3 PortA Connectable for _UPC
  UINT8    PchUsb3PortType[10];                     ///< Offset 100     PCH USB3 Port1 Type for _UPC
                                                    ///< Offset 101     PCH USB3 Port2 Type for _UPC
                                                    ///< Offset 102     PCH USB3 Port3 Type for _UPC
                                                    ///< Offset 103     PCH USB3 Port4 Type for _UPC
                                                    ///< Offset 104     PCH USB3 Port5 Type for _UPC
                                                    ///< Offset 105     PCH USB3 Port6 Type for _UPC
                                                    ///< Offset 106     PCH USB3 Port7 Type for _UPC
                                                    ///< Offset 107     PCH USB3 Port8 Type for _UPC
                                                    ///< Offset 108     PCH USB3 Port9 Type for _UPC
                                                    ///< Offset 109     PCH USB3 PortA Type for _UPC
  UINT8    PchUsb3PortCapability[10];               ///< Offset 110     PCH USB3 Port1 Capability for _UPC
                                                    ///< Offset 111     PCH USB3 Port2 Capability for _UPC
                                                    ///< Offset 112     PCH USB3 Port3 Capability for _UPC
                                                    ///< Offset 113     PCH USB3 Port4 Capability for _UPC
                                                    ///< Offset 114     PCH USB3 Port5 Capability for _UPC
                                                    ///< Offset 115     PCH USB3 Port6 Capability for _UPC
                                                    ///< Offset 116     PCH USB3 Port7 Capability for _UPC
                                                    ///< Offset 117     PCH USB3 Port8 Capability for _UPC
                                                    ///< Offset 118     PCH USB3 Port9 Capability for _UPC
                                                    ///< Offset 119     PCH USB3 PortA Capability for _UPC
} USB_PORT_MAP_NVS_AREA;

#pragma pack(pop)
#endif
