/** @file
  Header file for GPIO V2 signals.

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 2022 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/

#ifndef _GPIOV2_SIGNALS_H_
#define _GPIOV2_SIGNALS_H_


#define GPIOV2_SIGNAL_DEF(InstanceIndex, Interface, SignalTypeIndex, InterfaceIndex, PinIndex) \
  (UINT32)(                    \
    (InstanceIndex    << 28) + \
    (Interface        << 20) + \
    (SignalTypeIndex  << 12)  + \
    (InterfaceIndex   << 4)  + \
    (PinIndex         << 0)    \
  )

#define SIGNAL_ZERO_INDEX 0

#define GPIOV2_PERIPHERAL_INTERFACE_LPSS            0
#define GPIOV2_PERIPHERAL_INTERFACE_ISH             1
#define GPIOV2_PERIPHERAL_INTERFACE_THC             2
#define GPIOV2_PERIPHERAL_INTERFACE_HDA             3
#define GPIOV2_PERIPHERAL_INTERFACE_DMIC            4
#define GPIOV2_PERIPHERAL_INTERFACE_SNDW            5
#define GPIOV2_PERIPHERAL_INTERFACE_DDSP            6
#define GPIOV2_PERIPHERAL_INTERFACE_PANEL           7
#define GPIOV2_PERIPHERAL_INTERFACE_HDMI            8
#define GPIOV2_PERIPHERAL_INTERFACE_CNVI            9
#define GPIOV2_PERIPHERAL_INTERFACE_SD              10
#define GPIOV2_PERIPHERAL_INTERFACE_EMMC            11
#define GPIOV2_PERIPHERAL_INTERFACE_MIPI            12
#define GPIOV2_PERIPHERAL_INTERFACE_SATA            13
#define GPIOV2_PERIPHERAL_INTERFACE_PCIE            14
#define GPIOV2_PERIPHERAL_INTERFACE_USB             15
#define GPIOV2_PERIPHERAL_INTERFACE_ESPI            16
#define GPIOV2_PERIPHERAL_INTERFACE_SPI             17
#define GPIOV2_PERIPHERAL_INTERFACE_VR              18
#define GPIOV2_PERIPHERAL_INTERFACE_CPU             19
#define GPIOV2_PERIPHERAL_INTERFACE_DDP             20
#define GPIOV2_PERIPHERAL_INTERFACE_TIME            21
#define GPIOV2_PERIPHERAL_INTERFACE_SMB             22
#define GPIOV2_PERIPHERAL_INTERFACE_I2S             23
#define GPIOV2_PERIPHERAL_INTERFACE_IOM             24
#define GPIOV2_PERIPHERAL_INTERFACE_DISP            25
#define GPIOV2_PERIPHERAL_INTERFACE_IPU             26
#define GPIOV2_PERIPHERAL_INTERFACE_TBT             27
#define GPIOV2_PERIPHERAL_INTERFACE_PMC             28
#define GPIOV2_PERIPHERAL_INTERFACE_PWR             29
#define GPIOV2_PERIPHERAL_INTERFACE_MISC            30
#define GPIOV2_PERIPHERAL_INTERFACE_JTAG            31
#define GPIOV2_PERIPHERAL_INTERFACE_OSSE            32
#define GPIOV2_PERIPHERAL_INTERFACE_USBC            33
#define GPIOV2_PERIPHERAL_INTERFACE_UFS             34
#define GPIOV2_PERIPHERAL_INTERFACE_VISA2CH1        35
#define GPIOV2_PERIPHERAL_INTERFACE_VISA2CH2        36
#define GPIOV2_PERIPHERAL_INTERFACE_VISA2CH3        37
#define GPIOV2_PERIPHERAL_INTERFACE_VISA2CH4        38
#define GPIOV2_PERIPHERAL_INTERFACE_VISAFUSECH1     39
#define GPIOV2_PERIPHERAL_INTERFACE_VISAOSSEFUSECH1 40
#define GPIOV2_PERIPHERAL_INTERFACE_PTI_TRACE       41


#define GPIOV2_SIGNAL_TYPE_LPSS_UART_RX              0
#define GPIOV2_SIGNAL_TYPE_LPSS_UART_TX              1
#define GPIOV2_SIGNAL_TYPE_LPSS_UART_RTS             2
#define GPIOV2_SIGNAL_TYPE_LPSS_UART_CTS             3
#define GPIOV2_SIGNAL_TYPE_LPSS_SPI_MOSI             4
#define GPIOV2_SIGNAL_TYPE_LPSS_SPI_MISO             5
#define GPIOV2_SIGNAL_TYPE_LPSS_SPI_CLK              6
#define GPIOV2_SIGNAL_TYPE_LPSS_SPI_CS               7
#define GPIOV2_SIGNAL_TYPE_LPSS_I2C_SCL              8
#define GPIOV2_SIGNAL_TYPE_LPSS_I2C_SDA              9
#define GPIOV2_SIGNAL_TYPE_LPSS_I3C_SCL              10
#define GPIOV2_SIGNAL_TYPE_LPSS_I3C_SDA              11
#define GPIOV2_SIGNAL_TYPE_LPSS_I3C_SCL_FB           12

#define GPIOV2_SIGNAL_TYPE_ISH_GP                    0
#define GPIOV2_SIGNAL_TYPE_ISH_UART_RX               1
#define GPIOV2_SIGNAL_TYPE_ISH_UART_TX               2
#define GPIOV2_SIGNAL_TYPE_ISH_UART_RTS              3
#define GPIOV2_SIGNAL_TYPE_ISH_UART_CTS              4
#define GPIOV2_SIGNAL_TYPE_ISH_SPI_MOSI              5
#define GPIOV2_SIGNAL_TYPE_ISH_SPI_MISO              6
#define GPIOV2_SIGNAL_TYPE_ISH_SPI_CLK               7
#define GPIOV2_SIGNAL_TYPE_ISH_SPI_CS                8
#define GPIOV2_SIGNAL_TYPE_ISH_I2C_SCL               9
#define GPIOV2_SIGNAL_TYPE_ISH_I2C_SDA               10
#define GPIOV2_SIGNAL_TYPE_ISH_I3C_SCL               11
#define GPIOV2_SIGNAL_TYPE_ISH_I3C_SDA               12
#define GPIOV2_SIGNAL_TYPE_ISH_I3C_SCL_FB            13

#define GPIOV2_SIGNAL_TYPE_THC_WOT                   0
#define GPIOV2_SIGNAL_TYPE_THC_SPI_INT               1
#define GPIOV2_SIGNAL_TYPE_THC_CLK_LOOPBACK          2
#define GPIOV2_SIGNAL_TYPE_THC_CLK                   3
#define GPIOV2_SIGNAL_TYPE_THC_IO0                   4
#define GPIOV2_SIGNAL_TYPE_THC_IO1                   5
#define GPIOV2_SIGNAL_TYPE_THC_IO2                   6
#define GPIOV2_SIGNAL_TYPE_THC_IO3                   7
#define GPIOV2_SIGNAL_TYPE_THC_RSTB                  8
#define GPIOV2_SIGNAL_TYPE_THC_CSB                   9
#define GPIOV2_SIGNAL_TYPE_THC_I2C_SCL               10
#define GPIOV2_SIGNAL_TYPE_THC_I2C_SDA               11
#define GPIOV2_SIGNAL_TYPE_THC_DSYNC                 12

#define GPIOV2_SIGNAL_TYPE_HDA_BCLK                  0
#define GPIOV2_SIGNAL_TYPE_HDA_RSTB                  1
#define GPIOV2_SIGNAL_TYPE_HDA_SYNC                  2
#define GPIOV2_SIGNAL_TYPE_HDA_SDO                   3
#define GPIOV2_SIGNAL_TYPE_HDA_SDI                   4
#define GPIOV2_SIGNAL_TYPE_HDA_CPU_BCLK              5
#define GPIOV2_SIGNAL_TYPE_HDA_CPU_SDI               6
#define GPIOV2_SIGNAL_TYPE_HDA_CPU_SDO               7

#define GPIOV2_SIGNAL_TYPE_DMIC_DATA                 0
#define GPIOV2_SIGNAL_TYPE_DMIC_CLKA                 1
#define GPIOV2_SIGNAL_TYPE_DMIC_CLKB                 2

#define GPIOV2_SIGNAL_TYPE_SNDW_CLK                  0
#define GPIOV2_SIGNAL_TYPE_SNDW_DATA                 1
#define GPIOV2_SIGNAL_TYPE_SNDW_DATA0                2
#define GPIOV2_SIGNAL_TYPE_SNDW_DATA1                3
#define GPIOV2_SIGNAL_TYPE_SNDW_DATA2                4
#define GPIOV2_SIGNAL_TYPE_SNDW_DATA3                5

#define GPIOV2_SIGNAL_TYPE_DDSP_HPD                  0
#define GPIOV2_SIGNAL_TYPE_DDSP_HPD_A                1
#define GPIOV2_SIGNAL_TYPE_DDSP_HPD_B                2
#define GPIOV2_SIGNAL_TYPE_DDSP_HPD_C                3
#define GPIOV2_SIGNAL_TYPE_DDSP_HPDALV               4

#define GPIOV2_SIGNAL_TYPE_PANEL_AVDD_EN             0
#define GPIOV2_SIGNAL_TYPE_PANEL_BKLTEN              1
#define GPIOV2_SIGNAL_TYPE_PANEL_BKLTCTL             2
#define GPIOV2_SIGNAL_TYPE_PANEL_AVDD_EN2            3
#define GPIOV2_SIGNAL_TYPE_PANEL_BKLTEN2             4
#define GPIOV2_SIGNAL_TYPE_PANEL_BKLTCTL2            5
#define GPIOV2_SIGNAL_TYPE_PANEL_RESET               6
#define GPIOV2_SIGNAL_TYPE_PANEL_AVEE_EN             7
#define GPIOV2_SIGNAL_TYPE_PANEL_VIO_EN              8
#define GPIOV2_SIGNAL_TYPE_PANEL_HPD                 9
#define GPIOV2_SIGNAL_TYPE_PANEL_TE_EN               10

#define GPIOV2_SIGNAL_TYPE_HDMI_GMBUS_SCL            0
#define GPIOV2_SIGNAL_TYPE_HDMI_GMBUS_SDA            1

#define GPIOV2_SIGNAL_TYPE_CNVI_RF_RESET             0
#define GPIOV2_SIGNAL_TYPE_CNVI_CLKREQ               1
#define GPIOV2_SIGNAL_TYPE_CNVI_MFUART_RXD           2
#define GPIOV2_SIGNAL_TYPE_CNVI_MFUART_TXD           3
#define GPIOV2_SIGNAL_TYPE_CNVI_MFUART_RTS           4
#define GPIOV2_SIGNAL_TYPE_CNVI_MFUART_CTS           5
#define GPIOV2_SIGNAL_TYPE_CNVI_BRI_DT               6
#define GPIOV2_SIGNAL_TYPE_CNVI_BRI_RSP              7
#define GPIOV2_SIGNAL_TYPE_CNVI_RGI_DT               8
#define GPIOV2_SIGNAL_TYPE_CNVI_RGI_RSP              9
#define GPIOV2_SIGNAL_TYPE_CNVI_PA_BLANKING          10
#define GPIOV2_SIGNAL_TYPE_CNVI_DEBUG                11
#define GPIOV2_SIGNAL_TYPE_CNVI_DEBUG_A              12

#define GPIOV2_SIGNAL_TYPE_SD_PWR_EN_B               0
#define GPIOV2_SIGNAL_TYPE_SD_CMD                    1
#define GPIOV2_SIGNAL_TYPE_SD_DATA                   2
#define GPIOV2_SIGNAL_TYPE_SD_CDB                    3
#define GPIOV2_SIGNAL_TYPE_SD_CLK                    4
#define GPIOV2_SIGNAL_TYPE_SD_WP                     5
#define GPIOV2_SIGNAL_TYPE_SD_1P8_EN                 6
#define GPIOV2_SIGNAL_TYPE_SD_CLK_FB                 7

#define GPIOV2_SIGNAL_TYPE_EMMC_CMD                  0
#define GPIOV2_SIGNAL_TYPE_EMMC_DATA                 1
#define GPIOV2_SIGNAL_TYPE_EMMC_RCLK                 2
#define GPIOV2_SIGNAL_TYPE_EMMC_CLK                  3
#define GPIOV2_SIGNAL_TYPE_EMMC_RESETB               4

#define GPIOV2_SIGNAL_TYPE_MIPI_PANEL_RESET          0
#define GPIOV2_SIGNAL_TYPE_MIPI_SEC_POW_EN_AVEE      1
#define GPIOV2_SIGNAL_TYPE_MIPI_SEC_POW_EN_AVDD      2

#define GPIOV2_SIGNAL_TYPE_SATA_DEVSLP               0
#define GPIOV2_SIGNAL_TYPE_SATA_LED                  1
#define GPIOV2_SIGNAL_TYPE_SATA_GP                   2

#define GPIOV2_SIGNAL_TYPE_PCIE_SRCCLKREQ            0
#define GPIOV2_SIGNAL_TYPE_PCIE_LNK_DOWN             1

#define GPIOV2_SIGNAL_TYPE_USB_OC                    0

#define GPIOV2_SIGNAL_TYPE_ESPI_USB_OCB              0
#define GPIOV2_SIGNAL_TYPE_ESPI_ISCLK_XTAL_CLKREQ    1
#define GPIOV2_SIGNAL_TYPE_ESPI_ISCLK_XTAL_CLKACK    2
#define GPIOV2_SIGNAL_TYPE_ESPI_VWM_SPARE            3
#define GPIOV2_SIGNAL_TYPE_ESPI_CLK                  4
#define GPIOV2_SIGNAL_TYPE_ESPI_IO                   5
#define GPIOV2_SIGNAL_TYPE_ESPI_CS                   6
#define GPIOV2_SIGNAL_TYPE_ESPI_ALERT                7
#define GPIOV2_SIGNAL_TYPE_ESPI_RESET                8

#define GPIOV2_SIGNAL_TYPE_SPI_IO                    0
#define GPIOV2_SIGNAL_TYPE_SPI_MOSI                  1
#define GPIOV2_SIGNAL_TYPE_SPI_MISO                  2
#define GPIOV2_SIGNAL_TYPE_SPI_TPM_CS                3
#define GPIOV2_SIGNAL_TYPE_SPI_FLASH_CS              4
#define GPIOV2_SIGNAL_TYPE_SPI_CLK                   5

#define GPIOV2_SIGNAL_TYPE_VR_ALERT                  0

#define GPIOV2_SIGNAL_TYPE_CPU_C10_GATE              0
#define GPIOV2_SIGNAL_TYPE_CPU_GP                    1
#define GPIOV2_SIGNAL_TYPE_CPU_USB_OCB               2
#define GPIOV2_SIGNAL_TYPE_CPU_PCIE_LNK_DN           3

#define GPIOV2_SIGNAL_TYPE_DDP_CTRL_CLK              0
#define GPIOV2_SIGNAL_TYPE_DDP_CTRL_DATA             1
#define GPIOV2_SIGNAL_TYPE_DDP_CTRL_CLK_A            2
#define GPIOV2_SIGNAL_TYPE_DDP_CTRL_DATA_A           3
#define GPIOV2_SIGNAL_TYPE_DDP_CTRL_CLK_B            4
#define GPIOV2_SIGNAL_TYPE_DDP_CTRL_DATA_B           5
#define GPIOV2_SIGNAL_TYPE_DDP_CTRL_CLK_C            6
#define GPIOV2_SIGNAL_TYPE_DDP_CTRL_DATA_C           7

#define GPIOV2_SIGNAL_TYPE_TIME_SYNC                 0

#define GPIOV2_SIGNAL_TYPE_SMB_CLK                   0
#define GPIOV2_SIGNAL_TYPE_SMB_DATA                  1
#define GPIOV2_SIGNAL_TYPE_SMB_ALERT_B               2
#define GPIOV2_SIGNAL_TYPE_SMB_PCH_HOT_B             3
#define GPIOV2_SIGNAL_TYPE_SMB_SML_CLK               4
#define GPIOV2_SIGNAL_TYPE_SMB_SML_DATA              5
#define GPIOV2_SIGNAL_TYPE_SMB_SML_ALERT             6
#define GPIOV2_SIGNAL_TYPE_SMB_SML_BCLK              7
#define GPIOV2_SIGNAL_TYPE_SMB_SML_BDATA             8
#define GPIOV2_SIGNAL_TYPE_SMB_SML_BALERT            9

#define GPIOV2_SIGNAL_TYPE_I2S_SCLK                  0
#define GPIOV2_SIGNAL_TYPE_I2S_SFRM                  1
#define GPIOV2_SIGNAL_TYPE_I2S_TXD                   2
#define GPIOV2_SIGNAL_TYPE_I2S_RXD                   3
#define GPIOV2_SIGNAL_TYPE_I2S_MCLK                  4

#define GPIOV2_SIGNAL_TYPE_IOM_GPPC                  0
#define GPIOV2_SIGNAL_TYPE_IOM_GPPA                  1
#define GPIOV2_SIGNAL_TYPE_IOM_GPPE                  2
#define GPIOV2_SIGNAL_TYPE_IOM_GPPH                  3
#define GPIOV2_SIGNAL_TYPE_IOM_GPPF                  4
#define GPIOV2_SIGNAL_TYPE_IOM_GPPB                  5
#define GPIOV2_SIGNAL_TYPE_IOM_GPPD                  6
#define GPIOV2_SIGNAL_TYPE_IOM_GPPR                  7
#define GPIOV2_SIGNAL_TYPE_IOM_GPPJ                  8
#define GPIOV2_SIGNAL_TYPE_IOM_GPPI                  9
#define GPIOV2_SIGNAL_TYPE_IOM_GPPK                  10

#define GPIOV2_SIGNAL_TYPE_DISP_MISC                 0
#define GPIOV2_SIGNAL_TYPE_DISP_MISC_A               1
#define GPIOV2_SIGNAL_TYPE_DISP_MISC_B               2
#define GPIOV2_SIGNAL_TYPE_DISP_MISC_C               3

#define GPIOV2_SIGNAL_TYPE_IPU_IMGCLKOUT             0

#define GPIOV2_SIGNAL_TYPE_TBT_LSX_A                 0
#define GPIOV2_SIGNAL_TYPE_TBT_LSX_B                 1
#define GPIOV2_SIGNAL_TYPE_TBT_LSX_OE                2

#define GPIOV2_SIGNAL_TYPE_PMC_ALERT_B               0
#define GPIOV2_SIGNAL_TYPE_PMC_I2C_SDA               1
#define GPIOV2_SIGNAL_TYPE_PMC_I2C_SCL               2

#define GPIOV2_SIGNAL_TYPE_PWR_BATLOW                0
#define GPIOV2_SIGNAL_TYPE_PWR_AC_PRESENT            1
#define GPIOV2_SIGNAL_TYPE_PWR_SOC_WAKE              2
#define GPIOV2_SIGNAL_TYPE_PWR_PWRBTN                3
#define GPIOV2_SIGNAL_TYPE_PWR_SLP                   4
#define GPIOV2_SIGNAL_TYPE_PWR_SLP_A                 5
#define GPIOV2_SIGNAL_TYPE_PWR_SUSCLK                6
#define GPIOV2_SIGNAL_TYPE_PWR_SLP_WLAN              7
#define GPIOV2_SIGNAL_TYPE_PWR_LANPHYPC              8
#define GPIOV2_SIGNAL_TYPE_PWR_SLP_LAN               9
#define GPIOV2_SIGNAL_TYPE_PWR_WAKE                  10
#define GPIOV2_SIGNAL_TYPE_PWR_CATERR                11
#define GPIOV2_SIGNAL_TYPE_PWR_FORCEPR               12
#define GPIOV2_SIGNAL_TYPE_PWR_THERMTRIP             13
#define GPIOV2_SIGNAL_TYPE_PWR_VCCST                 14
#define GPIOV2_SIGNAL_TYPE_PWR_SYS_PWROK             15
#define GPIOV2_SIGNAL_TYPE_PWR_SYS_RESET             16
#define GPIOV2_SIGNAL_TYPE_PWR_MLK_RESET             17
#define GPIOV2_SIGNAL_TYPE_PWR_SX_HOLDOFF            18
#define GPIOV2_SIGNAL_TYPE_PWR_SLP_DRAM              19
#define GPIOV2_SIGNAL_TYPE_PWR_PRIPWRDNACK           20
#define GPIOV2_SIGNAL_TYPE_PWR_PRIACK                21
#define GPIOV2_SIGNAL_TYPE_PWR_PLTRST                22
#define GPIOV2_SIGNAL_TYPE_PWR_BOOTHALT              23
#define GPIOV2_SIGNAL_TYPE_PWR_EPD_ON                24
#define GPIOV2_SIGNAL_TYPE_PWR_VDD2_PWRGD            25

#define GPIOV2_SIGNAL_TYPE_MISC_FUSA_DIAGTEST_EN     0
#define GPIOV2_SIGNAL_TYPE_MISC_FUSA_DIAGTEST_MODE   1
#define GPIOV2_SIGNAL_TYPE_MISC_IEH_CORR_ERR         2
#define GPIOV2_SIGNAL_TYPE_MISC_IEH_NONFATAL_ERR     3
#define GPIOV2_SIGNAL_TYPE_MISC_IEH_FATAL_ERR        4
#define GPIOV2_SIGNAL_TYPE_MISC_DNX_FORCE_RELOAD     5
#define GPIOV2_SIGNAL_TYPE_MISC_MIC_MUTE             6
#define GPIOV2_SIGNAL_TYPE_MISC_MIC_MUTE_LED         7

#define GPIOV2_SIGNAL_TYPE_JTAG_MBPB                 0
#define GPIOV2_SIGNAL_TYPE_JTAG_TDO                  1
#define GPIOV2_SIGNAL_TYPE_JTAG_TDI                  2
#define GPIOV2_SIGNAL_TYPE_JTAG_TCK                  3
#define GPIOV2_SIGNAL_TYPE_JTAG_TMS                  4
#define GPIOV2_SIGNAL_TYPE_JTAG_TRST_B               5
#define GPIOV2_SIGNAL_TYPE_JTAG_DBG_PMODE            6
#define GPIOV2_SIGNAL_TYPE_JTAG_PREQ_B               7
#define GPIOV2_SIGNAL_TYPE_JTAG_PRDY_B               8

#define GPIOV2_SIGNAL_TYPE_OSSE_SMLCLK               0
#define GPIOV2_SIGNAL_TYPE_OSSE_SMLDATA              1
#define GPIOV2_SIGNAL_TYPE_OSSE_SMLALERT_B           2

#define GPIOV2_SIGNAL_TYPE_USBC_SMLCLK               0
#define GPIOV2_SIGNAL_TYPE_USBC_SMLDATA              1

#define GPIOV2_SIGNAL_TYPE_UFS_REFCLK                0

#define GPIOV2_SIGNAL_TYPE_VISA2CH1_DATA             0
#define GPIOV2_SIGNAL_TYPE_VISA2CH1_CLK              1

#define GPIOV2_SIGNAL_TYPE_VISA2CH2_DATA             0
#define GPIOV2_SIGNAL_TYPE_VISA2CH2_CLK              1

#define GPIOV2_SIGNAL_TYPE_VISA2CH3_DATA             0
#define GPIOV2_SIGNAL_TYPE_VISA2CH3_CLK              1

#define GPIOV2_SIGNAL_TYPE_VISA2CH4_DATA             0
#define GPIOV2_SIGNAL_TYPE_VISA2CH4_CLK              1

#define GPIOV2_SIGNAL_TYPE_VISAFUSECH1_DATA          0
#define GPIOV2_SIGNAL_TYPE_VISAFUSECH1_CLK           1

#define GPIOV2_SIGNAL_TYPE_VISAOSSEFUSECH1_DATA      0
#define GPIOV2_SIGNAL_TYPE_VISAOSSEFUSECH1_CLK       1

#define GPIOV2_SIGNAL_TYPE_PTI_TRACE_DATA            0
#define GPIOV2_SIGNAL_TYPE_PTI_TRACE_CLK             1

//
// Interface: LPSS (ID: 0)
//
#define GPIOV2_SIGNAL_LPSS_UART_RX(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_UART_RX,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_LPSS_UART_TX(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_UART_TX,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_LPSS_UART_RTS(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_UART_RTS,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_LPSS_UART_CTS(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_UART_CTS,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_LPSS_SPI_MOSI(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_SPI_MOSI,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_LPSS_SPI_MISO(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_SPI_MISO,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_LPSS_SPI_CLK(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_SPI_CLK,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_LPSS_SPI_CS(InterfaceIndex)                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_SPI_CS,         InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_LPSS_I2C_SCL(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_I2C_SCL,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_LPSS_I2C_SDA(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_I2C_SDA,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_LPSS_I3C_SCL(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_I3C_SCL,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_LPSS_I3C_SDA(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_I3C_SDA,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_LPSS_I3C_SCL_FB(InterfaceIndex)                         GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_LPSS,        GPIOV2_SIGNAL_TYPE_LPSS_I3C_SCL_FB,     InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: ISH (ID: 1)
//
#define GPIOV2_SIGNAL_ISH_GP(InterfaceIndex)                                  GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_GP,              InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_UART_RX(InterfaceIndex)                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_UART_RX,         InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_UART_TX(InterfaceIndex)                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_UART_TX,         InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_UART_RTS(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_UART_RTS,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_UART_CTS(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_UART_CTS,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_SPI_MOSI                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_SPI_MOSI,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_SPI_MISO                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_SPI_MISO,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_SPI_CLK                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_SPI_CLK,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_SPI_CS                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_SPI_CS,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_I2C_SCL(InterfaceIndex)                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_I2C_SCL,         InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_I2C_SDA(InterfaceIndex)                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_I2C_SDA,         InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_I3C_SCL(InterfaceIndex)                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_I3C_SCL,         InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_I3C_SDA(InterfaceIndex)                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_I3C_SDA,         InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ISH_I3C_SCL_FB(InterfaceIndex)                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ISH,         GPIOV2_SIGNAL_TYPE_ISH_I3C_SCL_FB,      InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: THC (ID: 2)
//
#define GPIOV2_SIGNAL_THC_WOT                                                 GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_WOT,             SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_THC_SPI_INT(InstanceIndex)                              GPIOV2_SIGNAL_DEF(InstanceIndex,      GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_SPI_INT,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_THC_CLK_LOOPBACK(InstanceIndex)                         GPIOV2_SIGNAL_DEF(InstanceIndex,      GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_CLK_LOOPBACK,    SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_THC_CLK(InstanceIndex)                                  GPIOV2_SIGNAL_DEF(InstanceIndex,      GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_CLK,             SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_THC_IO0(InstanceIndex)                                  GPIOV2_SIGNAL_DEF(InstanceIndex,      GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_IO0,             SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_THC_IO1(InstanceIndex)                                  GPIOV2_SIGNAL_DEF(InstanceIndex,      GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_IO1,             SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_THC_IO2(InstanceIndex)                                  GPIOV2_SIGNAL_DEF(InstanceIndex,      GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_IO2,             SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_THC_IO3(InstanceIndex)                                  GPIOV2_SIGNAL_DEF(InstanceIndex,      GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_IO3,             SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_THC_RSTB(InstanceIndex)                                 GPIOV2_SIGNAL_DEF(InstanceIndex,      GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_RSTB,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_THC_CSB(InstanceIndex)                                  GPIOV2_SIGNAL_DEF(InstanceIndex,      GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_CSB,             SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_THC_I2C_SCL(InterfaceIndex)                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_I2C_SCL,         InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_THC_I2C_SDA(InterfaceIndex)                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_I2C_SDA,         InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_THC_DSYNC(InstanceIndex)                                GPIOV2_SIGNAL_DEF(InstanceIndex,      GPIOV2_PERIPHERAL_INTERFACE_THC,         GPIOV2_SIGNAL_TYPE_THC_DSYNC,           SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: HDA (ID: 3)
//
#define GPIOV2_SIGNAL_HDA_BCLK                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_HDA,         GPIOV2_SIGNAL_TYPE_HDA_BCLK,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_HDA_RSTB                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_HDA,         GPIOV2_SIGNAL_TYPE_HDA_RSTB,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_HDA_SYNC                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_HDA,         GPIOV2_SIGNAL_TYPE_HDA_SYNC,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_HDA_SDO                                                 GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_HDA,         GPIOV2_SIGNAL_TYPE_HDA_SDO,             SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_HDA_SDI(PinIndex)                                       GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_HDA,         GPIOV2_SIGNAL_TYPE_HDA_SDI,             SIGNAL_ZERO_INDEX,  PinIndex            )
#define GPIOV2_SIGNAL_HDA_CPU_BCLK                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_HDA,         GPIOV2_SIGNAL_TYPE_HDA_CPU_BCLK,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_HDA_CPU_SDI                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_HDA,         GPIOV2_SIGNAL_TYPE_HDA_CPU_SDI,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_HDA_CPU_SDO                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_HDA,         GPIOV2_SIGNAL_TYPE_HDA_CPU_SDO,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: DMIC (ID: 4)
//
#define GPIOV2_SIGNAL_DMIC_DATA(InterfaceIndex)                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DMIC,        GPIOV2_SIGNAL_TYPE_DMIC_DATA,           InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DMIC_CLKA(InterfaceIndex)                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DMIC,        GPIOV2_SIGNAL_TYPE_DMIC_CLKA,           InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DMIC_CLKB(InterfaceIndex)                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DMIC,        GPIOV2_SIGNAL_TYPE_DMIC_CLKB,           InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: SNDW (ID: 5)
//
#define GPIOV2_SIGNAL_SNDW_CLK(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SNDW,        GPIOV2_SIGNAL_TYPE_SNDW_CLK,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SNDW_DATA(InterfaceIndex)                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SNDW,        GPIOV2_SIGNAL_TYPE_SNDW_DATA,           InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SNDW_DATA0(InterfaceIndex)                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SNDW,        GPIOV2_SIGNAL_TYPE_SNDW_DATA0,          InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SNDW_DATA1(InterfaceIndex)                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SNDW,        GPIOV2_SIGNAL_TYPE_SNDW_DATA1,          InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SNDW_DATA2(InterfaceIndex)                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SNDW,        GPIOV2_SIGNAL_TYPE_SNDW_DATA2,          InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SNDW_DATA3(InterfaceIndex)                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SNDW,        GPIOV2_SIGNAL_TYPE_SNDW_DATA3,          InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: DDSP (ID: 6)
//
#define GPIOV2_SIGNAL_DDSP_HPD(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDSP,        GPIOV2_SIGNAL_TYPE_DDSP_HPD,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DDSP_HPD_A                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDSP,        GPIOV2_SIGNAL_TYPE_DDSP_HPD_A,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DDSP_HPD_B                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDSP,        GPIOV2_SIGNAL_TYPE_DDSP_HPD_B,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DDSP_HPD_C                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDSP,        GPIOV2_SIGNAL_TYPE_DDSP_HPD_C,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DDSP_HPDALV                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDSP,        GPIOV2_SIGNAL_TYPE_DDSP_HPDALV,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: PANEL (ID: 7)
//
#define GPIOV2_SIGNAL_PANEL_AVDD_EN                                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PANEL,       GPIOV2_SIGNAL_TYPE_PANEL_AVDD_EN,       SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PANEL_BKLTEN                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PANEL,       GPIOV2_SIGNAL_TYPE_PANEL_BKLTEN,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PANEL_BKLTCTL                                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PANEL,       GPIOV2_SIGNAL_TYPE_PANEL_BKLTCTL,       SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PANEL_AVDD_EN2                                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PANEL,       GPIOV2_SIGNAL_TYPE_PANEL_AVDD_EN2,      SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PANEL_BKLTEN2                                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PANEL,       GPIOV2_SIGNAL_TYPE_PANEL_BKLTEN2,       SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PANEL_BKLTCTL2                                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PANEL,       GPIOV2_SIGNAL_TYPE_PANEL_BKLTCTL2,      SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PANEL_RESET                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PANEL,       GPIOV2_SIGNAL_TYPE_PANEL_RESET,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PANEL_AVEE_EN                                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PANEL,       GPIOV2_SIGNAL_TYPE_PANEL_AVEE_EN,       SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PANEL_VIO_EN                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PANEL,       GPIOV2_SIGNAL_TYPE_PANEL_VIO_EN,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PANEL_HPD                                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PANEL,       GPIOV2_SIGNAL_TYPE_PANEL_HPD,           SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PANEL_TE_EN                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PANEL,       GPIOV2_SIGNAL_TYPE_PANEL_TE_EN,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: HDMI (ID: 8)
//
#define GPIOV2_SIGNAL_HDMI_GMBUS_SCL                                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_HDMI,        GPIOV2_SIGNAL_TYPE_HDMI_GMBUS_SCL,      SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_HDMI_GMBUS_SDA                                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_HDMI,        GPIOV2_SIGNAL_TYPE_HDMI_GMBUS_SDA,      SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: CNVI (ID: 9)
//
#define GPIOV2_SIGNAL_CNVI_RF_RESET                                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_RF_RESET,       SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CNVI_CLKREQ                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_CLKREQ,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CNVI_MFUART_RXD(InterfaceIndex)                         GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_MFUART_RXD,     InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CNVI_MFUART_TXD(InterfaceIndex)                         GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_MFUART_TXD,     InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CNVI_MFUART_RTS(InterfaceIndex)                         GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_MFUART_RTS,     InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CNVI_MFUART_CTS(InterfaceIndex)                         GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_MFUART_CTS,     InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CNVI_BRI_DT                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_BRI_DT,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CNVI_BRI_RSP                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_BRI_RSP,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CNVI_RGI_DT                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_RGI_DT,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CNVI_RGI_RSP                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_RGI_RSP,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CNVI_PA_BLANKING                                        GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_PA_BLANKING,    SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CNVI_DEBUG(InterfaceIndex)                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_DEBUG,          InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CNVI_DEBUG_A(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CNVI,        GPIOV2_SIGNAL_TYPE_CNVI_DEBUG_A,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: SD (ID: 10)
//
#define GPIOV2_SIGNAL_SD_PWR_EN_B                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SD,          GPIOV2_SIGNAL_TYPE_SD_PWR_EN_B,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SD_CMD                                                  GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SD,          GPIOV2_SIGNAL_TYPE_SD_CMD,              SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SD_DATA                                                 GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SD,          GPIOV2_SIGNAL_TYPE_SD_DATA,             SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SD_CDB                                                  GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SD,          GPIOV2_SIGNAL_TYPE_SD_CDB,              SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SD_CLK                                                  GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SD,          GPIOV2_SIGNAL_TYPE_SD_CLK,              SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SD_WP                                                   GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SD,          GPIOV2_SIGNAL_TYPE_SD_WP,               SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SD_1P8_EN                                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SD,          GPIOV2_SIGNAL_TYPE_SD_1P8_EN,           SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SD_CLK_FB                                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SD,          GPIOV2_SIGNAL_TYPE_SD_CLK_FB,           SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: EMMC (ID: 11)
//
#define GPIOV2_SIGNAL_EMMC_CMD                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_EMMC,        GPIOV2_SIGNAL_TYPE_EMMC_CMD,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_EMMC_DATA                                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_EMMC,        GPIOV2_SIGNAL_TYPE_EMMC_DATA,           SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_EMMC_RCLK                                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_EMMC,        GPIOV2_SIGNAL_TYPE_EMMC_RCLK,           SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_EMMC_CLK                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_EMMC,        GPIOV2_SIGNAL_TYPE_EMMC_CLK,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_EMMC_RESETB                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_EMMC,        GPIOV2_SIGNAL_TYPE_EMMC_RESETB,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: MIPI (ID: 12)
//
#define GPIOV2_SIGNAL_MIPI_PANEL_RESET                                        GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_MIPI,        GPIOV2_SIGNAL_TYPE_MIPI_PANEL_RESET,    SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_MIPI_SEC_POW_EN_AVEE                                    GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_MIPI,        GPIOV2_SIGNAL_TYPE_MIPI_SEC_POW_EN_AVEE,SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_MIPI_SEC_POW_EN_AVDD                                    GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_MIPI,        GPIOV2_SIGNAL_TYPE_MIPI_SEC_POW_EN_AVDD,SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: SATA (ID: 13)
//
#define GPIOV2_SIGNAL_SATA_DEVSLP                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SATA,        GPIOV2_SIGNAL_TYPE_SATA_DEVSLP,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SATA_LED(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SATA,        GPIOV2_SIGNAL_TYPE_SATA_LED,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SATA_GP(InterfaceIndex)                                 GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SATA,        GPIOV2_SIGNAL_TYPE_SATA_GP,             InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: PCIE (ID: 14)
//
#define GPIOV2_SIGNAL_PCIE_SRCCLKREQ(InterfaceIndex)                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PCIE,        GPIOV2_SIGNAL_TYPE_PCIE_SRCCLKREQ,      InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PCIE_LNK_DOWN                                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PCIE,        GPIOV2_SIGNAL_TYPE_PCIE_LNK_DOWN,       SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: USB (ID: 15)
//
#define GPIOV2_SIGNAL_USB_OC(InterfaceIndex)                                  GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_USB,         GPIOV2_SIGNAL_TYPE_USB_OC,              InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: ESPI (ID: 16)
//
#define GPIOV2_SIGNAL_ESPI_USB_OCB(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ESPI,        GPIOV2_SIGNAL_TYPE_ESPI_USB_OCB,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ESPI_ISCLK_XTAL_CLKREQ                                  GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ESPI,        GPIOV2_SIGNAL_TYPE_ESPI_ISCLK_XTAL_CLKREQ,SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ESPI_ISCLK_XTAL_CLKACK                                  GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ESPI,        GPIOV2_SIGNAL_TYPE_ESPI_ISCLK_XTAL_CLKACK,SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ESPI_VWM_SPARE(InterfaceIndex)                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ESPI,        GPIOV2_SIGNAL_TYPE_ESPI_VWM_SPARE,      InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ESPI_CLK                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ESPI,        GPIOV2_SIGNAL_TYPE_ESPI_CLK,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ESPI_IO(InterfaceIndex)                                 GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ESPI,        GPIOV2_SIGNAL_TYPE_ESPI_IO,             InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ESPI_CS(InterfaceIndex)                                 GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ESPI,        GPIOV2_SIGNAL_TYPE_ESPI_CS,             InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ESPI_ALERT(InterfaceIndex)                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ESPI,        GPIOV2_SIGNAL_TYPE_ESPI_ALERT,          InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_ESPI_RESET                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_ESPI,        GPIOV2_SIGNAL_TYPE_ESPI_RESET,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: SPI (ID: 17)
//
#define GPIOV2_SIGNAL_SPI_IO(InterfaceIndex)                                  GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SPI,         GPIOV2_SIGNAL_TYPE_SPI_IO,              InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SPI_MOSI                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SPI,         GPIOV2_SIGNAL_TYPE_SPI_MOSI,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SPI_MISO                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SPI,         GPIOV2_SIGNAL_TYPE_SPI_MISO,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SPI_TPM_CS                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SPI,         GPIOV2_SIGNAL_TYPE_SPI_TPM_CS,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SPI_FLASH_CS(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SPI,         GPIOV2_SIGNAL_TYPE_SPI_FLASH_CS,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SPI_CLK                                                 GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SPI,         GPIOV2_SIGNAL_TYPE_SPI_CLK,             SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: VR (ID: 18)
//
#define GPIOV2_SIGNAL_VR_ALERT                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VR,          GPIOV2_SIGNAL_TYPE_VR_ALERT,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: CPU (ID: 19)
//
#define GPIOV2_SIGNAL_CPU_C10_GATE                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CPU,         GPIOV2_SIGNAL_TYPE_CPU_C10_GATE,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CPU_GP(InterfaceIndex)                                  GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CPU,         GPIOV2_SIGNAL_TYPE_CPU_GP,              InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CPU_USB_OCB(InterfaceIndex)                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CPU,         GPIOV2_SIGNAL_TYPE_CPU_USB_OCB,         InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_CPU_PCIE_LNK_DN(InterfaceIndex)                         GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_CPU,         GPIOV2_SIGNAL_TYPE_CPU_PCIE_LNK_DN,     InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: DDP (ID: 20)
//
#define GPIOV2_SIGNAL_DDP_CTRL_CLK(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDP,         GPIOV2_SIGNAL_TYPE_DDP_CTRL_CLK,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DDP_CTRL_DATA(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDP,         GPIOV2_SIGNAL_TYPE_DDP_CTRL_DATA,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DDP_CTRL_CLK_A                                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDP,         GPIOV2_SIGNAL_TYPE_DDP_CTRL_CLK_A,      SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DDP_CTRL_DATA_A                                         GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDP,         GPIOV2_SIGNAL_TYPE_DDP_CTRL_DATA_A,     SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DDP_CTRL_CLK_B                                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDP,         GPIOV2_SIGNAL_TYPE_DDP_CTRL_CLK_B,      SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DDP_CTRL_DATA_B                                         GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDP,         GPIOV2_SIGNAL_TYPE_DDP_CTRL_DATA_B,     SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DDP_CTRL_CLK_C                                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDP,         GPIOV2_SIGNAL_TYPE_DDP_CTRL_CLK_C,      SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DDP_CTRL_DATA_C                                         GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DDP,         GPIOV2_SIGNAL_TYPE_DDP_CTRL_DATA_C,     SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: TIME (ID: 21)
//
#define GPIOV2_SIGNAL_TIME_SYNC(InterfaceIndex)                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_TIME,        GPIOV2_SIGNAL_TYPE_TIME_SYNC,           InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: SMB (ID: 22)
//
#define GPIOV2_SIGNAL_SMB_CLK                                                 GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SMB,         GPIOV2_SIGNAL_TYPE_SMB_CLK,             SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SMB_DATA                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SMB,         GPIOV2_SIGNAL_TYPE_SMB_DATA,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SMB_ALERT_B                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SMB,         GPIOV2_SIGNAL_TYPE_SMB_ALERT_B,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SMB_PCH_HOT_B                                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SMB,         GPIOV2_SIGNAL_TYPE_SMB_PCH_HOT_B,       SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SMB_SML_CLK(InterfaceIndex)                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SMB,         GPIOV2_SIGNAL_TYPE_SMB_SML_CLK,         InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SMB_SML_DATA(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SMB,         GPIOV2_SIGNAL_TYPE_SMB_SML_DATA,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SMB_SML_ALERT(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SMB,         GPIOV2_SIGNAL_TYPE_SMB_SML_ALERT,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SMB_SML_BCLK(InterfaceIndex)                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SMB,         GPIOV2_SIGNAL_TYPE_SMB_SML_BCLK,        InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SMB_SML_BDATA(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SMB,         GPIOV2_SIGNAL_TYPE_SMB_SML_BDATA,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_SMB_SML_BALERT(InterfaceIndex)                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_SMB,         GPIOV2_SIGNAL_TYPE_SMB_SML_BALERT,      InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: I2S (ID: 23)
//
#define GPIOV2_SIGNAL_I2S_SCLK(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_I2S,         GPIOV2_SIGNAL_TYPE_I2S_SCLK,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_I2S_SFRM(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_I2S,         GPIOV2_SIGNAL_TYPE_I2S_SFRM,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_I2S_TXD(InterfaceIndex)                                 GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_I2S,         GPIOV2_SIGNAL_TYPE_I2S_TXD,             InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_I2S_RXD(InterfaceIndex)                                 GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_I2S,         GPIOV2_SIGNAL_TYPE_I2S_RXD,             InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_I2S_MCLK                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_I2S,         GPIOV2_SIGNAL_TYPE_I2S_MCLK,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: IOM (ID: 24)
//
#define GPIOV2_SIGNAL_IOM_GPPC(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_IOM,         GPIOV2_SIGNAL_TYPE_IOM_GPPC,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_IOM_GPPA(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_IOM,         GPIOV2_SIGNAL_TYPE_IOM_GPPA,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_IOM_GPPE(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_IOM,         GPIOV2_SIGNAL_TYPE_IOM_GPPE,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_IOM_GPPH(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_IOM,         GPIOV2_SIGNAL_TYPE_IOM_GPPH,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_IOM_GPPF(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_IOM,         GPIOV2_SIGNAL_TYPE_IOM_GPPF,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_IOM_GPPB(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_IOM,         GPIOV2_SIGNAL_TYPE_IOM_GPPB,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_IOM_GPPD(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_IOM,         GPIOV2_SIGNAL_TYPE_IOM_GPPD,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_IOM_GPPR(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_IOM,         GPIOV2_SIGNAL_TYPE_IOM_GPPR,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_IOM_GPPJ(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_IOM,         GPIOV2_SIGNAL_TYPE_IOM_GPPJ,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_IOM_GPPI(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_IOM,         GPIOV2_SIGNAL_TYPE_IOM_GPPI,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_IOM_GPPK(InterfaceIndex)                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_IOM,         GPIOV2_SIGNAL_TYPE_IOM_GPPK,            InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: DISP (ID: 25)
//
#define GPIOV2_SIGNAL_DISP_MISC(InterfaceIndex)                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DISP,        GPIOV2_SIGNAL_TYPE_DISP_MISC,           InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DISP_MISC_A                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DISP,        GPIOV2_SIGNAL_TYPE_DISP_MISC_A,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DISP_MISC_B                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DISP,        GPIOV2_SIGNAL_TYPE_DISP_MISC_B,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_DISP_MISC_C                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_DISP,        GPIOV2_SIGNAL_TYPE_DISP_MISC_C,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: IPU (ID: 26)
//
#define GPIOV2_SIGNAL_IPU_IMGCLKOUT(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_IPU,         GPIOV2_SIGNAL_TYPE_IPU_IMGCLKOUT,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: TBT (ID: 27)
//
#define GPIOV2_SIGNAL_TBT_LSX_A(InterfaceIndex)                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_TBT,         GPIOV2_SIGNAL_TYPE_TBT_LSX_A,           InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_TBT_LSX_B(InterfaceIndex)                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_TBT,         GPIOV2_SIGNAL_TYPE_TBT_LSX_B,           InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_TBT_LSX_OE(InterfaceIndex)                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_TBT,         GPIOV2_SIGNAL_TYPE_TBT_LSX_OE,          InterfaceIndex,     SIGNAL_ZERO_INDEX   )
//
// Interface: PMC (ID: 28)
//
#define GPIOV2_SIGNAL_PMC_ALERT_B                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PMC,         GPIOV2_SIGNAL_TYPE_PMC_ALERT_B,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PMC_I2C_SDA                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PMC,         GPIOV2_SIGNAL_TYPE_PMC_I2C_SDA,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PMC_I2C_SCL                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PMC,         GPIOV2_SIGNAL_TYPE_PMC_I2C_SCL,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: PWR (ID: 29)
//
#define GPIOV2_SIGNAL_PWR_BATLOW                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_BATLOW,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_AC_PRESENT                                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_AC_PRESENT,      SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_SOC_WAKE                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_SOC_WAKE,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_PWRBTN                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_PWRBTN,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_SLP(InterfaceIndex)                                 GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_SLP,             InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_SLP_A                                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_SLP_A,           SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_SUSCLK                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_SUSCLK,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_SLP_WLAN                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_SLP_WLAN,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_LANPHYPC                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_LANPHYPC,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_SLP_LAN                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_SLP_LAN,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_WAKE                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_WAKE,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_CATERR                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_CATERR,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_FORCEPR                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_FORCEPR,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_THERMTRIP                                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_THERMTRIP,       SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_VCCST                                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_VCCST,           SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_SYS_PWROK                                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_SYS_PWROK,       SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_SYS_RESET                                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_SYS_RESET,       SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_MLK_RESET                                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_MLK_RESET,       SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_SX_HOLDOFF                                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_SX_HOLDOFF,      SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_SLP_DRAM                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_SLP_DRAM,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_PRIPWRDNACK                                         GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_PRIPWRDNACK,     SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_PRIACK                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_PRIACK,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_PLTRST                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_PLTRST,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_BOOTHALT                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_BOOTHALT,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_EPD_ON                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_EPD_ON,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PWR_VDD2_PWRGD                                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PWR,         GPIOV2_SIGNAL_TYPE_PWR_VDD2_PWRGD,      SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: MISC (ID: 30)
//
#define GPIOV2_SIGNAL_MISC_FUSA_DIAGTEST_EN                                   GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_MISC,        GPIOV2_SIGNAL_TYPE_MISC_FUSA_DIAGTEST_EN, SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_MISC_FUSA_DIAGTEST_MODE                                 GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_MISC,        GPIOV2_SIGNAL_TYPE_MISC_FUSA_DIAGTEST_MODE, SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_MISC_IEH_CORR_ERR                                       GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_MISC,        GPIOV2_SIGNAL_TYPE_MISC_IEH_CORR_ERR,   SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_MISC_IEH_NONFATAL_ERR                                   GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_MISC,        GPIOV2_SIGNAL_TYPE_MISC_IEH_NONFATAL_ERR, SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_MISC_IEH_FATAL_ERR                                      GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_MISC,        GPIOV2_SIGNAL_TYPE_MISC_IEH_FATAL_ERR,  SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_MISC_DNX_FORCE_RELOAD                                   GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_MISC,        GPIOV2_SIGNAL_TYPE_MISC_DNX_FORCE_RELOAD, SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_MISC_MIC_MUTE                                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_MISC,        GPIOV2_SIGNAL_TYPE_MISC_MIC_MUTE,       SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_MISC_MIC_MUTE_LED                                       GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_MISC,        GPIOV2_SIGNAL_TYPE_MISC_MIC_MUTE_LED,   SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: JTAG (ID: 31)
//
#define GPIOV2_SIGNAL_JTAG_MBPB(InterfaceIndex)                               GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_JTAG,        GPIOV2_SIGNAL_TYPE_JTAG_MBPB,           InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_JTAG_TDO                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_JTAG,        GPIOV2_SIGNAL_TYPE_JTAG_TDO,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_JTAG_TDI                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_JTAG,        GPIOV2_SIGNAL_TYPE_JTAG_TDI,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_JTAG_TCK                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_JTAG,        GPIOV2_SIGNAL_TYPE_JTAG_TCK,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_JTAG_TMS                                                GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_JTAG,        GPIOV2_SIGNAL_TYPE_JTAG_TMS,            SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_JTAG_TRST_B                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_JTAG,        GPIOV2_SIGNAL_TYPE_JTAG_TRST_B,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_JTAG_DBG_PMODE                                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_JTAG,        GPIOV2_SIGNAL_TYPE_JTAG_DBG_PMODE,      SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_JTAG_PREQ_B                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_JTAG,        GPIOV2_SIGNAL_TYPE_JTAG_PREQ_B,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_JTAG_PRDY_B                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_JTAG,        GPIOV2_SIGNAL_TYPE_JTAG_PRDY_B,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: OSSE (ID: 32)
//
#define GPIOV2_SIGNAL_OSSE_SMLCLK                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_OSSE,        GPIOV2_SIGNAL_TYPE_OSSE_SMLCLK,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_OSSE_SMLDATA                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_OSSE,        GPIOV2_SIGNAL_TYPE_OSSE_SMLDATA,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_OSSE_SMLALERT_B                                         GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_OSSE,        GPIOV2_SIGNAL_TYPE_OSSE_SMLALERT_B,     SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: USBC (ID: 33)
//
#define GPIOV2_SIGNAL_USBC_SMLCLK                                             GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_USBC,        GPIOV2_SIGNAL_TYPE_USBC_SMLCLK,         SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_USBC_SMLDATA                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_USBC,        GPIOV2_SIGNAL_TYPE_USBC_SMLDATA,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: UFS (ID: 34)
//
#define GPIOV2_SIGNAL_UFS_REFCLK                                              GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_UFS,         GPIOV2_SIGNAL_TYPE_UFS_REFCLK,          SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: VISA2CH1 (ID: 35)
//
#define GPIOV2_SIGNAL_VISA2CH1_DATA(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VISA2CH1,    GPIOV2_SIGNAL_TYPE_VISA2CH1_DATA,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_VISA2CH1_CLK                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VISA2CH1,    GPIOV2_SIGNAL_TYPE_VISA2CH1_CLK,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: VISA2CH2 (ID: 36)
//
#define GPIOV2_SIGNAL_VISA2CH2_DATA(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VISA2CH2,    GPIOV2_SIGNAL_TYPE_VISA2CH2_DATA,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_VISA2CH2_CLK                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VISA2CH2,    GPIOV2_SIGNAL_TYPE_VISA2CH2_CLK,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: VISA2CH3 (ID: 37)
//
#define GPIOV2_SIGNAL_VISA2CH3_DATA(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VISA2CH3,    GPIOV2_SIGNAL_TYPE_VISA2CH3_DATA,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_VISA2CH3_CLK                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VISA2CH3,    GPIOV2_SIGNAL_TYPE_VISA2CH3_CLK,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: VISA2CH4 (ID: 38)
//
#define GPIOV2_SIGNAL_VISA2CH4_DATA(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VISA2CH4,    GPIOV2_SIGNAL_TYPE_VISA2CH4_DATA,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_VISA2CH4_CLK                                            GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VISA2CH4,    GPIOV2_SIGNAL_TYPE_VISA2CH4_CLK,        SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: VISAFUSECH1 (ID: 39)
//
#define GPIOV2_SIGNAL_VISAFUSECH1_DATA(InterfaceIndex)                        GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VISAFUSECH1, GPIOV2_SIGNAL_TYPE_VISAFUSECH1_DATA,    InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_VISAFUSECH1_CLK                                         GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VISAFUSECH1, GPIOV2_SIGNAL_TYPE_VISAFUSECH1_CLK,     SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: VISAOSSEFUSECH1 (ID: 40)
//
#define GPIOV2_SIGNAL_VISAOSSEFUSECH1_DATA(InterfaceIndex)                    GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VISAOSSEFUSECH1, GPIOV2_SIGNAL_TYPE_VISAOSSEFUSECH1_DATA, InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_VISAOSSEFUSECH1_CLK                                     GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_VISAOSSEFUSECH1, GPIOV2_SIGNAL_TYPE_VISAOSSEFUSECH1_CLK, SIGNAL_ZERO_INDEX,  SIGNAL_ZERO_INDEX   )
//
// Interface: PTI_TRACE (ID: 41)
//
#define GPIOV2_SIGNAL_PTI_TRACE_DATA(InterfaceIndex)                          GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PTI_TRACE,   GPIOV2_SIGNAL_TYPE_PTI_TRACE_DATA,      InterfaceIndex,     SIGNAL_ZERO_INDEX   )
#define GPIOV2_SIGNAL_PTI_TRACE_CLK(InterfaceIndex)                           GPIOV2_SIGNAL_DEF(SIGNAL_ZERO_INDEX,  GPIOV2_PERIPHERAL_INTERFACE_PTI_TRACE,   GPIOV2_SIGNAL_TYPE_PTI_TRACE_CLK,       InterfaceIndex,     SIGNAL_ZERO_INDEX   )

#endif // _GPIOV2_SIGNALS_H_
