## @file
#  Private API to decompose the IFWI via FIT tool.
#
#  @copyright
#  INTEL CONFIDENTIAL
#  Copyright (C) 2023 Intel Corporation.
#
#  This software and the related documents are Intel copyrighted materials,
#  and your use of them is governed by the express license under which they
#  were provided to you ("License"). Unless the License provides otherwise,
#  you may not use, modify, copy, publish, distribute, disclose or transmit
#  this software or the related documents without Intel's prior written
#  permission.
#
#  This software and the related documents are provided as is, with no
#  express or implied warranties, other than those that are expressly stated
#  in the License.
#
#  @par Specification
#
##

import os
from typing import Dict, Union

from CapsuleGenerate._Global import *

class IfwiDecomposeApi (object):
    #
    # Get the FIT tool section configuration.
    #
    CFG_FIT_TOOL_SECTION: dict = gPlatformCfgData[FIT_TOOL_SECTION]

    #
    # Python script used for this API.
    #
    PY_DECOMPOSE_SCRIPT_PATH     : str = \
        JoinPath (
          WORKSPACE_PATH,
          CFG_FIT_TOOL_SECTION[IFWI_DECOMPOSER_SCRIPT_KEY],
          )
    PY_XML_CFG_PARSER_SCRIPT_PATH: str = \
        JoinPath (
          WORKSPACE_PATH,
          CFG_FIT_TOOL_SECTION[IFWI_XML_CONFIG_PARSER_SCRIPT_KEY],
          )

    #
    # Path of decompose and export directory.
    #
    IFWI_DECOMPOSE_DIR_PATH: str = \
        JoinPath (
          TEMPORARY_DIR_PATH,
          FIT_DECOMPOSE_DIR_NAME,
          )
    IFWI_EXPORT_DIR_PATH   : str = IFWI_DECOMPOSE_DIR_PATH

    def __init__ (
        self,
        IfwiPath   : Union[str, os.PathLike],
        FitToolPath: Union[str, os.PathLike],
        ) -> None:
        """ Class for API to decompose the IFWI via FIT tool.

        Args:
            IfwiPath (Union[str, os.PathLike]):
                The path of IFWI image to be decomposed.
            FitToolPath (Union[str, os.PathLike]):
                The FIT tool to support to do the decomposing.

        Raises:
            None

        Returns:
            None.
        """
        self.__IfwiPath   : str = AbsPath (IfwiPath)
        self.__FitToolPath: str = AbsPath (FitToolPath)

        self.__PreCheck ()

        self.__BiosFileName   : str = BIOS_DECOMPOSE_FILENAME
        self.__MeFileName     : str = ME_DECOMPOSE_FILENAME
        self.__EcFileName     : str = EC_DECOMPOSE_FILENAME
        self.__GbEFileName    : str = GBE_DECOMPOSE_FILENAME
        self.__IshPdtFileName : str = ISHPDT_DECOMPOSE_FILENAME
        self.__IfwiCfgFileName: str = IFWI_XML_CFG_FILENAME

    @property
    def FwInfo (self) -> Dict[str, str]:
        """ Return the firmware component and decomposed path mapping.

        Args:
            None.

        Raises:
            None.

        Returns:
            Dict[str, str]:
                str:
                    Name of firmware component.
                str:
                    Path of firmware component decomposed path.

        """
        DecomposePath: str = IfwiDecomposeApi.IFWI_DECOMPOSE_DIR_PATH

        return {
            FW_BIOS      : JoinPath (DecomposePath, self.__BiosFileName),
            FW_CSE_REGION: JoinPath (DecomposePath, self.__MeFileName),
            FW_EC        : JoinPath (DecomposePath, self.__EcFileName),
            FW_GBE       : JoinPath (DecomposePath, self.__GbEFileName),
            FW_ISH_PDT   : JoinPath (DecomposePath, self.__IshPdtFileName),
            }

    @property
    def XmlCfgFile (self) -> str:
        """ Return path of the IFWI XML configuration file.

        Args:
            None.

        Raises:
            None.

        Returns:
            str:
                Path of the IFWI XML configuration file.
                (File generated by FIT tool)
        """
        DecomposePath: str = IfwiDecomposeApi.IFWI_DECOMPOSE_DIR_PATH

        return JoinPath (DecomposePath, self.__IfwiCfgFileName)

    def __PreCheck (self) -> None:
        """ Check the input argument is valid.

        Args:
            None.

        Raises:
            None.

        Returns:
            None.
        """
        CheckPathList: List[str] = [
            IfwiDecomposeApi.PY_DECOMPOSE_SCRIPT_PATH,
            IfwiDecomposeApi.PY_XML_CFG_PARSER_SCRIPT_PATH,
            self.__IfwiPath,
            self.__FitToolPath,
            ]
        CheckFileListExist (CheckPathList)

    def Execute (self) -> int:
        """ Call the script to decompose the IFWI.

        Args:
            None.

        Raises:
            None.

        Returns:
            int:
                The exit code of IFWI decomposer script.
                (Detail exit code should be reference its own)
        """
        DecomposePath: str = IfwiDecomposeApi.IFWI_DECOMPOSE_DIR_PATH
        ExportPath   : str = IfwiDecomposeApi.IFWI_EXPORT_DIR_PATH
        ExitCode     : int = int ()

        DEBUG (DEBUG_INFO, f'>> Start to decompose the IFWI via FIT tool.')
        Cmd: List[str] = [
            f'{IfwiDecomposeApi.PY_DECOMPOSE_SCRIPT_PATH}',
            '-i', f'{self.__IfwiPath}',
            '-f', f'{self.__FitToolPath}',
            '-c', f'{IfwiDecomposeApi.PY_XML_CFG_PARSER_SCRIPT_PATH}',
            '-d', f'{DecomposePath}',
            '-e', f'{ExportPath}',
            #
            # Customize firmware component file name.
            #
            '-bios',   f'{self.__BiosFileName}',
            '-ec',     f'{self.__EcFileName}',
            '-me',     f'{self.__MeFileName}',
            '-gbe',    f'{self.__GbEFileName}',
            '-pdt',    f'{self.__IshPdtFileName}',
            '-config', f'{self.__IfwiCfgFileName}'
            ]

        ExitCode, _, _ = ExecPythonCmd (Cmd)
        DEBUG (DEBUG_INFO, f'>> Finish to decompose the IFWI via FIT tool.')

        return ExitCode

#
# Expose variables / methods / objects.
#
__all__: List[str] = [
    'IfwiDecomposeApi'
    ]
