/** @file
  File to contain all the hardware specific stuff for the Smm Gpi dispatch protocol.

  @copyright
  INTEL CONFIDENTIAL
  Copyright (C) 1999 Intel Corporation.

  This software and the related documents are Intel copyrighted materials,
  and your use of them is governed by the express license under which they
  were provided to you ("License"). Unless the License provides otherwise,
  you may not use, modify, copy, publish, distribute, disclose or transmit
  this software or the related documents without Intel's prior written
  permission.

  This software and the related documents are provided as is, with no
  express or implied warranties, other than those that are expressly stated
  in the License.

@par Specification Reference:
**/
#include "PchSmm.h"
#include "PchSmmHelpers.h"
#include <Library/SmiHandlerProfileLib.h>
#include <Register/GpioRegs.h>
#include <Register/PmcRegs.h>

//
// Structure for GPI SMI is a template which needs to have
// GPI Smi bit offset and Smi Status & Enable registers updated (accordingly
// to choosen group and pad number) after adding it to SMM Callback database
//

GLOBAL_REMOVE_IF_UNREFERENCED CONST PCH_SMM_SOURCE_DESC mPchGpiSourceDescTemplate = {
  PCH_SMM_NO_FLAGS,
  {
    NULL_BIT_DESC_INITIALIZER,
    NULL_BIT_DESC_INITIALIZER
  },
  {
    {
      {
        GPIO_ADDR_TYPE, {0x0}
      },
      S_GPIO_PCR_GP_SMI_STS, 0x0,
    }
  },
  {
    {
      ACPI_ADDR_TYPE,
      {R_ACPI_IO_SMI_STS}
    },
    S_ACPI_IO_SMI_STS,
    N_ACPI_IO_SMI_STS_GPIO_SMI_STS
  }
};

/**
  The register function used to register SMI handler of GPI SMI event.

  @param[in]  This               Pointer to the EFI_SMM_GPI_DISPATCH2_PROTOCOL instance.
  @param[in]  DispatchFunction   Function to register for handler when the specified GPI causes an SMI.
  @param[in]  RegisterContext    Pointer to the dispatch function's context.
                                 The caller fills this context in before calling
                                 the register function to indicate to the register
                                 function the GPI(s) for which the dispatch function
                                 should be invoked.
  @param[out] DispatchHandle     Handle generated by the dispatcher to track the
                                 function instance.

  @retval EFI_SUCCESS            The dispatch function has been successfully
                                 registered and the SMI source has been enabled.
  @retval EFI_ACCESS_DENIED      Register is not allowed
  @retval EFI_INVALID_PARAMETER  RegisterContext is invalid. The GPI input value
                                 is not within valid range.
  @retval EFI_OUT_OF_RESOURCES   There is not enough memory (system or SMM) to manage this child.
**/
EFI_STATUS
EFIAPI
PchGpiSmiRegister (
  IN CONST EFI_SMM_GPI_DISPATCH2_PROTOCOL  *This,
  IN       EFI_SMM_HANDLER_ENTRY_POINT2    DispatchFunction,
  IN       EFI_SMM_GPI_REGISTER_CONTEXT    *RegisterContext,
  OUT      EFI_HANDLE                      *DispatchHandle
  )
{
  EFI_STATUS                  Status;
  DATABASE_RECORD             Record;
  UINT8                       GpiSmiBitOffset;
  UINT64                      GpiHostSwOwnRegAddress;
  UINT64                      GpiSmiStsRegAddress;
  UINT32                      Data32Or;
  UINT32                      Data32And;
  GPIOV2_SERVICES             **GpioServices;
  GPIOV2_PAD                  GpioPad;
  UINT32                      GpioServicesCnt;

  GpiSmiStsRegAddress     =  0;
  GpiHostSwOwnRegAddress  =  0;
  GpiSmiBitOffset         =  0;

  //
  // Return access denied if the SmmReadyToLock event has been triggered
  // Temporarily allow Smi Register/Unregister when Mm Runtime Update is in progress
  //
  if (PchSmiReigsterIsLocked ()) {
    DEBUG ((DEBUG_ERROR, "Register is not allowed if the EndOfDxe event has been triggered! \n"));
    return EFI_ACCESS_DENIED;
  }

  Status = GpioV2GetAllServices (NULL, &GpioServicesCnt);
  if (EFI_ERROR (Status)) {
    DEBUG ((DEBUG_ERROR, "%a - failed to get GPIO accesses\n", __FUNCTION__));
    return EFI_NOT_FOUND;
  } else {
    GpioServices = AllocateZeroPool (sizeof(GPIOV2_SERVICES *) * GpioServicesCnt);
    if (GpioServices == NULL){
      DEBUG ((DEBUG_ERROR, "Fail to allocate memory for GpioServices!\n"));
      return EFI_OUT_OF_RESOURCES;
    }
    GpioV2GetAllServices (GpioServices, &GpioServicesCnt);
    //
    // For now this library does not support multiple dies. Take first instance of GPIO service since there should be only one installed.
    //
    GpioServices[0]->GetPadAndSmiRegs (
                       GpioServices[0],
                       (UINT32) RegisterContext->GpiNum,
                       &GpioPad,
                       &GpiSmiBitOffset,
                       &GpiHostSwOwnRegAddress,
                       &GpiSmiStsRegAddress
                       );
    FreePool (GpioServices);
    GpioServices = NULL;
  }

  ZeroMem (&Record, sizeof (DATABASE_RECORD));

  //
  // Gather information about the registration request
  //
  Record.Callback          = DispatchFunction;
  Record.ChildContext.Gpi  = *RegisterContext;
  Record.ProtocolType      = GpiType;
  Record.Signature         = DATABASE_RECORD_SIGNATURE;

  CopyMem (&Record.SrcDesc, &mPchGpiSourceDescTemplate, sizeof (PCH_SMM_SOURCE_DESC) );

  Record.SrcDesc.Sts[0].Reg.Data.raw = GpiSmiStsRegAddress;  // GPI SMI Status register
  Record.SrcDesc.Sts[0].Bit = GpiSmiBitOffset;               // Bit position for selected pad

  //
  // Insert GpiSmi handler to PchSmmCore database
  //
  *DispatchHandle = NULL;

  Status = SmmCoreInsertRecord (
             &Record,
             DispatchHandle
             );
  ASSERT_EFI_ERROR (Status);

  SmiHandlerProfileRegisterHandler (
    &gEfiSmmGpiDispatch2ProtocolGuid,
    (EFI_SMM_HANDLER_ENTRY_POINT2) DispatchFunction,
    (UINTN)RETURN_ADDRESS (0),
    RegisterContext,
    sizeof(*RegisterContext)
    );

  //
  // Enable GPI SMI
  // HOSTSW_OWN with respect to generating GPI SMI has negative logic:
  //  - 0 (ACPI mode) - GPIO pad will be capable of generating SMI/NMI/SCI
  //  - 1 (GPIO mode) - GPIO pad will not generate SMI/NMI/SCI
  //
  Data32And  = (UINT32)~(1u << GpiSmiBitOffset);
  MmioAnd32 (GpiHostSwOwnRegAddress, Data32And);

  //
  // Add HOSTSW_OWN programming into S3 boot script
  //
  Data32Or = 0;
  S3BootScriptSaveMemReadWrite (S3BootScriptWidthUint32, GpiHostSwOwnRegAddress, &Data32Or, &Data32And);

  return EFI_SUCCESS;
}

/**
  Unregister a GPI SMI source dispatch function with a parent SMM driver

  @param[in] This                 Pointer to the EFI_SMM_GPI_DISPATCH2_PROTOCOL instance.
  @param[in] DispatchHandle       Handle of dispatch function to deregister.

  @retval EFI_SUCCESS             The dispatch function has been successfully
                                  unregistered and the SMI source has been disabled
                                  if there are no other registered child dispatch
                                  functions for this SMI source.
  @retval EFI_INVALID_PARAMETER   Handle is invalid.
**/
EFI_STATUS
EFIAPI
PchGpiSmiUnRegister (
  IN CONST EFI_SMM_GPI_DISPATCH2_PROTOCOL  *This,
  IN       EFI_HANDLE                      DispatchHandle
  )
{
  EFI_STATUS      Status;
  DATABASE_RECORD *RecordToDelete;
  DATABASE_RECORD *RecordInDb;
  LIST_ENTRY      *LinkInDb;
  UINT8           GpiSmiBitOffset;
  UINT64          GpiHostSwOwnRegAddress;
  UINT64          GpiSmiStsRegAddress;
  UINT32          Data32Or;
  UINT32          Data32And;
  BOOLEAN         DisableGpiSmiSource;
  GPIOV2_SERVICES      **GpioServices;
  GPIOV2_PAD           GpioPad;
  UINT32               GpioServicesCnt;

  GpiHostSwOwnRegAddress  =  0;
  GpiSmiBitOffset         =  0;

  if (DispatchHandle == NULL) {
    return EFI_INVALID_PARAMETER;
  }

  RecordToDelete = DATABASE_RECORD_FROM_LINK (DispatchHandle);
  if ((RecordToDelete->Signature != DATABASE_RECORD_SIGNATURE) ||
      (RecordToDelete->ProtocolType != GpiType)) {
    return EFI_INVALID_PARAMETER;
  }

  //
  // Return access denied if the SmmReadyToLock event has been triggered
  // Temporarily allow Smi Register/Unregister when Mm Runtime Update is in progress
  //
  if (PchSmiReigsterIsLocked ()) {
    DEBUG ((DEBUG_ERROR, "UnRegister is not allowed if the SmmReadyToLock event has been triggered! \n"));
    return EFI_ACCESS_DENIED;
  }

  DisableGpiSmiSource = TRUE;
  //
  // Loop through all sources in record linked list to see if any other GPI SMI
  // is installed on the same pin. If no then disable GPI SMI capability on this pad
  //
  LinkInDb = GetFirstNode (&mPrivateData.CallbackDataBase);
  while (!IsNull (&mPrivateData.CallbackDataBase, LinkInDb)) {
    RecordInDb = DATABASE_RECORD_FROM_LINK (LinkInDb);
    LinkInDb = GetNextNode (&mPrivateData.CallbackDataBase, &RecordInDb->Link);
    //
    // If this is the record to delete skip it
    //
    if (RecordInDb == RecordToDelete) {
      continue;
    }
    //
    // Check if record is GPI SMI type
    //
    if (RecordInDb->ProtocolType == GpiType) {
      //
      // Check if same GPIO pad is the source of this SMI
      //
      if (RecordInDb->ChildContext.Gpi.GpiNum == RecordToDelete->ChildContext.Gpi.GpiNum) {
        DisableGpiSmiSource = FALSE;
        break;
      }
    }
  }

  if (DisableGpiSmiSource) {
    Status = GpioV2GetAllServices (NULL, &GpioServicesCnt);
    if (EFI_ERROR (Status)) {
      DEBUG ((DEBUG_ERROR, "%a - failed to get GPIO accesses\n", __FUNCTION__));
      return EFI_NOT_FOUND;
    } else {
      GpioServices = AllocateZeroPool (sizeof(GPIOV2_SERVICES *) * GpioServicesCnt);
      if (GpioServices == NULL){
        DEBUG ((DEBUG_ERROR, "Fail to allocate memory for GpioServices!\n"));
        return EFI_OUT_OF_RESOURCES;
      }
      GpioV2GetAllServices (GpioServices, &GpioServicesCnt);
      //
      // For now this library does not support multiple dies. Take first instance of GPIO service since there should be only one installed.
      //
      GpioServices[0]->GetPadAndSmiRegs (
                        GpioServices[0],
                        (UINT32) RecordToDelete->ChildContext.Gpi.GpiNum,
                        &GpioPad,
                        &GpiSmiBitOffset,
                        &GpiHostSwOwnRegAddress,
                        &GpiSmiStsRegAddress
                        );
      FreePool (GpioServices);
      GpioServices = NULL;
    }

    Data32Or = 1u << GpiSmiBitOffset;
    Data32And = 0xFFFFFFFF;
    MmioOr32 (GpiHostSwOwnRegAddress, Data32Or);
    S3BootScriptSaveMemReadWrite (S3BootScriptWidthUint32, GpiHostSwOwnRegAddress, &Data32Or, &Data32And);
  }


  RemoveEntryList (&RecordToDelete->Link);
  ZeroMem (RecordToDelete, sizeof (DATABASE_RECORD));
  Status = gSmst->SmmFreePool (RecordToDelete);

  if (EFI_ERROR (Status)) {
    ASSERT (FALSE);
    return Status;
  }
  SmiHandlerProfileUnregisterHandler (
    &gEfiSmmGpiDispatch2ProtocolGuid,
    RecordToDelete->Callback,
    &RecordToDelete->ChildContext,
    RecordToDelete->ContextSize
    );
  return EFI_SUCCESS;
}
